### ISSUE TITLE
[BUG] Disabling SkBee on start of server

### ISSUE THREAD

**Issue by emergenitro** [ShaneBeee/SkBee#101]
**Describe the bug**

> [15:20:01 INFO]: [SkBee] Enabling SkBee v1.10.0
> [15:20:01 INFO]: [SkBee] Loading NBTApi...
> [15:20:01 INFO]: [SkBee] [NBTAPI] Found Spigot: v1_8_R3! Trying to find NMS support
> [15:20:01 INFO]: [SkBee] [NBTAPI] NMS support 'MC1_8_R3' loaded!
> [15:20:01 INFO]: [SkBee] [NBTAPI] Found Gson: class com.google.gson.Gson
> [15:20:01 INFO]: [SkBee] [NBTAPI] Using the plugin 'Skript' to create a bStats instance!
> [15:20:01 INFO]: [SkBee] Successfully loaded NBTApi!
> [15:20:01 ERROR]: [SkBee] Plugin SkBee v1.10.0 has failed to register events for class tk.shanebee.bee.api.listener.NBTListener because org.bukkit.block.data.BlockData does not exist.
> [15:20:01 INFO]: [SkBee] NBT Elements successfully loaded
> [15:20:01 INFO]: [SkBee] Recipe Elements disabled
> [15:20:01 INFO]: [SkBee] - Recipe elements are only available on 1.13+
> [15:20:01 INFO]: [SkBee] Scoreboard Elements successfully loaded
> [15:20:01 INFO]: [SkBee] Bound Elements successfully loaded
> [15:20:01 INFO]: [SkBee] Text Component Elements successfully loaded
> [15:20:01 INFO]: [SkBee] Pathfinding disabled
> [15:20:01 INFO]: [SkBee] - Pathfinding elements are only available on Paper 1.13+
> [15:20:01 INFO]: [SkBee] Structure Elements disabled
> [15:20:01 INFO]: [SkBee] - Structure elements are only available on 1.9.4+
> [15:20:02 ERROR]: Error occurred while enabling SkBee v1.10.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org.bukkit.Keyed
at java.lang.Class.forNameImpl(Native Method) ~[?:1.8.0_232]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_232]
at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
at tk.shanebee.bee.SkBee.loadOtherElements(SkBee.java:267) ~[?:?]
at tk.shanebee.bee.SkBee.onEnable(SkBee.java:73) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Keyed
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.ClassLoader.loadClassHelper(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_232]
... 16 more

I'm getting this error.. Idk why or how it's being produced and hence, I'm not sure how to reproduce it

**To Reproduce**
Unsure

**Expected behavior**
Should normally start

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/49610482/105363793-63aa6480-5c37-11eb-9a77-e7496063fe15.png)
![image](https://user-images.githubusercontent.com/49610482/105363800-65742800-5c37-11eb-9eae-10f3be96523f.png)
![image](https://user-images.githubusercontent.com/49610482/105363802-660cbe80-5c37-11eb-8b58-35a9289f765d.png)

**Version Info:**
 - **SkBee Version: 1.10.0** (ex: 1.0.0)
-  **Skript Version: dev36** (ex: Skript 2.5-alpha3)
 - **Server Version/Platform: PaperSpigot 1.8.8** (ex: Spigot 1.15.2)

**Additional context**
N/A

**Comment by ShaneBeee** [comment]
Thanks for officially posting this.

It has been reported (on discord) and fixed https://github.com/ShaneBeee/SkBee/commit/1f0592875003c441ae950f3e908bbb5e88d646dd

Will appear in the next update.
Don't worry about closing this issue. I will close it when i release the next update.
