### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by MrEnxo** [ShaneBeee/SkBee#127]
```
[00:05:47] [Server thread/ERROR]: #!#! Stack trace:
[00:05:47] [Server thread/ERROR]: #!#! java.util.ConcurrentModificationException
[00:05:47] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1011)
[00:05:47] [Server thread/ERROR]: #!#!     at com.shanebeestudios.skbee.api.NBT.NBTCustomBlock.setData(NBTCustomBlock.java:40)
[00:05:47] [Server thread/ERROR]: #!#!     at com.shanebeestudios.skbee.api.NBT.NBTCustomBlock.getData(NBTCustomBlock.java:28)
[00:05:47] [Server thread/ERROR]: #!#!     at com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.lambda$get$0(ExprNbtCompound.java:80)
[00:05:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:390)
[00:05:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:381)
[00:05:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:102)
[00:05:47] [Server thread/ERROR]: #!#!     at com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:71)
[00:05:47] [Server thread/ERROR]: #!#!     at com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:36)
[00:05:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:73)
[00:05:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[00:05:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:57)
[00:05:47] [Server thread/ERROR]: #!#!     at com.shanebeestudios.skbee.elements.nbt.expressions.ExprTagOfNBT.change(ExprTagOfNBT.java:109)
[00:05:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:281)
[00:05:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[00:05:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[00:05:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[00:05:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[00:05:47] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82)
[00:05:47] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[00:05:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269)
[00:05:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
[00:05:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217)
[00:05:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050)
[00:05:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[00:05:47] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
```

On 1.17 this happens everytime I try to set nbt on like any block except logs.

**Comment by ShaneBeee** [comment]
Can you post the rest of the error please

**Comment by MrEnxo** [comment]
```
[00:31:29] [Server thread/ERROR]: #!#! 
[00:31:29] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[00:31:29] [Server thread/ERROR]: #!#! 
[00:31:29] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[00:31:29] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:31:29] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:31:29] [Server thread/ERROR]: #!#! Here is full list of them:
[00:31:29] [Server thread/ERROR]: #!#! skRayFall v1.9.21 (https://sk.rayfall.net/) SkriptJSON v1.0.0 skript-gui v1.3-beta1 (https://github.com/APickledWalrus/skript-gui) SkJade v1.3.2 (https://www.github.com/Ankoki-Dev/SkJade) SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee) SkQuery v4.1.5 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/) Skent v2.1.0 
[00:31:29] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:31:29] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:31:29] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:31:29] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:31:29] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:31:29] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:31:29] [Server thread/ERROR]: #!#! 
[00:31:29] [Server thread/ERROR]: #!#! Stack trace:
[00:31:29] [Server thread/ERROR]: #!#! java.util.ConcurrentModificationException
[00:31:29] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1011)
[00:31:29] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBT.NBTCustomBlock.setData(NBTCustomBlock.java:40)
[00:31:29] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBT.NBTCustomBlock.getData(NBTCustomBlock.java:28)
[00:31:29] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprNbtCompound.lambda$get$0(ExprNbtCompound.java:74)
[00:31:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:390)
[00:31:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:381)
[00:31:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:102)
[00:31:29] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:65)
[00:31:29] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:32)
[00:31:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:73)
[00:31:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[00:31:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:57)
[00:31:29] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprTagOfNBT.change(ExprTagOfNBT.java:110)
[00:31:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:281)
[00:31:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[00:31:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[00:31:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[00:31:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[00:31:29] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82)
[00:31:29] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[00:31:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269)
[00:31:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
[00:31:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217)
[00:31:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050)
[00:31:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[00:31:29] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[00:31:29] [Server thread/ERROR]: #!#! 
[00:31:29] [Server thread/ERROR]: #!#! Version Information:
[00:31:29] [Server thread/ERROR]: #!#!   Skript: 2.6 (latest)
[00:31:29] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[00:31:29] [Server thread/ERROR]: #!#!     Date: 17:20:35.482878100
[00:31:29] [Server thread/ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[00:31:29] [Server thread/ERROR]: #!#!   Minecraft: 1.17.1
[00:31:29] [Server thread/ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[00:31:29] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.11.0-41-generic
[00:31:29] [Server thread/ERROR]: #!#! 
[00:31:29] [Server thread/ERROR]: #!#! Server platform: Spigot
[00:31:29] [Server thread/ERROR]: #!#! 
[00:31:29] [Server thread/ERROR]: #!#! Current node: null
[00:31:29] [Server thread/ERROR]: #!#! Current item: set tag "custom;player" of nbt compound from loop-block to [[long:1]]
[00:31:29] [Server thread/ERROR]: #!#! Current trigger: function reset_mine (simple event) (mines.sk, line 46)
[00:31:29] [Server thread/ERROR]: #!#! 
[00:31:29] [Server thread/ERROR]: #!#! Thread: Server thread
[00:31:29] [Server thread/ERROR]: #!#! 
[00:31:29] [Server thread/ERROR]: #!#! Language: english
[00:31:29] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[00:31:29] [Server thread/ERROR]: #!#! 
[00:31:29] [Server thread/ERROR]: #!#! End of Error.
[00:31:29] [Server thread/ERROR]: #!#! 
```

```
function reset_mine(mine: string):
	loop all blocks within {mines::%{_mine}%::pos-2} and {mines::%{_mine}%::pos-1}:
		set loop-block to air
	loop all blocks within {mines::%{_mine}%::pos-2} and {mines::%{_mine}%::pos-1}:
		set loop-block to random element out of {mines::%{_mine}%::blocks::*}
		wait 1 ticks
	wait 10 ticks
	loop all blocks within {mines::%{_mine}%::pos-2} and {mines::%{_mine}%::pos-1}:	
		set tag "custom;player" of nbt compound of loop-block to 1
```
^ This is the Code that errors

**Comment by MrEnxo** [comment]
bump

**Comment by ShaneBeee** [comment]
> bump

You don’t need to bump this.  I get emails for everything here. 
when I have some time, I’ll talk a look at the issue.

**Comment by MrEnxo** [comment]
lol alright

**Comment by ShaneBeee** [comment]
> SkBee v1.11.2

I noticed you're using a REALLY old version of SkBee (current version of SkBee = 1.14.1), can you please try update your SkBee and see if the problem persists.
I've tried replicating this and can not make it happen. 
I have seen this issue in the past, I just cant seem to replicate it, and its quite hard to debug/fix an issue if I can not replicate it.

**Comment by ShaneBeee** [comment]
Closing as I have not gotten any response in about a month
