### ISSUE TITLE
[BUG] Deprecated Method For Crafting Recipe Registration

### ISSUE THREAD

**Issue by Rebble69** [ShaneBeee/SkBee#128]
**Describe the bug**
Deprecated Method For Crafting Recipe Registration

**To Reproduce**
register a new crafting recipe

**Screenshots/Errors**
```
[22:50:40 WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[22:50:40 WARN]:        at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:28)
[22:50:40 WARN]:        at SkQuery.jar//com.w00tmast3r.skquery.elements.effects.EffNewRecipe.execute(EffNewRecipe.java:55)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:51)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.events.EvtScript.runTrigger(EvtScript.java:88)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.events.EvtScript.register(EvtScript.java:68)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScript$9(ScriptLoader.java:816)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:839)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$5(ScriptLoader.java:533)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:420)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:436)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:532)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:473)
[22:50:40 WARN]:        at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:748)
[22:50:40 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:50:40 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[22:50:40 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1226)
[22:50:40 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[22:50:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Version Info:**
 - **SkBee Version:** 1.4.1
-  **Skript Version:** 2.6
 - **Server Version/Platform** spigot 1.17.1

**Comment by ShaneBeee** [comment]
You must be lost. 
this issue tracker is for SkBee, that error is from SKQuery

**Comment by Rebble69** [comment]
wait i am actually an idiot. thanks
