### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ezcente** [ShaneBeee/SkBee#133]
**Describe the bug**
[23:22:47 ERROR]: #!#! [23:22:47 ERROR]: #!#! [Skript] Severe Error: [23:22:47 ERROR]: #!#! SkBee's class tk.shanebee.bee.elements.other.type.Types generated an exception while loading [23:22:47 ERROR]: #!#! [23:22:47 ERROR]: #!#! Something went horribly wrong with Skript. [23:22:47 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either. [23:22:47 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons). [23:22:47 ERROR]: #!#! Following plugins are probably related to this error in some way: [23:22:47 ERROR]: #!#! SkBee (https://github.com/ShaneBeee/SkBee) [23:22:47 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it. [23:22:47 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue. [23:22:47 ERROR]: #!#! In that case, you will be given instruction on how should you report it. [23:22:47 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin. [23:22:47 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker. [23:22:47 ERROR]: #!#! [23:22:47 ERROR]: #!#! Stack trace: [23:22:47 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "java.lang.Class.getMethod(String, java.lang.Class[])" because "mcKey" is null [23:22:47 ERROR]: #!#!     at SkBee 1.9.1.jar//tk.shanebee.bee.api.util.ParticleUtil.<clinit>(ParticleUtil.java:44) [23:22:47 ERROR]: #!#!     at SkBee 1.9.1.jar//tk.shanebee.bee.elements.other.type.Types.<clinit>(Types.java:30) [23:22:47 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method) [23:22:47 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467) [23:22:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) [23:22:47 ERROR]: #!#!     at SkBee 1.9.1.jar//tk.shanebee.bee.SkBee.loadOtherElements(SkBee.java:265) [23:22:47 ERROR]: #!#!     at SkBee 1.9.1.jar//tk.shanebee.bee.SkBee.onEnable(SkBee.java:72) [23:22:47 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [23:22:47 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) [23:22:47 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) [23:22:47 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) [23:22:47 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) [23:22:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) [23:22:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) [23:22:47 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313) [23:22:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202) [23:22:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) [23:22:47 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833) [23:22:47 ERROR]: #!#! [23:22:47 ERROR]: #!#! Version Information: [23:22:47 ERROR]: #!#!   Skript: 2.6.1 (latest) [23:22:47 ERROR]: #!#!     Flavor: skriptlang-github [23:22:47 ERROR]: #!#!     Date: 22:18:42.554713200 [23:22:47 ERROR]: #!#!   Bukkit: 1.18.1-R0.1-SNAPSHOT [23:22:47 ERROR]: #!#!   Minecraft: 1.18.1 [23:22:47 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12) [23:22:47 ERROR]: #!#!   OS: Linux amd64 5.13.0-27-generic [23:22:47 ERROR]: #!#! [23:22:47 ERROR]: #!#! Server platform: Paper [23:22:47 ERROR]: #!#! [23:22:47 ERROR]: #!#! Current node: null [23:22:47 ERROR]: #!#! Current item: null [23:22:47 ERROR]: #!#! [23:22:47 ERROR]: #!#! Thread: Server thread [23:22:47 ERROR]: #!#! [23:22:47 ERROR]: #!#! Language: english [23:22:47 ERROR]: #!#! Link parse mode: DISABLED [23:22:47 ERROR]: #!#! [23:22:47 ERROR]: #!#! End of Error. [23:22:47 ERROR]: #!#!

**To Reproduce**
I am unsure.

**Expected behavior**
Unable to load into the server.

**Version Info:**
 - **SkBee Version:** (1.9.1)
-  **Skript Version:** (Skript 2.6.1)
 - **Server Version/Platform** (Paper 1.18.1)

**Comment by ShaneBeee** [comment]
Can you please repost the error, with proper spacing and in code tags.
The error you currently have is nearly impossible to read.

**Comment by Ezcente** [comment]
I'm sorry, it was a bug in the config of the bukkit.yml.
