### ISSUE TITLE
[BUG] Server Error while starting

### ISSUE THREAD

**Issue by RealRayli** [ShaneBeee/SkBee#145]
[15:48:28 INFO]: [SkBee] Enabling SkBee v1.15.1
[15:48:28 INFO]: [SkBee] Loading NBTApi...
[15:48:28 INFO]: [SkBee] [NBTAPI] Found Spigot: v1_18_R2! Trying to find NMS support
[15:48:28 INFO]: [SkBee] [NBTAPI] NMS support 'MC1_18_R2' loaded!
[15:48:28 INFO]: [SkBee] [NBTAPI] Found Gson: class com.google.gson.Gson
[15:48:28 INFO]: [SkBee] Successfully loaded NBTApi!
[15:48:28 INFO]: [SkBee] NBT Elements successfully loaded
[15:48:28 INFO]: [SkBee] Recipe Elements successfully loaded
[15:48:28 ERROR]: #!#! 
[15:48:28 ERROR]: #!#! [Skript] Severe Error:
[15:48:28 ERROR]: #!#! SkBee's class com.shanebeestudios.skbee.elements.board.type.Types generated an exception while loading
[15:48:28 ERROR]: #!#! 
[15:48:28 ERROR]: #!#! Something went horribly wrong with Skript.
[15:48:28 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:48:28 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:48:28 ERROR]: #!#! Following plugins are probably related to this error in some way:
[15:48:28 ERROR]: #!#! SkBee (https://github.com/ShaneBeee/SkBee) 
[15:48:28 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:48:28 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:48:28 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:48:28 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:48:28 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:48:28 ERROR]: #!#! 
[15:48:28 ERROR]: #!#! Stack trace:
[15:48:28 ERROR]: #!#! java.lang.IllegalArgumentException: Can't register org.bukkit.scoreboard.Team$OptionStatus with the code name teamoptionstatus because that name is already used by team option status
[15:48:28 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.registerClass(Classes.java:92)
[15:48:28 ERROR]: #!#!     at SkBee-1.15.1.jar//com.shanebeestudios.skbee.elements.board.type.Types.<clinit>(Types.java:28)
[15:48:28 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[15:48:28 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:466)
[15:48:28 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107)
[15:48:28 ERROR]: #!#!     at SkBee-1.15.1.jar//com.shanebeestudios.skbee.SkBee.loadBoardElements(SkBee.java:177)
[15:48:28 ERROR]: #!#!     at SkBee-1.15.1.jar//com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:102)
[15:48:28 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:48:28 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:48:28 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[15:48:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[15:48:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[15:48:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[15:48:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[15:48:28 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[15:48:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[15:48:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[15:48:28 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[15:48:28 ERROR]: #!#! 
[15:48:28 ERROR]: #!#! Version Information:
[15:48:28 ERROR]: #!#!   Skript: 2.6
[15:48:28 ERROR]: #!#!     Flavor: skriptlang-github
[15:48:28 ERROR]: #!#!     Date: 17:20:35.482878100
[15:48:28 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[15:48:28 ERROR]: #!#!   Minecraft: 1.18.2
[15:48:28 ERROR]: #!#!   Java: 17-ea (OpenJDK 64-Bit Server VM 17-ea+17-1401)
[15:48:28 ERROR]: #!#!   OS: Linux amd64 4.19.0-17-amd64
[15:48:28 ERROR]: #!#! 
[15:48:28 ERROR]: #!#! Server platform: Paper
[15:48:28 ERROR]: #!#! 
[15:48:28 ERROR]: #!#! Current node: null
[15:48:28 ERROR]: #!#! Current item: null
[15:48:28 ERROR]: #!#! 
[15:48:28 ERROR]: #!#! Thread: Server thread
[15:48:28 ERROR]: #!#! 
[15:48:28 ERROR]: #!#! Language: english
[15:48:28 ERROR]: #!#! Link parse mode: DISABLED
[15:48:28 ERROR]: #!#! 
[15:48:28 ERROR]: #!#! End of Error.
[15:48:28 ERROR]: #!#! 
[15:48:28 INFO]: [SkBee] Scoreboard Elements successfully loaded
[15:48:28 INFO]: [SkBee] Bound Elements successfully loaded
[15:48:28 INFO]: [SkBee] Text Component Elements successfully loaded
[15:48:28 INFO]: [SkBee] Pathfinding Elements successfully loaded
[15:48:28 INFO]: [SkBee] Structure Elements disabled via config
[15:48:28 INFO]: [SkBee] Other Elements successfully loaded
[15:48:28 INFO]: [SkBee] Virtual Furnace Elements disabled via config
[15:48:28 INFO]: [SkBee] World Creator Elements successfully loaded
[15:48:28 INFO]: [SkBee] Game Event Elements successfully loaded
[15:48:28 INFO]: [SkBee] Successfully enabled v1.15.1 in 0.20

________________________________________________________________________________

[16:11:21 INFO]: [Skript] Server Version: git-Paper-259 (MC: 1.18.2)
[16:11:21 INFO]: [Skript] Skript Version: 2.6
[16:11:21 INFO]: [Skript] Installed Skript Addons:
[16:11:21 INFO]: [Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[16:11:21 INFO]: [Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[16:11:21 INFO]: [Skript]  - SkBee v1.15.1 (https://github.com/ShaneBeee/SkBee)
[16:11:21 INFO]: [Skript]  - Skript-Packet v2.0.1 (www.github.com/Anarchick/skript-packet)

________________________________________________________________________________

Hey there,

today ive updated to 1.18.2 and get this error.
As i logged in everything was fine but as i want to interact in my bound everything is none so i cant do anything in it.
Hope it can be fixed as soon as possible.

**Comment by ShaneBeee** [comment]
duplicate #137
