### ISSUE TITLE
[BUG] Can't use Sk-NBeeT codes

### ISSUE THREAD

**Issue by rudde0** [ShaneBeee/SkBee#17]
**Describe the bug**
All sk-nbeet codes are throwing errors.

**To Reproduce**
I deleted Sk-NBeeT
I added SkBee with `elements.nbt: true` value

**Expected behavior**
Should be no difference :D 

**Screenshots/Errors**
```
[12:53:38] [Server thread/ERROR]: #!#! 
[12:53:38] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[12:53:38] [Server thread/ERROR]: #!#! Could not load a_2_Survival_Rules\disEnchant.sk
[12:53:38] [Server thread/ERROR]: #!#! 
[12:53:38] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[12:53:38] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:53:38] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[12:53:38] [Server thread/ERROR]: #!#! Here is full list of them:
[12:53:38] [Server thread/ERROR]: #!#! skRayFall (https://sk.rayfall.net/) skript-mirror (https://github.com/btk5h/skript-mirror) TuSKe (github.com/Tuke-Nuke/TuSKe) skDragon SkBee skript-yaml SkQuery MundoSK (https://forums.skunity.com/resources/mundosk.69/) skript-placeholders (https://github.com/APickledWalrus/skript-placeholders) SharpSK 
[12:53:38] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[12:53:38] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[12:53:38] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[12:53:38] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[12:53:38] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[12:53:38] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[12:53:38] [Server thread/ERROR]: #!#! 
[12:53:38] [Server thread/ERROR]: #!#! Stack trace:
[12:53:38] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Event may not be null in non-simple VariableStrings!
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:455)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getAll(VariableString.java:731)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getAll(VariableString.java:1)
[12:53:38] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBTApi.validateNBT(NBTApi.java:29)
[12:53:38] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprItemWithNBT.init(ExprItemWithNBT.java:44)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:502)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:840)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1569)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1526)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1006)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1093)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:48)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:153)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:665)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380)
[12:53:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:534)
[12:53:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[12:53:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[12:53:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1275)
[12:53:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:467)
[12:53:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1193)
[12:53:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:980)
[12:53:38] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[12:53:38] [Server thread/ERROR]: #!#! 
[12:53:38] [Server thread/ERROR]: #!#! Version Information:
[12:53:38] [Server thread/ERROR]: #!#!   Skript: 2.4.1
[12:53:38] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[12:53:38] [Server thread/ERROR]: #!#!     Date: 2019-12-22
[12:53:38] [Server thread/ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[12:53:38] [Server thread/ERROR]: #!#!   Minecraft: 1.15.2
[12:53:38] [Server thread/ERROR]: #!#!   Java: 1.8.0_241 (Java HotSpot(TM) 64-Bit Server VM 25.241-b07)
[12:53:38] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[12:53:38] [Server thread/ERROR]: #!#! 
[12:53:38] [Server thread/ERROR]: #!#! Server platform: Paper
[12:53:38] [Server thread/ERROR]: #!#! 
[12:53:38] [Server thread/ERROR]: #!#! Current node: give an enchanted book with nbt "{StoredEnchantments:[{lvl:%{_book::2}%s,id:""minecraft:%{_book::1}%""}]}" to {_p} (a_2_Survival_Rules\disEnchant.sk, line 96)
[12:53:38] [Server thread/ERROR]: #!#! Current item: null
[12:53:38] [Server thread/ERROR]: #!#! 
[12:53:38] [Server thread/ERROR]: #!#! Thread: Server thread
[12:53:38] [Server thread/ERROR]: #!#! 
[12:53:38] [Server thread/ERROR]: #!#! Language: english
[12:53:38] [Server thread/ERROR]: #!#! Link parse mode: STRICT
[12:53:38] [Server thread/ERROR]: #!#! 
[12:53:38] [Server thread/ERROR]: #!#! End of Error.
[12:53:38] [Server thread/ERROR]: #!#!
```
for more: https://pastebin.ubuntu.com/p/SNrs3wSnqZ/

**Version Info:**
 - **SkBee Version:** (ex: 1.0.0)SkBee-1.3.0 (I also tried 1.2.0)
-  **Skript Version:** (ex: Skript 2.5-alpha3)Skript 2.4.1
 - **Server Version/Platform** (ex: Spigot 1.15.2)Paper 1.15.2

**Comment by ShaneBeee** [comment]
Hmm... Im not entirely sure what is causing this, the last line in the error is:
```
java.lang.IllegalArgumentException: Event may not be null in non-simple VariableStrings!
```
Makes me think the variable is not set.

**Comment by rudde0** [comment]
Unfortunately same error is still appearing. :(

```
drop (1 of leather chestplate with nbt "{display:{color:15051050},customitemnbt:""Blood Moon Chestplate"",ReduceDamage:25}" named "&6Chestplate" with lore "a fancy chestplate") at player
```
There is no error too but this code have:
```
drop (1 of leather chestplate with nbt "{display:{color:15051050},OzelEsya:""Kanli_Ay_Zirhi"",HasarAzalt:%{_random}%}" named "&6Kanlı Ay Zırhı" with lore lore("&7Hasar Azaltır: &c%%%{_random}%", "", "&6Kabiliyet: Hayatta Kalan", "&7Giyiliyken her &bhayatta kalma &7saatiniz", "&7başına &c+1 kalp &7kazanırsınız. Bu etki", "&7beş defaya kadar birikebilir.", "", "&7Etkinin işlemesi için &6Kanlı Ay", "&6Zırhlarının &7tüm parçalarını", "&7giyiyor olmanız gerekir.", "", "&7Kıyafetlerin bozulmaması için &9Kanlı Ay", "&9Dikiş Kiti &7üreterek &6Kanlı Ay", "&6Kıyafetlerinizi &7onarabilirsiniz.", "", "&6&lEfsanevi")) at {_loc}
```
{_loc} presents coordinate of victim
{_random} is a random integer between 1 and 25
Error: https://pastebin.ubuntu.com/p/Cr9ZWtHNx4/

And you're right, there is no error in your code: http://prntscr.com/sc021r

is it causing from lore length or local variables maybe?

----

After some tests i realised i can't use variables in nbt strings
```
function myarmors(p: player):
	set {_random} to random integer between 1 and 25
	drop (1 of leather chestplate with nbt "{display:{color:15051050},OzelEsya:""Kanli_Ay_Zirhi"",HasarAzalt:%{_random}%}" named "&6Kanlı Ay Zırhı" with lore lore("&7Hasar Azaltır: &c%%%{_random}%", "", "&6Kabiliyet: Hayatta Kalan", "&7Giyiliyken her &bhayatta kalma &7saatiniz", "&7başına &c+1 kalp &7kazanırsınız. Bu etki", "&7beş defaya kadar birikebilir.", "", "&7Etkinin işlemesi için &6Kanlı Ay", "&6Zırhlarının &7tüm parçalarını", "&7giyiyor olmanız gerekir.", "", "&7Kıyafetlerin bozulmaması için &9Kanlı Ay", "&9Dikiş Kiti &7üreterek &6Kanlı Ay", "&6Kıyafetlerinizi &7onarabilirsiniz.", "", "&6&lEfsanevi")) at location of {_p}
```
not working but
```
function myarmors(p: player):
	set {_random} to random integer between 1 and 25
	drop (1 of leather chestplate with nbt "{display:{color:15051050},OzelEsya:""Kanli_Ay_Zirhi"",HasarAzalt:3}" named "&6Kanlı Ay Zırhı" with lore lore("&7Hasar Azaltır: &c%%%{_random}%", "", "&6Kabiliyet: Hayatta Kalan", "&7Giyiliyken her &bhayatta kalma &7saatiniz", "&7başına &c+1 kalp &7kazanırsınız. Bu etki", "&7beş defaya kadar birikebilir.", "", "&7Etkinin işlemesi için &6Kanlı Ay", "&6Zırhlarının &7tüm parçalarını", "&7giyiyor olmanız gerekir.", "", "&7Kıyafetlerin bozulmaması için &9Kanlı Ay", "&9Dikiş Kiti &7üreterek &6Kanlı Ay", "&6Kıyafetlerinizi &7onarabilirsiniz.", "", "&6&lEfsanevi")) at location of {_p}
```
thats working

**Comment by ShaneBeee** [comment]
try the latest update... it may have fixed some issues.

**Comment by rudde0** [comment]
I have already tried

**Comment by ShaneBeee** [comment]
Can you send the error produced by the latest version of SkBee.

**Comment by ShaneBeee** [comment]
Ok I found the issue, and I believe I solved it. I'll get a release out shortly.

**Comment by ShaneBeee** [comment]
This version should fix it:
https://github.com/ShaneBeee/SkBee/releases/tag/1.3.2

**Comment by rudde0** [comment]
yes its fixed thanks but there is one more thing
```
[02:32:45 ERROR]: [Skript] Tag ""HasarAzalt"" of the object nbt of the chestplate of the player is not a text (a_2_Survival_Rules\Survival.sk, line 69: add (tag "HasarAzalt" of nbt of player's chestplate) parsed as number to {_update}')
[02:32:45 ERROR]: [Skript] Tag ""HasarAzalt"" of the object nbt of the leggings of the player is not a text (a_2_Survival_Rules\Survival.sk, line 71: add (tag "HasarAzalt" of nbt of player's leggings) parsed as number to {_update}')
[02:32:45 ERROR]: [Skript] Tag ""HasarAzalt"" of the object nbt of the boots of the player is not a text (a_2_Survival_Rules\Survival.sk, line 74: add (tag "HasarAzalt" of nbt of player's boots) parsed as number to {_update}')
[02:32:45 ERROR]: [Skript] Tag ""HasarAzalt"" of the object nbt of the helmet of the player is not a text (a_2_Survival_Rules\Survival.sk, line 100: add (tag "HasarAzalt" of nbt of player's helmet) parsed as number to {_update}')
[02:32:45 ERROR]: [Skript] Tag ""HasarAzalt"" of the object nbt of the chestplate of the player is not a text (a_2_Survival_Rules\Survival.sk, line 103: add (tag "HasarAzalt" of nbt of player's chestplate) parsed as number to {_update}')
[02:32:45 ERROR]: [Skript] Tag ""HasarAzalt"" of the object nbt of the leggings of the player is not a text (a_2_Survival_Rules\Survival.sk, line 106: add (tag "HasarAzalt" of nbt of player's leggings) parsed as number to {_update}')
[02:32:45 ERROR]: [Skript] Tag ""HasarAzalt"" of the object nbt of the boots of the player is not a text (a_2_Survival_Rules\Survival.sk, line 110: add (tag "HasarAzalt" of nbt of player's boots) parsed as number to {_update}')
[02:32:47 ERROR]: [Skript] Tag ""PRValue"" of the object nbt of the tool of the player is not a text (a_2_Survival_Rules\Survival.sk, line 715: set {_value} to (tag "PRValue" of nbt of player's tool) parsed as number')
[02:32:47 ERROR]: [Skript] Tag ""PRValue"" of the object nbt of the tool of the player is not a text (a_2_Survival_Rules\Survival.sk, line 721: set {_value} to (tag "PRValue" of nbt of player's off tool) parsed as number')
```
can you do automatic text parse for variables? sknbeet has that feature I guess
