### ISSUE TITLE
[BUG] Cloning worlds broken due to session.lock [1.18.2]

### ISSUE THREAD

**Issue by ethanrettinger** [ShaneBeee/SkBee#184]
### **Describe the bug**
Attempting to clone a world (in 1.18.2, paperspigot) causes an error to be thrown to the console

### **To Reproduce**
1. Load a world
2. **Clone** the aforementioned world [NOT Copy!] (unloaded worlds ALSO throw an error in console rather than throwing a skript error!)
3. Ensure the loaded world has a `session.lock` file

### **Expected behavior**

1. Load the "PIT" world into memory
2. Clone the "PIT" world exactly as is with a different name
5. Teleport the player into the cloned world after loading it

### **Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.
_Console Error:_
![image](https://user-images.githubusercontent.com/79817320/174203939-2c3f19e6-810c-4b85-bd97-f047edb840c7.png)
_Source Code related to error:_
![image](https://user-images.githubusercontent.com/79817320/174204179-4e587180-6828-42be-96e3-d82d9b79ef80.png)

### **Version Info:**
 - **SkBee Version:** (ex: 1.0.0) `SkBee-1.16.0-But-With-Stats`
-  **Skript Version:** (ex: Skript 2.5-alpha3) `Skript 2.6.2`
 - **Server Version/Platform** (ex: Spigot 1.15.2) `PaperSpigot 1.18.2`

### **Additional context**
Probably not related, but I am using skript-reflect to asynchronously create the world on a new thread.
(Note: it is crucial that the server maintains its performance while a world is being created, since I expect hundreds of them to be created, all while players are online.) 
The world "PIT" was not created by other plugins and is not a default world (but it was also not generated by the SkBee plugin)

**Comment by ShaneBeee** [comment]
can you try do this without doing it async, my guess is that is the issue here.
From my understanding, this can't be done async

**Comment by ethanrettinger** [comment]
@ShaneBeee Doesn't seem like it. Error is identical
Source code:
![image](https://user-images.githubusercontent.com/79817320/174238008-b7cb2c37-f8e3-41e7-b59c-4a605171ccff.png)

Error:
```[02:23:29 WARN]: java.nio.file.FileSystemException: .\PIT\session.lock -> .\PRIVATE-4\session.lock: The process cannot access the file because another process has locked a portion of the file
[02:23:29 WARN]:        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[02:23:29 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[02:23:29 WARN]:        at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:209)
[02:23:29 WARN]:        at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:284)
[02:23:29 WARN]:        at java.base/java.nio.file.Files.copy(Files.java:1305)
[02:23:29 WARN]:        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:850)
[02:23:29 WARN]:        at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1312)
...```

**Comment by ShaneBeee** [comment]
I can't replicate, but I changed how the world folder copying is done
(rather than copying the whole directory, I copy each of the contents, but skip session.lock)
give this version a try and let me know if it works:
- Go to this link https://github.com/ShaneBeee/SkBee/actions/runs/2517667890
- Scroll to the bottom and download `SkBee-Artifact`
