### ISSUE TITLE
[BUG] On Anvil Prepare Event / Send Meesage 

### ISSUE THREAD

**Issue by HaciGandalf** [ShaneBeee/SkBee#185]
**Describe the bug**
Not sending message to player and giving this error.

**To Reproduce**
1. right click on the anvil
2. place items in slots

**Screenshots/Errors**
```
[11:02:15] [Server thread/ERROR]: #!#! 
[11:02:15] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[11:02:15] [Server thread/ERROR]: #!#! 
[11:02:15] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[11:02:15] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:02:15] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:02:15] [Server thread/ERROR]: #!#! Here is full list of them:
[11:02:15] [Server thread/ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect) skript-gui v1.3-beta1 (https://github.com/APickledWalrus/skript-gui) SkBee v1.16.0 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.4 Skacket v1.0.9 
[11:02:15] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[11:02:15] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:02:15] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:02:15] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:02:15] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:02:15] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[11:02:15] [Server thread/ERROR]: #!#! 
[11:02:15] [Server thread/ERROR]: #!#! Stack trace:
[11:02:15] [Server thread/ERROR]: #!#! java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[11:02:15] [Server thread/ERROR]: #!#!     at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[11:02:15] [Server thread/ERROR]: #!#!     at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[11:02:15] [Server thread/ERROR]: #!#!     at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[11:02:15] [Server thread/ERROR]: #!#!     at java.base/java.util.Objects.checkIndex(Objects.java:359)
[11:02:15] [Server thread/ERROR]: #!#!     at java.base/java.util.ArrayList.get(ArrayList.java:427)
[11:02:15] [Server thread/ERROR]: #!#!     at SkBee-1.16.0.jar//com.shanebeestudios.skbee.elements.other.events.OtherEvents$2.get(OtherEvents.java:55)
[11:02:15] [Server thread/ERROR]: #!#!     at SkBee-1.16.0.jar//com.shanebeestudios.skbee.elements.other.events.OtherEvents$2.get(OtherEvents.java:51)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:99)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:85)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:112)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:47)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:110)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[11:02:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[11:02:15] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[11:02:15] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:02:15] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[11:02:15] [Server thread/ERROR]: #!#!     at org.bukkit.event.Event.callEvent(Event.java:45)
[11:02:15] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1640)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.world.inventory.ContainerAnvil.a(ContainerAnvil.java:319)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:968)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInItemName.a(PacketPlayInItemName.java:24)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInItemName.a(PacketPlayInItemName.java:6)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[11:02:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[11:02:15] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[11:02:15] [Server thread/ERROR]: #!#! 
[11:02:15] [Server thread/ERROR]: #!#! Version Information:
[11:02:15] [Server thread/ERROR]: #!#!   Skript: 2.6.2 (latest)
[11:02:15] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[11:02:15] [Server thread/ERROR]: #!#!     Date: 19:12:53.596652600
[11:02:15] [Server thread/ERROR]: #!#!   Bukkit: 1.18-R0.1-SNAPSHOT
[11:02:15] [Server thread/ERROR]: #!#!   Minecraft: 1.18
[11:02:15] [Server thread/ERROR]: #!#!   Java: 17.0.2 (Java HotSpot(TM) 64-Bit Server VM 17.0.2+8-LTS-86)
[11:02:15] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[11:02:15] [Server thread/ERROR]: #!#! 
[11:02:15] [Server thread/ERROR]: #!#! Server platform: Paper
[11:02:15] [Server thread/ERROR]: #!#! 
[11:02:15] [Server thread/ERROR]: #!#! Current node: null
[11:02:15] [Server thread/ERROR]: #!#! Current item: send "[!] Özel eşyaların isimleri değiştirilemez." to the player
[11:02:15] [Server thread/ERROR]: #!#! Current trigger: anvil prepare (simple event) (esyalar.sk, line 106)
[11:02:15] [Server thread/ERROR]: #!#! 
[11:02:15] [Server thread/ERROR]: #!#! Thread: Server thread
[11:02:15] [Server thread/ERROR]: #!#! 
[11:02:15] [Server thread/ERROR]: #!#! Language: english
[11:02:15] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[11:02:15] [Server thread/ERROR]: #!#! 
[11:02:15] [Server thread/ERROR]: #!#! End of Error.
[11:02:15] [Server thread/ERROR]: #!#!
```

```
on anvil prepare:
    if tag "OzelEsya" of nbt of slot 0 of event-inventory is set:
        if event-slot is not air:
            if colored display name of slot 0 of event-inventory is not colored display name of event-slot:
                set repair cost of event-inventory to 10000000
                close player's inventory
                send "&8[&c&l!&8] &cÖzel eşyaların isimleri değiştirilemez." to player
```

**Version Info:**
 - **SkBee Version:** (1.16.0)
-  **Skript Version:** (Skript 2.6.2)
 - **Server Version/Platform** (Spigot 1.18.1)

**Comment by ShaneBeee** [comment]
fixed in SkBee 1.16.1
