### ISSUE TITLE
Error on loading 

### ISSUE THREAD

**Issue by Cilicou** [ShaneBeee/SkBee#189]
Script works without SkBee, seems related to a "fishingstate" ?
- Seems to be a conflict between SkBee and Skellet. If only one of the two is activated it works, but if both are it crashes. 
- Also seems like there's even more errors of this sort if I activate more than just NBT elements in the config.

```
[01:19:58 ERROR]: #!#! Stack trace:
[01:19:58 ERROR]: #!#! ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: [player] fish[ing] [state[s] [of] %-fishingstates%]]
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:54)
[01:19:58 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1037)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1008)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:740)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[01:19:58 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:19:58 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[01:19:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900)
[01:19:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:863)
[01:19:58 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:473)
[01:19:58 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[01:19:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1414)
[01:19:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1187)
[01:19:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[01:19:58 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[01:19:58 ERROR]: #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for fishingstate
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:77)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[01:19:58 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1037)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1008)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:740)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[01:19:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[01:19:58 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:19:58 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[01:19:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900)
[01:19:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:863)
[01:19:58 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:473)
[01:19:58 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[01:19:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1414)
[01:19:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1187)
[01:19:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[01:19:58 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[01:19:58 ERROR]: #!#!
[01:19:58 ERROR]: #!#! Version Information:
[01:19:58 ERROR]: #!#!   Skript: 2.6.2 (latest)
[01:19:58 ERROR]: #!#!     Flavor: skriptlang-github
[01:19:58 ERROR]: #!#!     Date: 19:12:53.596652600
[01:19:58 ERROR]: #!#!   Bukkit: 1.19-R0.1-SNAPSHOT
[01:19:58 ERROR]: #!#!   Minecraft: 1.19
[01:19:58 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[01:19:58 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[01:19:58 ERROR]: #!#!
[01:19:58 ERROR]: #!#! Server platform: Paper
[01:19:58 ERROR]: #!#!
[01:19:58 ERROR]: #!#! Current node: on any movement: (custom\tpa.sk, line 82)
[01:19:58 ERROR]: #!#! Current item: null
[01:19:58 ERROR]: #!#!
[01:19:58 ERROR]: #!#! Thread: Server thread
[01:19:58 ERROR]: #!#!
[01:19:58 ERROR]: #!#! Language: english
[01:19:58 ERROR]: #!#! Link parse mode: DISABLED
[01:19:58 ERROR]: #!#!
[01:19:58 ERROR]: #!#! End of Error.
[01:19:58 ERROR]: #!#!
```

**Comment by ShaneBeee** [comment]
Unfortunately there is nothing I can do there.
Skellett would be loaded after SkBee (plugins are loaded in alphabetical order unless they have dependencies), and since SkBee loads first, it takes priority. SkBee also has a check for this (long story short, only loads Fishing State if no other add-on has done so already) So this issue would actually be an issue with Skellett, you'll need to report it to them.
