### ISSUE TITLE
[BUG] SkBee breaks Reflect's Bossbar

### ISSUE THREAD

**Issue by L3v3lup** [ShaneBeee/SkBee#190]
**Describe the bug**
I've reported this same bug to TPGamesNL (creator of SkriptReflect), he told me to report this here, its caused be Skbee.
Creating a Bossbar using SkriptReflect doesnt work due an class of SkBee.
It is caused by this: [https://github.com/ShaneBeee/SkBee/blob/master/src/main/java/com/shanebeestudios/skbee/elements/bossbar/types/Types.java#L95](url)

**To Reproduce**
```
import:
  org.bukkit.Bukkit
  org.bukkit.boss.BarColor
  org.bukkit.boss.BarStyle

on join:
  set {JobBossbar.%player%} to Bukkit.createBossBar("", BarColor.PURPLE, BarStyle.SOLID)
```

**Screenshots/Errors**
```
[12:19:39 ERROR]: #!#! Stack trace:
[12:19:39 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.yggdrasil.Fields.size()" because "fields" is null
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:188)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.serialize(Classes.java:723)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:548)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:542)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.Variables.saveVariableChange(Variables.java:552)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:385)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:376)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Variable.set(Variable.java:467)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Variable.change(Variable.java:523)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[12:19:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[12:19:39 ERROR]: #!#!     at skript-db.jar//com.btk5h.skriptdb.skript.EffExecuteStatement.lambda$execute$4(EffExecuteStatement.java:139)
[12:19:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[12:19:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[12:19:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559)
[12:19:39 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[12:19:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[12:19:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1247)
[12:19:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[12:19:39 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[12:19:39 ERROR]: #!#!
[12:19:39 ERROR]: #!#! Version Information:
[12:19:39 ERROR]: #!#!   Skript: 2.6.2
[12:19:39 ERROR]: #!#!     Flavor: skriptlang-github
[12:19:39 ERROR]: #!#!     Date: 19:12:53.596652600
[12:19:39 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[12:19:39 ERROR]: #!#!   Minecraft: 1.18.2
[12:19:39 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[12:19:39 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[12:19:39 ERROR]: #!#!
[12:19:39 ERROR]: #!#! Server platform: Paper
[12:19:39 ERROR]: #!#!
[12:19:39 ERROR]: #!#! Current node: null
[12:19:39 ERROR]: #!#! Current item: set {JobBossbar} (as java.lang.Object) to org.bukkit.Bukkit.createBossBar(("", org.bukkit.boss.BarColor.PURPLE and org.bukkit.boss.BarStyle.SOLID)[class java.lang.Object])
[12:19:39 ERROR]: #!#! Current trigger: join (simple event) (Jobs.sk, line 19)
```

**Version Info:**
 - **SkBee Version:** 1.16.1
-  **Skript Version:** 2.6.2
 - **Server Version/Platform:** 1.18.2
 - **Addons:** SkBee, skRayFall, skript-db, skript-reflect, skript-yaml, SKUniversal, skUtilities

**Comment by ShaneBeee** [comment]
why not just use SkBee boss bars then?

**Comment by UsainSrht** [comment]
I built with the last commit you've done and it still doesn't work.

**Comment by ShaneBeee** [comment]
could you send the error please, cause I just tried it several times and had no issues.

**Comment by UsainSrht** [comment]
> could you send the error please, cause I just tried it several times and had no issues.

Sorry, my bad. I'm not kidding, few seconds before you replied I realized it was my error on code .d It's working.

**Comment by ShaneBeee** [comment]
re-opening this. I don't close issues til I've done a release
This way if someone has the same issue they can see its death with
