### ISSUE TITLE
[BUG] Long error (Particle)

### ISSUE THREAD

**Issue by ImNotStable** [ShaneBeee/SkBee#196]
**Describe the bug**

**To Reproduce**
Unsure I just believe it's an issue with Skbee and SkQuery, it disappears when I remove
`
script options:
  $ developer mode
`

**Expected behavior**
Every file creates this error

**Screenshots/Errors**
```
[18:04:28 ERROR]: #!#! [Skript] Severe Error:
[18:04:28 ERROR]: #!#! Could not load economy\gems.sk
[18:04:28 ERROR]: #!#!
[18:04:28 ERROR]: #!#! Something went horribly wrong with Skript.
[18:04:28 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:04:28 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[18:04:28 ERROR]: #!#! Here is full list of them:
[18:04:28 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) Diskuise v0.2-beta3 Skript-Advancements v1.3.1 TuSKe v2.1 (github.com/Tuke-Nuke/TuSKe) SkJade v1.4.1 (https://www.github.com/Ankoki-Dev/SkJade) Khoryl v1.0.6 SkMusic v2.0.0 SkBee v1.17.0-Beta1 (https://github.com/ShaneBeee/SkBee) Skacket v1.0.10 Skellett v2.0.6 (https://forums.skunity.com/resources/skellett.24/) SkQuery v4.1.6
[18:04:28 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[18:04:28 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[18:04:28 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[18:04:28 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[18:04:28 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[18:04:28 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[18:04:28 ERROR]: #!#!
[18:04:28 ERROR]: #!#! Stack trace:
[18:04:28 ERROR]: #!#! java.lang.RuntimeException: pattern compiling exception, element class: com.shanebeestudios.skbee.elements.other.effects.EffParticle
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:140)
[18:04:28 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:04:28 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:04:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[18:04:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:510)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:484)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1456)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[18:04:28 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[18:04:28 ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: (lerp|draw|make) %number% [of] %particle% [particle] [using %-itemtype/blockdata/dustoption/dusttransition/vibration%] %directions% %locations% [with offset %-vector%] [with extra %-number%] [(1¦with force)] [(for|to) %-players%]]
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:54)
[18:04:28 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:140)
[18:04:28 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:04:28 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:04:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[18:04:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:510)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:484)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1456)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[18:04:28 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[18:04:28 ERROR]: #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for particle
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[18:04:28 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[18:04:28 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:140)
[18:04:28 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:04:28 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:04:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[18:04:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:510)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:484)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1456)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[18:04:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[18:04:28 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[18:04:28 ERROR]: #!#!
[18:04:28 ERROR]: #!#! Version Information:
[18:04:28 ERROR]: #!#!   Skript: 2.6.2 (latest)
[18:04:28 ERROR]: #!#!     Flavor: skriptlang-github
[18:04:28 ERROR]: #!#!     Date: 19:12:53.596652600
[18:04:28 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[18:04:28 ERROR]: #!#!   Minecraft: 1.18.2
[18:04:28 ERROR]: #!#!   Java: 17.0.3.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.3.1+2-LTS-6)
[18:04:28 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[18:04:28 ERROR]: #!#!
[18:04:28 ERROR]: #!#! Server platform: Paper
[18:04:28 ERROR]: #!#!
[18:04:28 ERROR]: #!#! Current node: $ developer mode (economy\gems.sk, line 2)
[18:04:28 ERROR]: #!#! Current item: null
[18:04:28 ERROR]: #!#!
[18:04:28 ERROR]: #!#! Thread: Server thread
[18:04:28 ERROR]: #!#!
[18:04:28 ERROR]: #!#! Language: english
[18:04:28 ERROR]: #!#! Link parse mode: DISABLED
[18:04:28 ERROR]: #!#!
[18:04:28 ERROR]: #!#! End of Error.
[18:04:28 ERROR]: #!#!
```

**Version Info:**
 - **SkBee Version:** 1.17.0-Beta1
-  **Skript Version:** 2.6.2
 - **Server Version/Platform**  git-Paper-386 (MC: 1.18.2)

**Comment by ShaneBeee** [comment]
can you please send the output of the command `/skbee info`

**Comment by ImNotStable** [comment]
Which one is the latest version 1.17.0-Beta1 or 1.16.3

**Comment by ImNotStable** [comment]
My bad I'm used to that being a startup thing
[20:33:38 INFO]: --- [SkBee Loading Info] ---
[20:33:38 INFO]: - [NBTAPI] Found Spigot: v1_18_R2! Trying to find NMS support
[20:33:38 INFO]: - [NBTAPI] NMS support 'MC1_18_R2' loaded!
[20:33:38 INFO]: - [NBTAPI] Found Gson: class com.google.gson.Gson
[20:33:38 INFO]: - NBT Elements successfully loaded
[20:33:38 INFO]: - Recipe Elements successfully loaded
[20:33:38 INFO]: - Scoreboard Elements successfully loaded
[20:33:38 INFO]: - Team Elements disabled
[20:33:38 INFO]: - It appears another Skript addon may have registered Team syntax.
[20:33:38 INFO]: - To use SkBee Teams, please remove the addon which has registered Teams already.
[20:33:38 INFO]: - Bound Elements successfully loaded
[20:33:38 INFO]: - Text Component Elements successfully loaded
[20:33:38 INFO]: - Pathfinding Elements disabled via config
[20:33:38 INFO]: - Structure Elements disabled via config
[20:33:38 INFO]: - Other Elements successfully loaded
[20:33:38 INFO]: - Virtual Furnace Elements disabled via config
[20:33:38 INFO]: - World Creator Elements successfully loaded
[20:33:38 INFO]: - Game Event Elements successfully loaded
[20:33:38 INFO]: - BossBar Elements disabled
[20:33:38 INFO]: - It appears another Skript addon may have registered BossBar syntax.
[20:33:38 INFO]: - To use SkBee BossBars, please remove the addon which has registered BossBars already.
[20:33:38 INFO]: - Statistic Elements successfully loaded
[20:33:38 INFO]: - Villager Elements successfully loaded
[20:33:38 INFO]: - Advancement Elements successfully loaded
[20:33:38 INFO]: - You're running a beta version, no need to check for an update!
[20:33:38 INFO]:
[20:33:38 INFO]: --- [Server Info] ---
[20:33:38 INFO]: Server Version: git-Paper-386 (MC: 1.18.2)
[20:33:38 INFO]: Skript Version: 2.6.2
[20:33:38 INFO]: Skript Addons:
[20:33:38 INFO]: - skript-placeholders v1.5.2
[20:33:38 INFO]: - Skacket v1.0.10
[20:33:38 INFO]: - Skellett v2.0.6
[20:33:38 INFO]: - SkMusic v2.0.0
[20:33:38 INFO]: - Diskuise v0.2-beta3
[20:33:38 INFO]: - SkQuery v4.1.6
[20:33:38 INFO]: - SkJade v1.4.1
[20:33:38 INFO]: - Khoryl v1.0.6
[20:33:38 INFO]: - TuSKe v2.1
[20:33:38 INFO]: - Skript-Advancements v1.3.1
[20:33:38 INFO]: SkBee Version: 1.17.0-Beta1
[20:33:38 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by ShaneBeee** [comment]
Hmm, weird.
So I have downloaded most of the addons you have, and I can not replicate this.
It seems like to me that another addon is registering the Particle class info, under a name other than "particle", but im not sure which one.

All I can say right now is maybe try reloading/restarting your server a few times, removing addons 1 by 1, and find out which one is causing this issue, and let me know.

**Comment by ImNotStable** [comment]
try to create a file with 
```
script options:
    $ developer mode
```

**Comment by ShaneBeee** [comment]
I've done that and had no issues:
<img width="950" alt="Screen Shot 2022-07-01 at 2 17 35 PM" src="https://user-images.githubusercontent.com/20008482/176969018-133578bc-5382-46a5-a1a3-a96c7dc6b0f5.png">

At this point, I can't replicate the issue, nor do I know which addon its caused by, to try figure out what's going on.
