### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GeoGb1** [ShaneBeee/SkBee#202]
I tried to update to Skbee 1.17.0 and i got this erorr while starting the server.

```[11:26:10 ERROR]: #!#! 
[11:26:10 ERROR]: #!#! [Skript] Severe Error:
[11:26:10 ERROR]: #!#! SkBee's class com.shanebeestudios.skbee.elements.bossbar.types.Types generated an exception while loading
[11:26:10 ERROR]: #!#! 
[11:26:10 ERROR]: #!#! Something went horribly wrong with Skript.
[11:26:10 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:26:10 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:26:10 ERROR]: #!#! Following plugins are probably related to this error in some way:
[11:26:10 ERROR]: #!#! SkBee (https://github.com/ShaneBeee/SkBee) 
[11:26:10 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:26:10 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:26:10 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:26:10 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:26:10 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[11:26:10 ERROR]: #!#! 
[11:26:10 ERROR]: #!#! Stack trace:
[11:26:10 ERROR]: #!#! java.lang.IllegalArgumentException: Can't register org.bukkit.boss.BarColor with the code name bossbarcolor because that name is already used by boss bar color
[11:26:10 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.registerClass(Classes.java:90)
[11:26:10 ERROR]: #!#!     at SkBee-1.17.0.jar//com.shanebeestudios.skbee.elements.bossbar.types.Types.<clinit>(Types.java:137)
[11:26:10 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[11:26:10 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
[11:26:10 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:117)
[11:26:10 ERROR]: #!#!     at SkBee-1.17.0.jar//com.shanebeestudios.skbee.SkBee.loadBossBarElements(SkBee.java:362)
[11:26:10 ERROR]: #!#!     at SkBee-1.17.0.jar//com.shanebeestudios.skbee.SkBee.loadSkriptElements(SkBee.java:141)
[11:26:10 ERROR]: #!#!     at SkBee-1.17.0.jar//com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:76)
[11:26:10 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:26:10 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:26:10 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[11:26:10 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[11:26:10 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[11:26:10 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[11:26:10 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[11:26:10 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[11:26:10 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[11:26:10 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[11:26:10 ERROR]: #!#! 
[11:26:10 ERROR]: #!#! Version Information:
[11:26:10 ERROR]: #!#!   Skript: 2.6.2 (latest)
[11:26:10 ERROR]: #!#!     Flavor: skriptlang-github
[11:26:10 ERROR]: #!#!     Date: 19:12:53.596652600
[11:26:10 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[11:26:10 ERROR]: #!#!   Minecraft: 1.17.1
[11:26:10 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[11:26:10 ERROR]: #!#!   OS: Linux amd64 5.13.0-27-generic
[11:26:10 ERROR]: #!#! 
[11:26:10 ERROR]: #!#! Server platform: Paper
[11:26:10 ERROR]: #!#! 
[11:26:10 ERROR]: #!#! Current node: null
[11:26:10 ERROR]: #!#! Current item: null
[11:26:10 ERROR]: #!#! 
[11:26:10 ERROR]: #!#! Thread: Server thread
[11:26:10 ERROR]: #!#! 
[11:26:10 ERROR]: #!#! Language: english
[11:26:10 ERROR]: #!#! Link parse mode: DISABLED
[11:26:10 ERROR]: #!#! 
[11:26:10 ERROR]: #!#! End of Error.
[11:26:10 ERROR]: #!#! ```

**Comment by ShaneBeee** [comment]
I'm hoping this was fixed... if you could try this build:
(scroll down to the bottom and download the artifact)
https://github.com/ShaneBeee/SkBee/actions/runs/2617643652

Let me know if it works

**Comment by GeoGb1** [comment]
i will test this maybe tommorrow because i only have one server which is at its peak right now and i dont wanna lose players right now
those erorr appears only when the server starts, in rest, its fine

**Comment by ShaneBeee** [comment]
closing as im pretty sure it was fixed. If it wasn't please re-open this with more info
