### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by ImNotStable** [ShaneBeee/SkBee#203]
**Describe the bug**
Just loading the skript caused this

**To Reproduce**
```vb
command /sp:
	trigger:
		set {_n} to nbt compound from "{SuperPickaxe:3}"
		add {_n} to nbt compound of player's tool
		send pretty nbt of nbt compound of player's tool
		send {_n}
		
on break:
	send pretty nbt of nbt compound of player's tool
```

**Expected behavior**
The skript should work

**Screenshots/Errors**
```
[Tue 16:25:24 ERROR Minecraft] #!#! 
[Tue 16:25:24 ERROR Minecraft] #!#! [Skript] Severe Error:
[Tue 16:25:24 ERROR Minecraft] #!#! Could not load players/pickaxe.sk
[Tue 16:25:24 ERROR Minecraft] #!#! 
[Tue 16:25:24 ERROR Minecraft] #!#! Something went horribly wrong with Skript.
[Tue 16:25:24 ERROR Minecraft] #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[Tue 16:25:24 ERROR Minecraft] #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[Tue 16:25:24 ERROR Minecraft] #!#! Here is full list of them:
[Tue 16:25:24 ERROR Minecraft] #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) SkJade v1.4.2 (https://www.github.com/Ankoki-Dev/SkJade) SkBee v1.17.0 (https://github.com/ShaneBeee/SkBee) SkQuery v4.1.6 DiscordSRV v1.25.1 (https://github.com/DiscordSRV/DiscordSRV) 
[Tue 16:25:24 ERROR Minecraft] #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[Tue 16:25:24 ERROR Minecraft] #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[Tue 16:25:24 ERROR Minecraft] #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[Tue 16:25:24 ERROR Minecraft] #!#! In that case, you will be given instruction on how should you report it.
 
[Tue 16:25:24 ERROR Minecraft] #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[Tue 16:25:24 ERROR Minecraft] #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[Tue 16:25:24 ERROR Minecraft] #!#! 
[Tue 16:25:24 ERROR Minecraft] #!#! Stack trace:
[Tue 16:25:24 ERROR Minecraft] #!#! java.lang.IllegalStateException: zip file closed
[Tue 16:25:24 ERROR Minecraft] #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[Tue 16:25:24 ERROR Minecraft] #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[Tue 16:25:24 ERROR Minecraft] #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[Tue 16:25:24 ERROR Minecraft] #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[Tue 16:25:24 ERROR Minecraft] #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
[Tue 16:25:24 ERROR Minecraft] #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[Tue 16:25:24 ERROR Minecraft] #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[Tue 16:25:24 ERROR Minecraft] #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[Tue 16:25:24 ERROR Minecraft] #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[Tue 16:25:24 ERROR Minecraft] #!#!     at SkBee-1.17.0.jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.init(ExprNbtCompound.java:64)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:254)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:516)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:499)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[Tue 16:25:24 ERROR Minecraft] #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[Tue 16:25:24 ERROR Minecraft] #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[Tue 16:25:24 ERROR Minecraft] #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[Tue 16:25:24 ERROR Minecraft] #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2307)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2118)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[Tue 16:25:24 ERROR Minecraft] #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[Tue 16:25:24 ERROR Minecraft] #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[Tue 16:25:24 ERROR Minecraft] #!#! 
[Tue 16:25:24 ERROR Minecraft] #!#! Version Information:
[Tue 16:25:24 ERROR Minecraft] #!#!   Skript: 2.6.2
[Tue 16:25:24 ERROR Minecraft] #!#!     Flavor: skriptlang-github
[Tue 16:25:24 ERROR Minecraft] #!#!     Date: 19:12:53.596652600
[Tue 16:25:24 ERROR Minecraft] #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[Tue 16:25:24 ERROR Minecraft] #!#!   Minecraft: 1.18.2
[Tue 16:25:24 ERROR Minecraft] #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[Tue 16:25:24 ERROR Minecraft] #!#!   OS: Linux amd64 5.13.0-27-generic
[Tue 16:25:24 ERROR Minecraft] #!#! 
[Tue 16:25:24 ERROR Minecraft] #!#! Server platform: Paper
[Tue 16:25:24 ERROR Minecraft] #!#! 
[Tue 16:25:24 ERROR Minecraft] #!#! Current node: set {_n} to nbt compound from "{SuperPickaxe:3}" (players/pickaxe.sk, line 3)
[Tue 16:25:24 ERROR Minecraft] #!#! Current item: null
[Tue 16:25:24 ERROR Minecraft] #!#! 
[Tue 16:25:24 ERROR Minecraft] #!#! Thread: Server thread
[Tue 16:25:24 ERROR Minecraft] #!#! 
[Tue 16:25:24 ERROR Minecraft] #!#! Language: english
[Tue 16:25:24 ERROR Minecraft] #!#! Link parse mode: STRICT
[Tue 16:25:24 ERROR Minecraft] #!#! 
[Tue 16:25:24 ERROR Minecraft] #!#! End of Error.
[Tue 16:25:24 ERROR Minecraft] #!#! 
```

**Version Info:**
 - **SkBee Version:** 1.17.0
-  **Skript Version:** 2.6.2
 - **Server Version/Platform** git-Paper-372 (MC: 1.18.2)

Plugins (34): AdvancedBan, Chunky, Citizens, CoreProtect, DiscordSRV, EpicRename, Essentials, ExcellentCrates, FastAsyncWorldEdit (WorldEdit), GriefPrevention, GSit, HolographicDisplays, LuckPerms, mcMMO, Multiverse-Core, NexEngine, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, PWarp, SkBee, SkJade, SkQuery, Skript, skript-placeholders*, Stress, SuperVanish, TAB, TabTPS, UltimateStacker, Vault, ViaVersion, Vouchers, WorldGuard

(/skbee info doesn't work)

**Comment by ShaneBeee** [comment]
> (/skbee info doesn't work)

can you send a screenshot or copy/paste of the console when SkBee is loading. 
It looks to me like SkBee probably hasn't loaded properly

**Comment by ImNotStable** [comment]
I can't find the log I'm sorry for the inconvenience
