### ISSUE TITLE
[BUG] merchant recipes

### ISSUE THREAD

**Issue by GeoGb1** [ShaneBeee/SkBee#204]
**THE CODE:**
```
command /test:
	permission: op
	trigger:
		set {_m} to merchant named "yo"
		set {_r} to merchant recipe with result dirt with max uses 5
		set ingredients of merchant recipe {_r} to stone and glass
		add {_r} to merchant recipes of {_m}
		open merchant {_m} to player
```

**Errors*:*

```
[23:44:10] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.6.2
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.MerchantRecipe.<init>(org.bukkit.inventory.ItemStack, int, int, boolean, int, float, int, int)'
	at com.shanebeestudios.skbee.elements.villager.expressions.ExprMerchantRecipe.get(ExprMerchantRecipe.java:88) ~[SkBee-1.17.0.jar:?]
	at com.shanebeestudios.skbee.elements.villager.expressions.ExprMerchantRecipe.get(ExprMerchantRecipe.java:20) ~[SkBee-1.17.0.jar:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99) ~[Skript.jar:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:274) ~[Skript.jar:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript.jar:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:250) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255) ~[Skript.jar:?]
	at ch.njol.skript.command.Commands.handleCommand(Commands.java:260) ~[Skript.jar:?]
	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:177) ~[Skript.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-411]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2254) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:44:10] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'test' in plugin Skript v2.6.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void org.bukkit.inventory.MerchantRecipe.<init>(org.bukkit.inventory.ItemStack, int, int, boolean, int, float, int, int)'
	at com.shanebeestudios.skbee.elements.villager.expressions.ExprMerchantRecipe.get(ExprMerchantRecipe.java:88) ~[SkBee-1.17.0.jar:?]
	at com.shanebeestudios.skbee.elements.villager.expressions.ExprMerchantRecipe.get(ExprMerchantRecipe.java:20) ~[SkBee-1.17.0.jar:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99) ~[Skript.jar:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:274) ~[Skript.jar:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript.jar:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:250) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:194) ~[Skript.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-411]
	... 21 more
```

**Version Info:**
 - **SkBee Version:** (1.17.0)
 - **Skript Version:** (2.6.2)
 - **Server Version/Platform** (1.17.1 PAPER)

**Comment by ShaneBeee** [comment]
It appears the constructor I was using for this, wasn't added til MC 1.18.x
I will fix the error soon

**Comment by ShaneBeee** [comment]
no, I haven't released anything yet
