### ISSUE TITLE
[BUG] dustOption(rgb()) function causing internal issue

### ISSUE THREAD

**Issue by HenryFyt** [ShaneBeee/SkBee#222]
**Describe the bug:**
Variables inside of rgb() function causing internal issues.

**To Reproduce:**

set {_R} to 255
set {_G} to 0
set {_B} to 255

set {_c} to dustOption(rgb({_R}, {_G}, {_B}), 1)   #- What's causing the internal issue

**Expected behavior:**
{_c} is a purple dust particle 

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/36750152/181103320-f26437c1-d0e1-4a12-9bec-cb44e1282a19.png)

**Version Info:**
 - SkBee: 1.17.3
 - Skript: 2.6.2
 - Paper 1.17.1

**Additional context**
Code to reproduce: 
[skbeebug.txt](https://github.com/ShaneBeee/SkBee/files/9193093/skbeebug.txt)

**Comment by ShaneBeee** [comment]
what is the error?

I tried the code:
```vb
on load:
	set {_R} to 255
	set {_G} to 0
	set {_B} to 255

	set {_c} to dustOption(rgb({_R}, {_G}, {_B}), 1)
	send "C: %{_c}%"
```
Output:
```
> sk reload test
[13:39:02 INFO]: [Skript] Reloading test.sk...
[13:39:02 INFO]: C: org.bukkit.Particle$DustOptions@56cdd49
[13:39:02 INFO]: [Skript] Successfully reloaded test.sk. (5ms)
```

Seems to work fine for me.

**Comment by HenryFyt** [comment]
Sorry, forgot to include that.

[00:32:53 INFO]: AmazingTank issued server command: /fuckyourmom
[00:32:53 INFO]: rgb(255, 4.25, 0)
[00:32:53 INFO]: 255
[00:32:53 INFO]: 4.25
[00:32:53 INFO]: 0
[00:32:53 ERROR]: #!#! 
[00:32:53 ERROR]: #!#! [Skript] Severe Error:
[00:32:53 ERROR]: #!#! 
[00:32:53 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[00:32:53 ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[00:32:53 ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[00:32:53 ERROR]: #!#! 
[00:32:53 ERROR]: #!#! Stack trace:
[00:32:53 ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[00:32:53 ERROR]: #!#!     at SkBee-1.17.3.jar//com.shanebeestudios.skbee.elements.other.type.Types$2.execute(Types.java:138)
[00:32:53 ERROR]: #!#!     at SkBee-1.17.3.jar//com.shanebeestudios.skbee.elements.other.type.Types$2.execute(Types.java:134)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:288)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:43)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:250)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:260)
[00:32:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:177)
[00:32:53 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[00:32:53 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:32:53 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:32:53 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[00:32:53 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2254)
[00:32:53 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2073)
[00:32:53 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[00:32:53 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[00:32:53 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[00:32:53 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[00:32:53 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:32:53 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[00:32:53 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[00:32:53 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[00:32:53 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[00:32:53 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[00:32:53 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[00:32:53 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[00:32:53 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[00:32:53 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1536)
[00:32:53 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[00:32:53 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[00:32:53 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[00:32:53 ERROR]: #!#! 
[00:32:53 ERROR]: #!#! Version Information:
[00:32:53 ERROR]: #!#!   Skript: 2.6.2 (OUTDATED)
[00:32:53 ERROR]: #!#!     Flavor: skriptlang-github
[00:32:53 ERROR]: #!#!     Date: 19:12:53.596652600
[00:32:53 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[00:32:53 ERROR]: #!#!   Minecraft: 1.17.1
[00:32:53 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[00:32:53 ERROR]: #!#!   OS: Linux amd64 5.13.0-27-generic
[00:32:53 ERROR]: #!#! 
[00:32:53 ERROR]: #!#! Server platform: Paper
[00:32:53 ERROR]: #!#! 
[00:32:53 ERROR]: #!#! Current node: null
[00:32:53 ERROR]: #!#! Current item: set {_dust} (as java.lang.Object) to dustOption(rgb({_R} (as java.lang.Long), {_G} (as java.lang.Long), {_B} (as java.lang.Long)), [[long:1]])
[00:32:53 ERROR]: #!#! Current trigger: command /fuckyourmom (simple event) (vector.sk, line 117)
[00:32:53 ERROR]: #!#! 
[00:32:53 ERROR]: #!#! Thread: Server thread
[00:32:53 ERROR]: #!#! 
[00:32:53 ERROR]: #!#! Language: english
[00:32:53 ERROR]: #!#! Link parse mode: DISABLED
[00:32:53 ERROR]: #!#! 
[00:32:53 ERROR]: #!#! End of Error.
[00:32:53 ERROR]: #!#! 

Did you try using the exact code I used? Not sure 🤷

**Comment by ShaneBeee** [comment]
I did a bunch of testing, and so far the only way I can get that error, is if one of the vars isn't set
I will try to surprise the error, but im not sure if I can do that in a function

**Comment by HenryFyt** [comment]
Yeah, but you can see the debugging messages in the picture 
![image](https://user-images.githubusercontent.com/36750152/181167554-4d13a28b-d564-4718-9959-742455943c42.png)
that all the values are set, so why wouldn't this be working properly?

**Comment by ShaneBeee** [comment]
Maybe it has something to do with that 4.25, since its taking in an int if im not mistaken

**Comment by HenryFyt** [comment]
Oh, so the rgb function used integers as opposed to numbers? Interesting.

**Comment by ShaneBeee** [comment]
> Oh, so the rgb function used integers as opposed to numbers? Interesting.

yes, this is stated in Skript's docs (it says "long", not sure why, same thing)
