### ISSUE TITLE
[BUG] Error for tabbing in console

### ISSUE THREAD

**Issue by ImNotStable** [ShaneBeee/SkBee#234]
**Describe the bug**
Large error in console when using the tab button to see all available commands (make sure you have a clear line, doesn't work with the start of a command)

**To Reproduce**
open your .bat console and just click tab everything works properly there's just a large error

**Expected behavior**
No error

**Screenshots/Errors**
[21:53:17 ERROR]: Could not pass event TabCompleteEvent to Skript v2.6.3
java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
        at jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
        at jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
        at jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.lang.String.checkIndex(String.java:4557) ~[?:?]
        at java.lang.StringLatin1.charAt(StringLatin1.java:46) ~[?:?]
        at java.lang.String.charAt(String.java:1515) ~[?:?]
        at com.shanebeestudios.skbee.elements.other.events.TabEvent.check(TabEvent.java:69) ~[SkBee-2.0.0.jar:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:136) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71) ~[Skript.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-387]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.command.ConsoleCommandCompleter$2.evaluate(ConsoleCommandCompleter.java:96) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.command.ConsoleCommandCompleter$2.evaluate(ConsoleCommandCompleter.java:90) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.util.Waitable.run(Waitable.java:24) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1545) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Version Info:**
 - **SkBee Version:** 2.0.0
 - **Skript Version:** 2.6.3
 - **Server Version/Platform** git-Paper-387 (MC: 1.18.2)

**Additional context**
Only Plugins are SkQuery, Skript, and Skbee

**Comment by ShaneBeee** [comment]
im curious why this was closed?
