### ISSUE TITLE
[BUG] Bound problem 

### ISSUE THREAD

**Issue by jurajplayercze** [ShaneBeee/SkBee#259]
**Describe the bug**
When i have enabled two scripts using bound check, but it throwing error in console.
Cheese on discord said _Unhanled NPE_. So please, take a look at it

**To Reproduce**
Two different scripts using border check, for example damage of player

**Screenshots/Errors**

**Version Info:**
 - Provide output of **/skbee info**   
 **OR**
 - **SkBee Version:** (ex: 2.3.1)
 - **Skript Version:** (ex: Skript 2.6.3)
 - **Server Version/Platform** (ex: Spigot 1.18.2)

**Additional context**
My code from hockey script (var_prefix option is different from second script)
Also i already checked if it will throw error without the function, and yes, it throw error without function

`on damage of player:
    if (location of victim) is within bound with id "{@var_prefix}":
        cancel event
        if attacker is a magma cube:#collide with puck
            JPEventHockeyHold(victim,attacker)
        else if attacker is a player:#player attacks player
            push victim (vector from attacker to victim) with speed {@push_power}
            delete (metadata tag "{@var_prefix}.held" of victim)
            if block under (metadata tag "{@var_prefix}.puck" of victim) is not ice:
                teleport (metadata tag "{@var_prefix}.puck" of {_p}) to victim`

second code is from hotpotato script
`on damage of player:
    if (location of victim) is within bound with id "{@var_prefix}":
        cancel event
        if {{@var_prefix}::remove::bomb} is attacker:
            JPEventHotpotatoBomb(attacker,victim,"pass")`

**Comment by ShaneBeee** [comment]
so what's the error?

**Comment by jurajplayercze** [comment]
``> so what's the error?

That's really stupid from me. Sorry for that.
```
[12:22:01 ERROR]: #!#! 
[12:22:01 ERROR]: #!#! [Skript] Severe Error:
[12:22:01 ERROR]: #!#! 
[12:22:01 ERROR]: #!#! Something went horribly wrong with Skript.
[12:22:01 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:22:01 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[12:22:01 ERROR]: #!#! Here is full list of them:
[12:22:01 ERROR]: #!#! SkBee v2.3.1 (https://github.com/ShaneBeee/SkBee) 
[12:22:01 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[12:22:01 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[12:22:01 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[12:22:01 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[12:22:01 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[12:22:01 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[12:22:01 ERROR]: #!#! 
[12:22:01 ERROR]: #!#! Stack trace:
[12:22:01 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "com.shanebeestudios.skbee.elements.bound.objects.Bound.isInRegion(org.bukkit.Location)" because the return value of "ch.njol.skript.lang.Expression.getSingle(org.bukkit.event.Event)" is null
[12:22:01 ERROR]: #!#!     at SkBee-2.3.1.jar//com.shanebeestudios.skbee.elements.bound.conditions.CondBoundContainsLocation.lambda$check$0(CondBoundContainsLocation.java:45)
[12:22:01 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:170)
[12:22:01 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:158)
[12:22:01 ERROR]: #!#!     at SkBee-2.3.1.jar//com.shanebeestudios.skbee.elements.bound.conditions.CondBoundContainsLocation.check(CondBoundContainsLocation.java:45)
[12:22:01 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.walk(SecConditional.java:165)
[12:22:01 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[12:22:01 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[12:22:01 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[12:22:01 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[12:22:01 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[12:22:01 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:22:01 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:22:01 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[12:22:01 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:248)
[12:22:01 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1151)
[12:22:01 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1010)
[12:22:01 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:964)
[12:22:01 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1185)
[12:22:01 ERROR]: #!#!     at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2065)
[12:22:01 ERROR]: #!#!     at net.minecraft.world.entity.player.EntityHuman.damageEntity0(EntityHuman.java:1031)
[12:22:01 ERROR]: #!#!     at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1346)
[12:22:01 ERROR]: #!#!     at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:938)
[12:22:01 ERROR]: #!#!     at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1027)
[12:22:01 ERROR]: #!#!     at net.minecraft.world.entity.monster.EntitySlime.j(EntitySlime.java:286)
[12:22:01 ERROR]: #!#!     at net.minecraft.world.entity.monster.EntitySlime.b(EntitySlime.java:277)
[12:22:01 ERROR]: #!#!     at net.minecraft.world.entity.player.EntityHuman.c(EntityHuman.java:621)
[12:22:01 ERROR]: #!#!     at net.minecraft.world.entity.player.EntityHuman.w_(EntityHuman.java:587)
[12:22:01 ERROR]: #!#!     at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2917)
[12:22:01 ERROR]: #!#!     at net.minecraft.world.entity.player.EntityHuman.k(EntityHuman.java:269)
[12:22:01 ERROR]: #!#!     at net.minecraft.server.level.EntityPlayer.l(EntityPlayer.java:667)
[12:22:01 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.c(PlayerConnection.java:314)
[12:22:01 ERROR]: #!#!     at net.minecraft.network.NetworkManager.a(NetworkManager.java:567)
[12:22:01 ERROR]: #!#!     at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
[12:22:01 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1620)
[12:22:01 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[12:22:01 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1455)
[12:22:01 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)
[12:22:01 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[12:22:01 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[12:22:01 ERROR]: #!#! 
[12:22:01 ERROR]: #!#! Version Information:
[12:22:01 ERROR]: #!#!   Skript: 2.6.3 (latest)
[12:22:01 ERROR]: #!#!     Flavor: skriptlang-github
[12:22:01 ERROR]: #!#!     Date: 00:55:22.847925631
[12:22:01 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[12:22:01 ERROR]: #!#!   Minecraft: 1.18.2
[12:22:01 ERROR]: #!#!   Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
[12:22:01 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[12:22:01 ERROR]: #!#! 
[12:22:01 ERROR]: #!#! Server platform: Paper
[12:22:01 ERROR]: #!#! 
[12:22:01 ERROR]: #!#! Current node: null
[12:22:01 ERROR]: #!#! Current item: if the location is in the bound bound from id "jp.script.event.hotpotato"
[12:22:01 ERROR]: #!#! Current trigger: damage of player (damage of [[entitydata:player]]) (hotpotato2.sk, line 100)
[12:22:01 ERROR]: #!#! 
[12:22:01 ERROR]: #!#! Thread: Server thread
[12:22:01 ERROR]: #!#! 
[12:22:01 ERROR]: #!#! Language: english
[12:22:01 ERROR]: #!#! Link parse mode: DISABLED
[12:22:01 ERROR]: #!#! 
[12:22:01 ERROR]: #!#! End of Error.
[12:22:01 ERROR]: #!#! 
```
