### ISSUE TITLE
[BUG] Mini Message

### ISSUE THREAD

**Issue by TravelerHere** [ShaneBeee/SkBee#265]
**Describe the bug**
- Everytime I try to send a mini message to me, it won't work
**To Reproduce**
Please include clear steps to reproduce the behavior
```vb
command u:
	trigger:
		set {_a} to -1
		loop 100 times:
			set {_m::1} to mini message from "THIS IS A TEST "
			set {_m::2} to mini message from "<gradient:red:yellow:%{_a}%> WITH A GRADIENT "
			set {_m} to merge components {_m::*}
			add 0.1 to {_a}
			if {_a} > 1:
				set {_a} to -1
			send action component {_m} to player
			wait 1 ticks
		send action bar "" to player
```
**Expected behavior**
Cool Gradient Action Bar
**Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.
```
[08:22:55 ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.6.3
java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/MiniMessage
	at com.shanebeestudios.skbee.api.text.BeeComponent.fromMiniMessage(BeeComponent.java:67) ~[SkBee-2.4.0-Adventure-Beta.jar:?]
	at com.shanebeestudios.skbee.elements.text.expressions.ExprMiniMessage.get(ExprMiniMessage.java:49) ~[SkBee-2.4.0-Adventure-Beta.jar:?]
	at com.shanebeestudios.skbee.elements.text.expressions.ExprMiniMessage.get(ExprMiniMessage.java:19) ~[SkBee-2.4.0-Adventure-Beta.jar:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99) ~[Skript.jar:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:274) ~[Skript.jar:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript.jar:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:251) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:256) ~[Skript.jar:?]
	at ch.njol.skript.command.Commands.handleCommand(Commands.java:261) ~[Skript.jar:?]
	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:178) ~[Skript.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-411]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2254) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.minimessage.MiniMessage
	... 37 more
[08:22:55 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'u' in plugin Skript v2.6.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/MiniMessage
	at com.shanebeestudios.skbee.api.text.BeeComponent.fromMiniMessage(BeeComponent.java:67) ~[SkBee-2.4.0-Adventure-Beta.jar:?]
	at com.shanebeestudios.skbee.elements.text.expressions.ExprMiniMessage.get(ExprMiniMessage.java:49) ~[SkBee-2.4.0-Adventure-Beta.jar:?]
	at com.shanebeestudios.skbee.elements.text.expressions.ExprMiniMessage.get(ExprMiniMessage.java:19) ~[SkBee-2.4.0-Adventure-Beta.jar:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99) ~[Skript.jar:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:274) ~[Skript.jar:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript.jar:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:251) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:256) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:195) ~[Skript.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-411]
	... 21 more
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.minimessage.MiniMessage
	at com.shanebeestudios.skbee.api.text.BeeComponent.fromMiniMessage(BeeComponent.java:67) ~[SkBee-2.4.0-Adventure-Beta.jar:?]
	at com.shanebeestudios.skbee.elements.text.expressions.ExprMiniMessage.get(ExprMiniMessage.java:49) ~[SkBee-2.4.0-Adventure-Beta.jar:?]
	at com.shanebeestudios.skbee.elements.text.expressions.ExprMiniMessage.get(ExprMiniMessage.java:19) ~[SkBee-2.4.0-Adventure-Beta.jar:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99) ~[Skript.jar:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:274) ~[Skript.jar:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript.jar:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:251) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:256) ~[Skript.jar:?]
	at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:195) ~[Skript.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-411]
	... 21 more
```
**Version Info:**
 - Provide output of **/skbee info**   
 **OR**
 - **SkBee Version:** (ex: 1.16.1)
 - **Skript Version:** (ex: Skript 2.6.1)
 - **Server Version/Platform** (ex: Spigot 1.15.2)
![image](https://user-images.githubusercontent.com/104726372/192088346-956a98f1-6c0a-4740-abc1-ef8841e53d21.png)

**Additional context**

**Comment by TravelerHere** [comment]
My bad about the error part

**Comment by ShaneBeee** [comment]
oh, it appears MiniMessage isn't on 1.17.x

**Comment by ShaneBeee** [comment]
I fixed, and re-uploaded the jar:
https://github.com/ShaneBeee/SkBee/releases/tag/2.4.0-Adventure-Beta

Give it a whirl at let me know if the big error is gone.
