### ISSUE TITLE
[BUG] huge console error and events stop working

### ISSUE THREAD

**Issue by Evanbeer** [ShaneBeee/SkBee#270]
**Describe the bug**
A lot of errors in the console and simple things as on right click stopped working
**To Reproduce**
Please include clear steps to reproduce the behavior
Using this event i think https://skripthub.net/docs/?id=919
**Expected behavior**
To check if someone is a owner of a region and then open  a gui
**Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.
[10:37:39 ERROR]: #!#! 
[10:37:39 ERROR]: #!#! [Skript] Severe Error:
[10:37:39 ERROR]: #!#! Could not load Jail.sk
[10:37:39 ERROR]: #!#! 
[10:37:39 ERROR]: #!#! Something went horribly wrong with Skript.
[10:37:39 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[10:37:39 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[10:37:39 ERROR]: #!#! Here is full list of them:
[10:37:39 ERROR]: #!#! SkBee v2.3.3 (https://github.com/ShaneBeee/SkBee) 
[10:37:39 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[10:37:39 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[10:37:39 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[10:37:39 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[10:37:39 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[10:37:39 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[10:37:39 ERROR]: #!#! 
[10:37:39 ERROR]: #!#! Stack trace:
[10:37:39 ERROR]: #!#! java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
[10:37:39 ERROR]: #!#!     at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
[10:37:39 ERROR]: #!#!     at java.base/java.lang.String.substring(String.java:2704)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.VariableString.unquote(VariableString.java:177)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.hooks.regions.classes.Region$2.parse(Region.java:77)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.hooks.regions.classes.Region$2.parse(Region.java:56)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.registrations.Classes.parseSimple(Classes.java:444)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.registrations.Classes.parse(Classes.java:473)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:584)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.ParseTagPatternElement.match(ParseTagPatternElement.java:79)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:344)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:627)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:255)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:131)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:520)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:522)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.loadCode(Section.java:90)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.init(Section.java:69)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.loadCode(Section.java:90)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.init(Section.java:69)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[10:37:39 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:149)
[10:37:39 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:37:39 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[10:37:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[10:37:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:59)
[10:37:39 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[10:37:39 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:306)
[10:37:39 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:290)
[10:37:39 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2295)
[10:37:39 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2249)
[10:37:39 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[10:37:39 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[10:37:39 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[10:37:39 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[10:37:39 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[10:37:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[10:37:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[10:37:39 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[10:37:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[10:37:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[10:37:39 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[10:37:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[10:37:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1195)
[10:37:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[10:37:39 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[10:37:39 ERROR]: #!#! 
[10:37:39 ERROR]: #!#! Version Information:
[10:37:39 ERROR]: #!#!   Skript: 2.6.3 (latest)
[10:37:39 ERROR]: #!#!     Flavor: skriptlang-github
[10:37:39 ERROR]: #!#!     Date: 00:55:22.847925631
[10:37:39 ERROR]: #!#!   Bukkit: 1.19.1-R0.1-SNAPSHOT
[10:37:39 ERROR]: #!#!   Minecraft: 1.19.1
[10:37:39 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[10:37:39 ERROR]: #!#!   OS: Linux amd64 5.15.0-46-generic
[10:37:39 ERROR]: #!#! 
[10:37:39 ERROR]: #!#! Server platform: Paper
[10:37:39 ERROR]: #!#! 
[10:37:39 ERROR]: #!#! Current node: set metadata tag "cell" of player to chest inventory with 3 rows named "&6%owners of "%region at event-block%"%'s cell" (Jail.sk, line 7)
[10:37:39 ERROR]: #!#! Current item: null
[10:37:39 ERROR]: #!#! 
[10:37:39 ERROR]: #!#! Thread: Server thread
[10:37:39 ERROR]: #!#! 
[10:37:39 ERROR]: #!#! Language: english
[10:37:39 ERROR]: #!#! Link parse mode: DISABLED
[10:37:39 ERROR]: #!#! 
[10:37:39 ERROR]: #!#! End of Error.
[10:37:39 ERROR]: #!#! 
**Version Info:**
 - Provide output of **/skbee info**   
 **OR**
 - **SkBee Version:** (ex: 1.16.1)
 - **Skript Version:** (ex: Skript 2.6.1)
 - **Server Version/Platform** (ex: Spigot 1.15.2)

![image](https://user-images.githubusercontent.com/60839540/194536028-91afc280-4fe3-4d76-ae77-55b5395fa45f.png)

**Additional context**

none

**Comment by Evanbeer** [comment]
Error is still there when i remove skbee, I have no idea what to do
