### ISSUE TITLE
[Bug] Error loading text components

### ISSUE THREAD

**Issue by YodaZen** [ShaneBeee/SkBee#272]
```
[00:27:49 ERROR]: #!#! 
[00:27:49 ERROR]: #!#! [Skript] Severe Error:
[00:27:49 ERROR]: #!#! SkBee's class com.shanebeestudios.skbee.elements.text.type.Types generated an exception while loading
[00:27:49 ERROR]: #!#! 
[00:27:49 ERROR]: #!#! Something went horribly wrong with Skript.
[00:27:49 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:27:49 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:27:49 ERROR]: #!#! Following plugins are probably related to this error in some way:
[00:27:49 ERROR]: #!#! SkBee (https://github.com/ShaneBeee/SkBee) 
[00:27:49 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:27:49 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:27:49 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:27:49 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:27:49 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:27:49 ERROR]: #!#! 
[00:27:49 ERROR]: #!#! Stack trace:
[00:27:49 ERROR]: #!#! java.lang.IllegalArgumentException: Can't register com.shanebeestudios.skbee.api.text.BeeComponent with the code name textcomponent because that name is already used by text component
[00:27:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.registerClass(Classes.java:91)
[00:27:49 ERROR]: #!#!     at SkBee-2.4.0.jar//com.shanebeestudios.skbee.elements.text.type.Types.<clinit>(Types.java:17)
[00:27:49 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[00:27:49 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
[00:27:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:117)
[00:27:49 ERROR]: #!#!     at SkBee-2.4.0.jar//com.shanebeestudios.skbee.SkBee.loadTextElements(SkBee.java:270)
[00:27:49 ERROR]: #!#!     at SkBee-2.4.0.jar//com.shanebeestudios.skbee.SkBee.loadSkriptElements(SkBee.java:134)
[00:27:49 ERROR]: #!#!     at SkBee-2.4.0.jar//com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:77)
[00:27:49 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:27:49 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[00:27:49 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[00:27:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[00:27:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[00:27:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[00:27:49 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[00:27:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[00:27:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[00:27:49 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[00:27:49 ERROR]: #!#! 
[00:27:49 ERROR]: #!#! Version Information:
[00:27:49 ERROR]: #!#!   Skript: 2.6.3 (latest)
[00:27:49 ERROR]: #!#!     Flavor: skriptlang-github
[00:27:49 ERROR]: #!#!     Date: 00:55:22.847925631
[00:27:49 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[00:27:49 ERROR]: #!#!   Minecraft: 1.17.1
[00:27:49 ERROR]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8-86)
[00:27:49 ERROR]: #!#!   OS: Linux amd64 5.4.0-91-generic
[00:27:49 ERROR]: #!#! 
[00:27:49 ERROR]: #!#! Server platform: Paper
[00:27:49 ERROR]: #!#! 
[00:27:49 ERROR]: #!#! Current node: null
[00:27:49 ERROR]: #!#! Current item: null
[00:27:49 ERROR]: #!#! 
[00:27:49 ERROR]: #!#! Thread: Server thread
[00:27:49 ERROR]: #!#! 
[00:27:49 ERROR]: #!#! Language: english
[00:27:49 ERROR]: #!#! Link parse mode: DISABLED
[00:27:49 ERROR]: #!#! 
[00:27:49 ERROR]: #!#! End of Error.
[00:27:49 ERROR]: #!#! 
```

Just updated to the newst version, don't know if i have done something wrong with skript that causes this.

**Comment by YodaZen** [comment]
Found the problem: (Why can't i do this tho?)

set {_Location} to player's location
while {JobCenterRequest.%uuid of player%} is true:
	if distance between {_Location} and player's location is greater than 5:
		delete {JobCenterRequest.%uuid of player%}
		message "&eJob Center &7>> &fPå gensyn!" to player
		stop

**Comment by ShaneBeee** [comment]
`java.lang.IllegalArgumentException: Can't register com.shanebeestudios.skbee.api.text.BeeComponent with the code name textcomponent because that name is already used by text component`
This means that another addon has registered "text component" already.
I'll have to add a check for that before attempting to register

**Comment by YodaZen** [comment]
> 

So it's something you have to implement before it works?

**Comment by ShaneBeee** [comment]
> So it's something you have to implement before it works?

no, its just a conflict with another addon.
I have to add a check before registering the type, and see if another addon is registering the same one

**Comment by ShaneBeee** [comment]
can you send the FULL output of `/skbee info`

**Comment by YodaZen** [comment]
> can you send the FULL output of `/skbee info`

`[11:55:11 INFO]: --- [SkBee Loading Info] ---
[11:55:11 INFO]: - [NBTAPI] Found Spigot: v1_17_R1! Trying to find NMS support
[11:55:11 INFO]: - [NBTAPI] NMS support 'MC1_17_R1' loaded!
[11:55:11 INFO]: - NBT Elements successfully loaded
[11:55:11 INFO]: - Recipe Elements successfully loaded
[11:55:11 INFO]: - Scoreboard Elements successfully loaded
[11:55:11 INFO]: - Team Elements disabled
[11:55:11 INFO]: - It appears another Skript addon may have registered Team syntax.
[11:55:11 INFO]: - To use SkBee Teams, please remove the addon which has registered Teams already.
[11:55:11 INFO]: - Bound Elements successfully loaded
[11:55:11 INFO]: - Text Component Elements successfully loaded
[11:55:11 INFO]: - Pathfinding Elements successfully loaded
[11:55:11 INFO]: - Structure Elements successfully loaded
[11:55:11 INFO]: - It looks like another addon registered 'fishingstate' already.
[11:55:11 INFO]: - You may have to use their fishing states in SkBee's 'Fish Event State' expression.
[11:55:11 INFO]: - Other Elements successfully loaded
[11:55:11 INFO]: - Virtual Furnace Elements disabled via config
[11:55:11 INFO]: - World Creator Elements successfully loaded
[11:55:11 INFO]: - Game Event Elements successfully loaded
[11:55:11 INFO]: - BossBar Elements disabled
[11:55:11 INFO]: - It appears another Skript addon may have registered BossBar syntax.
[11:55:11 INFO]: - To use SkBee BossBars, please remove the addon which has registered BossBars already.
[11:55:11 INFO]: - Statistic Elements successfully loaded
[11:55:11 INFO]: - Villager Elements successfully loaded
[11:55:11 INFO]: - Advancement Elements successfully loaded
[11:55:11 INFO]: - World Border Elements successfully loaded
[11:55:11 INFO]: - Plugin is up to date!
[11:55:11 INFO]:  
[11:55:11 INFO]: --- [Server Info] ---
[11:55:11 INFO]: Server Version: git-Paper-411 (MC: 1.17.1)
[11:55:11 INFO]: Skript Version: 2.6.3
[11:55:11 INFO]: Skript Addons:
[11:55:11 INFO]: - skript-placeholders v1.5.2
[11:55:11 INFO]: - SkUniversal v2.13
[11:55:11 INFO]: - Skellett v2.0.7
[11:55:11 INFO]: - DiSky v4.1.1
[11:55:11 INFO]: - skript-yaml v1.4
[11:55:11 INFO]: - skript-reflect v2.3
[11:55:11 INFO]: - skRayFall v1.9.28
[11:55:11 INFO]: - SkQuery v4.1.6
[11:55:11 INFO]: - SkriptJSON v1.0.0
[11:55:11 INFO]: SkBee Version: 2.4.0
[11:55:11 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee`

**Comment by ShaneBeee** [comment]
this fix will be available in the next update of SkBee
for now, you can disable "ChatComponent" in Skellett's "SyntaxToggles.yml" file

**Comment by YodaZen** [comment]
> this fix will be available in the next update of SkBee
> 
> for now, you can disable "ChatComponent" in Skellett's "SyntaxToggles.yml" file

Thanks alot :)
