### ISSUE TITLE
[BUG] Error loading SkBee 2.5.3

### ISSUE THREAD

**Issue by MCSkyStar** [ShaneBeee/SkBee#290]
**Describe the bug**   
I have a server and the I downloaded v2.5.3 but it displays red in the plugins tab.

**Screenshots/Errors**   
```
[22:00:00 ERROR]: Error occurred while enabling SkBee v2.5.3 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.NamespacedKey org.bukkit.potion.PotionEffectType.getKey()'
	at com.shanebeestudios.skbee.elements.other.expressions.ExprAvailableMaterials.lambda$static$1(ExprAvailableMaterials.java:90) ~[SkBee-2.5.3.jar:?]
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473) ~[?:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:234) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1307) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at com.shanebeestudios.skbee.elements.other.expressions.ExprAvailableMaterials.<clinit>(ExprAvailableMaterials.java:90) ~[SkBee-2.5.3.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:117) ~[Skript-2.6.4 (3).jar:?]
	at com.shanebeestudios.skbee.SkBee.loadOtherElements(SkBee.java:340) ~[SkBee-2.5.3.jar:?]
	at com.shanebeestudios.skbee.SkBee.loadSkriptElements(SkBee.java:137) ~[SkBee-2.5.3.jar:?]
	at com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:77) ~[SkBee-2.5.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:00:00 INFO]: [SkBee] Disabling SkBee v2.5.3
```

**Version Info:**
SkBee Version: 2.5.3
Minecraft version: 1.17.1 (Paper)

```
An internal error occurred while attempting to preform this command
```

**Comment by ShaneBeee** [comment]
Please keep this open.
I close issues when I've actually released it

**Comment by MCSkyStar** [comment]
Thanks!
