### ISSUE TITLE
[BUG] Failed to load libraries

### ISSUE THREAD

**Issue by 0XPYEX0** [ShaneBeee/SkBee#293]
**Describe the bug**   
There are errors when loading libraries

**To Reproduce**   
Just start server

**Expected behavior**   
Load it successfully

**Screenshots/Errors**   
```
[02:48:54 INFO]: [SkBee] Loading 1 libraries... please wait
[02:48:54 ERROR]: Could not load 'plugins/SkBee-2.5.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: Error resolving libraries
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:411) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:319) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Error resolving libraries
at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:100) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
... 7 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at commons-io:commons-io:jar:2.11.0
at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:353) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:97) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
... 7 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at commons-io:commons-io:jar:2.11.0
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:288) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:97) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
... 7 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for commons-io:commons-io:jar:2.11.0
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:255) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:97) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
... 7 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact commons-io:commons-io:pom:2.11.0 from/to central (https://repo.maven.apache.org/maven2): /vdata/stormc/data/user/s3/XPYEX/Survival19/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.pom.part.lock (Permission denied)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:425) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:97) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
... 7 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact commons-io:commons-io:pom:2.11.0 from/to central (https://repo.maven.apache.org/maven2): /vdata/stormc/data/user/s3/XPYEX/Survival19/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.pom.part.lock (Permission denied)
at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73) ~[maven-resolver-util-1.7.3.jar:1.7.3]
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:97) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
... 7 more
Caused by: java.io.FileNotFoundException: /vdata/stormc/data/user/s3/XPYEX/Survival19/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.pom.part.lock (Permission denied)
at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
at java.io.RandomAccessFile.open(RandomAccessFile.java:344) ~[?:?]
at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[?:?]
at java.io.RandomAccessFile.<init>(RandomAccessFile.java:213) ~[?:?]
at org.eclipse.aether.connector.basic.PartialFile$LockFile.tryLock(PartialFile.java:138) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.connector.basic.PartialFile$LockFile.lock(PartialFile.java:82) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.connector.basic.PartialFile$LockFile.<init>(PartialFile.java:70) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.connector.basic.PartialFile$Factory.newInstance(PartialFile.java:268) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:442) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73) ~[maven-resolver-util-1.7.3.jar:1.7.3]
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:97) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
... 7 more
```

**Version Info:**
```
git-Paper-307 (MC: 1.19.2)
SkBee-2.5.3
```

**Additional context**   
None

**Comment by ShaneBeee** [comment]
This issue is not actually caused by SkBee.
It appears your server (most likely the host) is blocking external downloads.
Please contact your server host to resolve this issue.

**Comment by 0XPYEX0** [comment]
After testing, in the new version of Minecraft, the libraries are moved to the ```bundler``` directory
![image](https://user-images.githubusercontent.com/50171612/206889332-85ad8f86-9aa6-411d-a500-619830d5540f.png)
But SkBee did not adapt to this change.

**Comment by 0XPYEX0** [comment]
And I checked the file downloaded by SkBee
![7SHJVE(U356}5LJF~H0T5}3](https://user-images.githubusercontent.com/50171612/206889468-25e95402-9d86-40c6-b84c-54e0e6ecfab9.png)
Why not .jar?

**Comment by 0XPYEX0** [comment]
I fixed it.  It caused by loader system by Bukkit
![I{GWGKTC~{_ZOESR7T3FCLC](https://user-images.githubusercontent.com/50171612/206890015-562278ef-464e-4acf-88b2-279010944a44.png)
Just remove this (in plugin.yml) , and it runs okay

**Comment by ShaneBeee** [comment]
so you have solved this?
can we close this issue now?
