### ISSUE TITLE
Skript fails to start

### ISSUE THREAD

**Issue by crazedorangutan** [ShaneBeee/SkBee#303]
**Describe the bug**   
So Skript itself appears to start, but it says it fails to load the individual sk files

**To Reproduce**   
I'm not entirely sure if it's caused by conflict between addons, or if it's just the skBee itself

**Expected behavior**   
For skript to start and load the sk files

**Screenshots/Errors**   
The errors extend for roughly 3000 lines so I won't paste it all here but I'll send what appears to be repeating
```
[06:19:18] [Server thread/ERROR]: #!#! 
[06:19:18] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[06:19:18] [Server thread/ERROR]: #!#! Could not load CCCode.sk
[06:19:18] [Server thread/ERROR]: #!#! 
[06:19:18] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[06:19:18] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[06:19:18] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[06:19:18] [Server thread/ERROR]: #!#! Here is full list of them:
[06:19:18] [Server thread/ERROR]: #!#! MongoSK v2.3.0 (https://github.com/Romitou/MongoSK) skRayFall v1.9.26 (https://sk.rayfall.net/) skript-gui v1.3-alpha3 (https://github.com/APickledWalrus/skript-gui) skDragon v0.17.5 SkBee v2.6.0 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.4 FunkySk v1.0.2 Skacket v1.0.9 SkQuery v4.1.8 Skore v2.0.4 
[06:19:18] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[06:19:18] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[06:19:18] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[06:19:18] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[06:19:18] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[06:19:18] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[06:19:18] [Server thread/ERROR]: #!#! 
[06:19:18] [Server thread/ERROR]: #!#! Stack trace:
[06:19:18] [Server thread/ERROR]: #!#! java.lang.RuntimeException: pattern compiling exception, element class: com.shanebeestudios.skbee.elements.recipe.expressions.ExprMaterialChoice
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:522)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[06:19:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:19:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[06:19:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1229)
[06:19:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[06:19:18] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[06:19:18] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: material choice of %minecrafttag%]
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:54)
[06:19:18] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1254)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:522)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[06:19:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:19:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[06:19:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1229)
[06:19:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[06:19:18] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[06:19:18] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for minecrafttag
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:264)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[06:19:18] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1254)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:522)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[06:19:18] [Server thread/ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[06:19:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:19:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[06:19:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1229)
[06:19:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[06:19:18] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[06:19:18] [Server thread/ERROR]: #!#! 
[06:19:18] [Server thread/ERROR]: #!#! Version Information:
[06:19:18] [Server thread/ERROR]: #!#!   Skript: 2.6.4 (latest)
[06:19:18] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[06:19:18] [Server thread/ERROR]: #!#!     Date: 17:14:25.041218900
[06:19:18] [Server thread/ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[06:19:18] [Server thread/ERROR]: #!#!   Minecraft: 1.17.1
[06:19:18] [Server thread/ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[06:19:18] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.15.0-53-generic
[06:19:18] [Server thread/ERROR]: #!#! 
[06:19:18] [Server thread/ERROR]: #!#! Server platform: Paper
[06:19:18] [Server thread/ERROR]: #!#! 
[06:19:18] [Server thread/ERROR]: #!#! Current node: set {_seconds} to 30 (CCCode.sk, line 4)
[06:19:18] [Server thread/ERROR]: #!#! Current item: null
[06:19:18] [Server thread/ERROR]: #!#! 
[06:19:18] [Server thread/ERROR]: #!#! Thread: Server thread
[06:19:18] [Server thread/ERROR]: #!#! 
[06:19:18] [Server thread/ERROR]: #!#! Language: english
[06:19:18] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[06:19:18] [Server thread/ERROR]: #!#! 
[06:19:18] [Server thread/ERROR]: #!#! End of Error.
```

Between the repeating errors I did get this though
```
[06:19:18] [Server thread/ERROR]: #!#! 
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at Minigames.jar//au.com.mineauz.minigames.objects.ResourcePack.download(ResourcePack.java:224)
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at Minigames.jar//au.com.mineauz.minigames.objects.ResourcePack.lambda$validate$0(ResourcePack.java:160)
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[06:19:18] [Craft Scheduler Thread - 7 - Minigames/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
**Version Info:**
```
I tried doing /skbee info, but it tells me there was an internal error while trying to run the command
SkBee Ver is 2.6.0
Skript Ver is 2.6.4
![image](https://user-images.githubusercontent.com/95040748/209424533-f34f3f59-99a7-4b1f-af94-32917ece1d0f.png)

```

**Additional context**   
Not really much to say, 2.5.4 works fine but 2.6.0 completely breaks

**Comment by ShaneBeee** [comment]
thanks for letting me know, this will be fixed in the next release.
For the time being, make sure `minecraft-tag` is enabled in the SkBee config (that's what's causing this error)
