### ISSUE TITLE
Packet encoding of packet ID 78 threw (skippable? false) (via Fishing, setting items inchest with nbt compound)

### ISSUE THREAD

**Issue by tim740** [ShaneBeee/SkBee#332]
**Describe the bug**   
Fishing Executes a function which builds a chest with a random set of items, was working fine on 1.19.2
set item of fishing caught entity to chest with nbt compound from "BlockEntityTag"

**To Reproduce**   
Unknown Randomly happens and kicks the player and all players around the player.
and Still gives the nbt chest.

**Expected behavior**   
Give nbt chest with no errors and no kicking (worked fine on 1.19.2)

**Screenshots/Errors**   
`[21:42:36 ERROR]: Packet encoding of packet ID 78 threw (skippable? false)
java.lang.IllegalArgumentException: The expected number of elements must be nonnegative
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.<init>(Object2ObjectOpenHashMap.java:91) ~[fastutil-8.5.9.jar:?]
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:467) ~[?:?]
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:21) ~[?:?]
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:471) ~[?:?]
        at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:694) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:685) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.network.FriendlyByteBuf.writeItem(FriendlyByteBuf.java:643) ~[?:?]
        at net.minecraft.network.syncher.EntityDataSerializers$1.write(EntityDataSerializers.java:42) ~[?:?]
        at net.minecraft.network.syncher.EntityDataSerializers$1.copy(EntityDataSerializers.java:39) ~[?:?]
        at net.minecraft.network.syncher.SynchedEntityData$DataValue.write(SynchedEntityData.java:346) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.pack(ClientboundSetEntityDataPacket.java:18) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:38) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.19.3.jar:git-Paper-386]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:459) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:433) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Version Info:**
```
Server Version: git-Paper-386 (MC: 1.19.3)
Skript Version: 2.6.4
Skript Addons:
- skript-gui v1.3
- Khoryl v1.0.6
- skUtilities (Dev Build)
```

**Comment by ShaneBeee** [comment]
Well this is an odd one.

For starters, the fact that this works on 1.19.2 and not 1.19.3 makes me think this is Minecraft bug.
Looking at the error, it appears Minecraft is not happy with something regarding an ItemStack.

That said, I did test lightly:
```vb
on fish:
	if fishing state = caught fish:
		set {_e} to fish caught entity
		set item of {_e} to chest with nbt from "{BlockEntityTag:{Items:[{Count:5b,Slot:0b,id:""minecraft:apple""},{Count:1b,Slot:1b,id:""minecraft:bone_meal""},{Count:1b,Slot:2b,id:""minecraft:birch_stairs""}],id:""minecraft:chest""},display:{Lore:['""(+NBT)""']}}"
```
I wasn't kicked, I got the chest.

I wasn't able to reproduce the error.

Do you have code I can test?

**Comment by tim740** [comment]
The code is fairly large so this is a simpler version of what the nbt is setting to.

`on player fishing:
	if fish event state = caught fish:
		set item of fishing caught entity to chest named "chest" with lore "lore" with nbt compound from "{BlockEntityTag:{Items:[%treasureCalc(player)%]}}"`

here was the nbt that caused a crash with the same error

`[14:29:16 INFO]: treasureCalc: {Slot:0,id:nautilus_shell,Count:1},{Slot:1,id:tipped_arrow,Count:2,tag:{Potion:"minecraft:harming"}},{Slot:2,id:golden_apple,Count:1}`

So complete would of been `with nbt compound from "{BlockEntityTag:{Items:[{Slot:0,id:nautilus_shell,Count:1},{Slot:1,id:tipped_arrow,Count:2,tag:{Potion:"minecraft:harming"}},{Slot:2,id:golden_apple,Count:1}]}}"`

**Comment by ShaneBeee** [comment]
Ok I did 2 more tests using the information provided:

1) Directly using the NBT
```vb
on player fishing:
	if fish event state = caught fish:
		set {_tag} to join treasureCalc(player) with ","
		set item of fishing caught entity to chest named "chest" with lore "lore" with nbt compound from "{BlockEntityTag:{Items:[{Slot:0,id:nautilus_shell,Count:1},{Slot:1,id:tipped_arrow,Count:2,tag:{Potion:""minecraft:harming""}},{Slot:2,id:golden_apple,Count:1}]}}"
```

2) Using your function (modified a tad to return the nbt as a string) but basically the same result:
```vb
function treasureCalc(player: player) :: string:
	add "{Slot:0,id:nautilus_shell,Count:1}" to {_n::*}
	add "{Slot:1,id:tipped_arrow,Count:2,tag:{Potion:""minecraft:harming""}}" to {_n::*}
	add "{Slot:2,id:golden_apple,Count:1}" to {_n::*}
	return join {_n::*} by ","

on player fishing:
	if fish event state = caught fish:
		set {_tag} to join treasureCalc(player) with ","
		set item of fishing caught entity to chest named "chest" with lore "lore" with nbt compound from "{BlockEntityTag:{Items:[%treasureCalc(player)%]}}"
```
Both tests I got the chest and did not get any error/crash/kick
<img width="966" alt="Screenshot 2023-01-29 at 10 01 29 AM" src="https://user-images.githubusercontent.com/20008482/215346251-ce4889d6-13f3-42ac-ac20-5ff5ade75687.png">

Needless to say, I can not reproduce the issue. I'm not saying it's not an issue, I believe you are definitely having said issue, I myself just cannot make it happen.

I don't even know where I could possibly look to fix this, it just seems like MC is somewhere unhappy with an item stack

**Comment by tim740** [comment]
Yeah, it's a strange one since it doesn't seem to happen predictably, seems to happen at random

**Comment by tim740** [comment]
Just had it happen twice in a row, not sure if it will help?

`[19:16:19 INFO]: treasureCalc: {Slot:0,id:ender_pearl,Count:2},{Slot:1,id:iron_nugget,Count:6}
[19:16:19 ERROR]: Packet encoding of packet ID 78 threw (skippable? false)
java.lang.IllegalArgumentException: The expected number of elements must be nonnegative
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.<init>(Object2ObjectOpenHashMap.java:91) ~[fastutil-8.5.9.jar:?]
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:467) ~[?:?]
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:21) ~[?:?]
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:471) ~[?:?]
        at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:694) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:685) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.network.FriendlyByteBuf.writeItem(FriendlyByteBuf.java:643) ~[?:?]
        at net.minecraft.network.syncher.EntityDataSerializers$1.write(EntityDataSerializers.java:42) ~[?:?]
        at net.minecraft.network.syncher.EntityDataSerializers$1.copy(EntityDataSerializers.java:39) ~[?:?]
        at net.minecraft.network.syncher.SynchedEntityData$DataValue.write(SynchedEntityData.java:346) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.pack(ClientboundSetEntityDataPacket.java:18) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:38) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.19.3.jar:git-Paper-386]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:459) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:433) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

`[19:16:50 INFO]: treasureCalc: {Slot:0,id:ender_pearl,Count:2},{Slot:1,id:emerald,Count:1}
[19:16:50 ERROR]: Packet encoding of packet ID 78 threw (skippable? false)
java.lang.IllegalArgumentException: The expected number of elements must be nonnegative
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.<init>(Object2ObjectOpenHashMap.java:91) ~[fastutil-8.5.9.jar:?]
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:467) ~[?:?]
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:21) ~[?:?]
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:471) ~[?:?]
        at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:694) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:685) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.network.FriendlyByteBuf.writeItem(FriendlyByteBuf.java:643) ~[?:?]
        at net.minecraft.network.syncher.EntityDataSerializers$1.write(EntityDataSerializers.java:42) ~[?:?]
        at net.minecraft.network.syncher.EntityDataSerializers$1.copy(EntityDataSerializers.java:39) ~[?:?]
        at net.minecraft.network.syncher.SynchedEntityData$DataValue.write(SynchedEntityData.java:346) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.pack(ClientboundSetEntityDataPacket.java:18) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:38) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.19.3.jar:git-Paper-386]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:459) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:428) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by ShaneBeee** [comment]
no matter what I try, even using the nbt just above the error there, I can't get it to error.
It's almost as if your server hates ender pearls.

**Comment by ShaneBeee** [comment]
one suggestion I have is maybe try replicate this on a blank server, including only Skript and SkBee.
Maybe just maybe another plugin is interfering.

On my server this is all I got
```
Plugins (7): BeeConomy, PermissionsEx, RandomTeleport, SkBee, Skript, skript-reflect, Vault
```

If there is a conflict with a plugin maybe this can help sort out which plugin[s] (if any) is/are causing issues.

**Comment by ShaneBeee** [comment]
Im going to close this, as I gather it may no longer be an issue?!?
I was not able to replicate it. I am not saying you're making this up, I truly feel you had an issue, Im just not sure what is causing it.

If the issue persists, please feel free to re-open this.
