### ISSUE TITLE
[BUG] Can't read NBT File 

### ISSUE THREAD

**Issue by J-ak-e** [ShaneBeee/SkBee#350]
**Describe the bug**   
I wanted to try NBT Files for some custom items, but when I try to get the NBT of a file, it throws a massive error in the console.

**To Reproduce**   
Create the file manually and leave it empty.
Then try to get the nbt of it.
```
[10:23:07 ERROR]: #!#! Current node: null
[10:23:07 ERROR]: #!#! Current item: set {_file} (as java.lang.Object) to nbt compound from "plugins/Skript/nbt/custom_items.nbt"
[10:23:07 ERROR]: #!#! Current trigger: function saveToNBTFile (simple event) (main.sk, line 4)
```

```
options:
  filePath: "plugins/Skript/nbt/custom_items.nbt"

function saveToNBTFile(item:item, id:string):
  set {_item} to full nbt of {_item}
  set {_file} to nbt from file {@filePath}
  set compound tag {_id} of {_file} to {_item}
  save nbt file of {_file}
```

**Expected behavior**   
It should recognize that the file does not contain nbt and thus stop or just return an empty compound.

**Screenshots/Errors**
```
[10:23:07 ERROR]: #!#!
[10:23:07 ERROR]: #!#! [Skript] Severe Error:
[10:23:07 ERROR]: #!#!
[10:23:07 ERROR]: #!#! Something went horribly wrong with Skript.
[10:23:07 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[10:23:07 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[10:23:07 ERROR]: #!#! Here is full list of them:
[10:23:07 ERROR]: #!#! SkBee v2.7.5 (https://github.com/ShaneBeee/SkBee)
[10:23:07 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[10:23:07 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[10:23:07 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[10:23:07 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[10:23:07 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[10:23:07 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[10:23:07 ERROR]: #!#!
[10:23:07 ERROR]: #!#! Stack trace:
[10:23:07 ERROR]: #!#! com.shanebeestudios.skbee.api.nbt.NbtApiException: [?]Exception while reading a NBT File!
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:80)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTFile.<init>(NBTFile.java:34)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTApi.getNBTFile(NBTApi.java:157)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.lambda$get$0(ExprNbtCompound.java:115)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.registrations.Converters.convert(Converters.java:390)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:381)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:102)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:79)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:36)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:73)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:290)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:220)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:217)
[10:23:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftFuture.run(CraftFuture.java:88)
[10:23:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[10:23:07 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[10:23:07 ERROR]: #!#! Caused by: com.shanebeestudios.skbee.api.nbt.NbtApiException: [?]Error while calling the method 'readCompressed(java.io.InputStream)', loaded: true, Enum: NBTFILE_READ, Passed Class: null
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:74)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTFile.<init>(NBTFile.java:34)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTApi.getNBTFile(NBTApi.java:157)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.lambda$get$0(ExprNbtCompound.java:115)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.registrations.Converters.convert(Converters.java:390)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:381)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:102)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:79)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:36)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:73)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:290)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:220)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:217)
[10:23:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftFuture.run(CraftFuture.java:88)
[10:23:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[10:23:07 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[10:23:07 ERROR]: #!#! Caused by: java.lang.reflect.InvocationTargetException
[10:23:07 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:23:07 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[10:23:07 ERROR]: #!#!     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:23:07 ERROR]: #!#!     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:74)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTFile.<init>(NBTFile.java:34)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTApi.getNBTFile(NBTApi.java:157)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.lambda$get$0(ExprNbtCompound.java:115)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.registrations.Converters.convert(Converters.java:390)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:381)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:102)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:79)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:36)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:73)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:290)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:220)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:217)
[10:23:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftFuture.run(CraftFuture.java:88)
[10:23:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[10:23:07 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[10:23:07 ERROR]: #!#! Caused by: java.io.EOFException
[10:23:07 ERROR]: #!#!     at java.base/java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
[10:23:07 ERROR]: #!#!     at java.base/java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
[10:23:07 ERROR]: #!#!     at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
[10:23:07 ERROR]: #!#!     at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
[10:23:07 ERROR]: #!#!     at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
[10:23:07 ERROR]: #!#!     at net.minecraft.nbt.NBTCompressedStreamTools.b(NBTCompressedStreamTools.java:49)
[10:23:07 ERROR]: #!#!     at net.minecraft.nbt.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53)
[10:23:07 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:23:07 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[10:23:07 ERROR]: #!#!     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:23:07 ERROR]: #!#!     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:74)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTFile.<init>(NBTFile.java:34)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.api.nbt.NBTApi.getNBTFile(NBTApi.java:157)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.lambda$get$0(ExprNbtCompound.java:115)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.registrations.Converters.convert(Converters.java:390)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:381)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:102)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:79)
[10:23:07 ERROR]: #!#!     at SkBee-2.7.5 (1).jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:36)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:73)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:290)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:220)
[10:23:07 ERROR]: #!#!     at Skript-2.6.4 (5).jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:217)
[10:23:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftFuture.run(CraftFuture.java:88)
[10:23:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[10:23:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[10:23:07 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[10:23:07 ERROR]: #!#!
[10:23:07 ERROR]: #!#! Version Information:
[10:23:07 ERROR]: #!#!   Skript: 2.6.4 (latest)
[10:23:07 ERROR]: #!#!     Flavor: skriptlang-github
[10:23:07 ERROR]: #!#!     Date: 17:14:25.041218900
[10:23:07 ERROR]: #!#!   Bukkit: 1.19.3-R0.1-SNAPSHOT
[10:23:07 ERROR]: #!#!   Minecraft: 1.19.3
[10:23:07 ERROR]: #!#!   Java: 17.0.2 (Java HotSpot(TM) 64-Bit Server VM 17.0.2+8-LTS-86)
[10:23:07 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[10:23:07 ERROR]: #!#!
[10:23:07 ERROR]: #!#! Server platform: Paper
[10:23:07 ERROR]: #!#!
[10:23:07 ERROR]: #!#! Current node: null
[10:23:07 ERROR]: #!#! Current item: set {_file} (as java.lang.Object) to nbt compound from "plugins/Skript/nbt/custom_items.nbt"
[10:23:07 ERROR]: #!#! Current trigger: function saveToNBTFile (simple event) (main.sk, line 4)
[10:23:07 ERROR]: #!#!
[10:23:07 ERROR]: #!#! Thread: Server thread
[10:23:07 ERROR]: #!#!
[10:23:07 ERROR]: #!#! Language: english
[10:23:07 ERROR]: #!#! Link parse mode: DISABLED
[10:23:07 ERROR]: #!#!
[10:23:07 ERROR]: #!#! End of Error.
[10:23:07 ERROR]: #!#!
```

**Version Info:**
```
[10:29:17 INFO]: --- [SkBee Loading Info] ---
[10:29:17 INFO]: - [NBTAPI] Found Spigot: v1_19_R2! Trying to find NMS support
[10:29:17 INFO]: - [NBTAPI] NMS support 'MC1_19_R2' loaded!
[10:29:17 INFO]: - NBT Elements successfully loaded
[10:29:17 INFO]: - Recipe Elements successfully loaded
[10:29:17 INFO]: - Scoreboard Elements successfully loaded
[10:29:17 INFO]: - Scoreboard Objective Elements successfully loaded
[10:29:17 INFO]: - Team Elements successfully loaded
[10:29:17 INFO]: - Bound Elements successfully loaded
[10:29:17 INFO]: - Text Component Elements successfully loaded
[10:29:17 INFO]: - Pathfinding Elements successfully loaded
[10:29:17 INFO]: - Structure Elements successfully loaded
[10:29:17 INFO]: - Other Elements successfully loaded
[10:29:17 INFO]: - Virtual Furnace Elements disabled via config
[10:29:17 INFO]: - World Creator Elements successfully loaded
[10:29:17 INFO]: - Game Event Elements successfully loaded
[10:29:17 INFO]: - BossBar Elements successfully loaded
[10:29:17 INFO]: - Statistic Elements successfully loaded
[10:29:17 INFO]: - Villager Elements successfully loaded
[10:29:17 INFO]: - Advancement Elements successfully loaded
[10:29:17 INFO]: - World Border Elements successfully loaded
[10:29:17 INFO]: - Particle Elements successfully loaded
[10:29:17 INFO]: - Minecraft Tag elements successfully loaded
[10:29:17 INFO]: - RayTrace elements successfully loaded
[10:29:17 INFO]: - Fishing elements successfully loaded
[10:29:17 INFO]: - Plugin is up to date!
[10:29:17 INFO]: --- [Server Info] ---
[10:29:17 INFO]: Server Version: git-Paper-413 (MC: 1.19.3)
[10:29:17 INFO]: Skript Version: 2.6.4
[10:29:17 INFO]: Skript Addons:
[10:29:17 INFO]: SkBee Version: 2.7.5
[10:29:17 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee
```

**Additional context**   

This looks like it could give you some important info about the issue:
```
[10:20:42 ERROR]: #!#! Caused by: com.shanebeestudios.skbee.api.nbt.NbtApiException: [?]Error while calling the method 'readCompressed(java.io.InputStream)', loaded: true, Enum: NBTFILE_READ, Passed Class: null
```

/skript info:
```[10:29:34 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[10:29:34 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[10:29:34 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[10:29:34 INFO]: [Skript] Server Version: git-Paper-413 (MC: 1.19.3)
[10:29:34 INFO]: [Skript] Skript Version: 2.6.4
[10:29:34 INFO]: [Skript] Installed Skript Addons:
[10:29:34 INFO]: [Skript]  - SkBee v2.7.5 (https://github.com/ShaneBeee/SkBee)
[10:29:34 INFO]: [Skript] Installed dependencies: None```

**Comment by Fusezion** [comment]
Appears he was able to fix it after manually setting a value within it after being empty or smth. From what I understood it was just an empty file and caused an error even on newer versions until he updated the file somehow. I don't fully know his process he did

**Comment by J-ak-e** [comment]
I just deleted it and let skbee create it.

> Appears he was able to fix it after manually setting a value within it after being empty or smth. From what I understood it was just an empty file and caused an error even on newer versions until he updated the file somehow. I don't fully know his process he did

**Comment by ShaneBeee** [comment]
Yeah I wouldn't say this is a bug.
You're creating a file that doesn't follow NBT format, therefore Minecraft can't read the NBT file as its expecting to read it.

**Comment by ShaneBeee** [comment]
Closing this as non-issue
While I could suppress the error, its not likely someone is going to try load a non-NBT file as an NBT file.
