### ISSUE TITLE
[BUG] Merchant - missing ingredient causes stack trace error

### ISSUE THREAD

**Issue by TomHo41** [ShaneBeee/SkBee#351]
**Describe the bug**   
I wanted to create merchant gui, followed https://skripthub.net/docs/ 

**To Reproduce**   
Using 1.18.2 paper.jar newest Skript and Skbee version 
here is my skript: 
```
command /blackmarket:
	trigger:
		set {_merchant} to new merchant named "&x&0&0&0&0&0&0ᴅᴀʀᴋ ᴍᴀʀᴋᴇᴛ"
		set {_recipe} to new merchant recipe with result diamond sword with max uses 10
		add {_recipe} to merchant recipes of {_merchant}
		open merchant {_m} to player
```

**Expected behavior**   
It should create merchant gui with one recipe 

**Screenshots/Errors**   
```
[14:20:07 ERROR]: #!#! 
[14:20:07 ERROR]: #!#! [Skript] Severe Error:
[14:20:07 ERROR]: #!#! 
[14:20:07 ERROR]: #!#! Something went horribly wrong with Skript.
[14:20:07 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:20:07 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:20:07 ERROR]: #!#! Here is full list of them:
[14:20:07 ERROR]: #!#! SkBee v2.7.5 (https://github.com/ShaneBeee/SkBee) 
[14:20:07 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:20:07 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:20:07 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:20:07 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:20:07 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:20:07 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[14:20:07 ERROR]: #!#! 
[14:20:07 ERROR]: #!#! Stack trace:
[14:20:07 ERROR]: #!#! java.lang.IllegalStateException: No offered ingredients
[14:20:07 ERROR]: #!#!     at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
[14:20:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMerchantRecipe.toMinecraft(CraftMerchantRecipe.java:134)
[14:20:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMerchant.setRecipes(CraftMerchant.java:40)
[14:20:07 ERROR]: #!#!     at SkBee-2.7.5.jar//com.shanebeestudios.skbee.elements.villager.expressions.ExprMerchantRecipes.change(ExprMerchantRecipes.java:100)
[14:20:07 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[14:20:07 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[14:20:07 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[14:20:07 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[14:20:07 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[14:20:07 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286)
[14:20:07 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:251)
[14:20:07 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:256)
[14:20:07 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:261)
[14:20:07 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:178)
[14:20:07 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[14:20:07 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[14:20:07 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:20:07 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669)
[14:20:07 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2299)
[14:20:07 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2118)
[14:20:07 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[14:20:07 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:20:07 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[14:20:07 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[14:20:07 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:20:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:20:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:20:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1400)
[14:20:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[14:20:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[14:20:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1377)
[14:20:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[14:20:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:20:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1348)
[14:20:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1230)
[14:20:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:20:07 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[14:20:07 ERROR]: #!#! 
[14:20:07 ERROR]: #!#! Version Information:
[14:20:07 ERROR]: #!#!   Skript: 2.6.4 (latest)
[14:20:07 ERROR]: #!#!     Flavor: skriptlang-github
[14:20:07 ERROR]: #!#!     Date: 17:14:25.041218900
[14:20:07 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[14:20:07 ERROR]: #!#!   Minecraft: 1.18.2
[14:20:07 ERROR]: #!#!   Java: 17.0.6 (OpenJDK 64-Bit Server VM 17.0.6+10)
[14:20:07 ERROR]: #!#!   OS: Linux amd64 5.4.0-139-generic
[14:20:07 ERROR]: #!#! 
[14:20:07 ERROR]: #!#! Server platform: Paper
[14:20:07 ERROR]: #!#! 
[14:20:07 ERROR]: #!#! Current node: null
[14:20:07 ERROR]: #!#! Current item: add {_recipe} (as org.bukkit.inventory.MerchantRecipe) to all merchant recipes of {_merchant} (as java.lang.Object)
[14:20:07 ERROR]: #!#! Current trigger: command /blackmarket (simple event) (blackmarket.sk, line 14)
[14:20:07 ERROR]: #!#! 
[14:20:07 ERROR]: #!#! Thread: Server thread
[14:20:07 ERROR]: #!#! 
[14:20:07 ERROR]: #!#! Language: english
[14:20:07 ERROR]: #!#! Link parse mode: DISABLED
[14:20:07 ERROR]: #!#! 
[14:20:07 ERROR]: #!#! End of Error.
[14:20:07 ERROR]: #!#! 
```

**Version Info:**
Skript Version: 2.6.4 SkBee Version: 2.7.5

**Comment by ShaneBeee** [comment]
I can suppress the stack trace error, but the issue is:
`java.lang.IllegalStateException: No offered ingredients`

You didn't add an ingredient to your recipe.

**Comment by TomHo41** [comment]
Ok thanks

**Comment by ShaneBeee** [comment]
I don’t close issues til I have done a release
