### ISSUE TITLE
[BUG] 2.8.0 - Failed to start up

### ISSUE THREAD

**Issue by Fusezion** [ShaneBeee/SkBee#363]
**Describe the bug**   
After updating skbee to the 2.8.0 release skbee no longer is enabled upon start up

**To Reproduce**   
Run any version below 1.19.4 from what i understand based off their error

**Expected behavior**   
Skbee to load and enable without any issues

**Screenshots/Errors**   
```md
[10:09:47] [Server thread/INFO]: [SkBee] Enabling SkBee v2.8.0-for-Skript-2.7.0-beta1
[10:09:47] [Server thread/INFO]: [SkBee] Loading NBTApi...
[10:09:47] [Server thread/INFO]: [SkBee] [NBTAPI] Found Spigot: v1_19_R1! Trying to find NMS support
[10:09:47] [Server thread/INFO]: [SkBee] [NBTAPI] NMS support 'MC1_19_R1' loaded!
[10:09:47] [Server thread/INFO]: [SkBee] Successfully loaded NBTApi!
[10:09:47] [Server thread/INFO]: [SkBee] NBT Elements successfully loaded
[10:09:47] [Server thread/INFO]: [SkBee] Recipe Elements successfully loaded
[10:09:47] [Server thread/INFO]: [SkBee] Scoreboard Elements successfully loaded
[10:09:47] [Server thread/INFO]: [SkBee] Scoreboard Objective Elements successfully loaded
[10:09:47] [Server thread/INFO]: [SkBee] Team Elements successfully loaded
[10:09:47] [Server thread/INFO]: [SkBee] Bound Elements successfully loaded
[10:09:47] [Server thread/INFO]: [SkBee] Text Component Elements successfully loaded
[10:09:47] [Server thread/INFO]: [SkBee] Pathfinding Elements successfully loaded
[10:09:47] [Server thread/INFO]: [SkBee] Structure Elements successfully loaded
[10:09:47] [Server thread/ERROR]: Error occurred while enabling SkBee v2.8.0-for-Skript-2.7.0-beta1 (Is it up to date?)
java.lang.NoClassDefFoundError: io/papermc/paper/math/Position
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at ch.njol.skript.util.Utils.getClasses(Utils.java:201) ~[Skript-2.7.0-beta1.jar:?]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82) ~[Skript-2.7.0-beta1.jar:?]
	at com.shanebeestudios.skbee.AddonLoader.loadOtherElements(AddonLoader.java:311) ~[SkBee-2.8.0-for-Skript-2.7.0-beta1.jar:?]
	at com.shanebeestudios.skbee.AddonLoader.loadSkriptElements(AddonLoader.java:90) ~[SkBee-2.8.0-for-Skript-2.7.0-beta1.jar:?]
	at com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:55) ~[SkBee-2.8.0-for-Skript-2.7.0-beta1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.papermc.paper.math.Position
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 18 more
[10:09:47] [Server thread/INFO]: [SkBee] Disabling SkBee v2.8.0-for-Skript-2.7.0-beta1
```

**Version Info:**
if skbee loaded sure but here's skript info
```md
[10:18:40 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[10:18:40 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[10:18:40 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[10:18:40 INFO]: [Skript] Server Version: git-Paper-307 (MC: 1.19.2)
[10:18:40 INFO]: [Skript] Skript Version: 2.7.0-beta1 (skriptlang-github)
[10:18:40 INFO]: [Skript] Installed Skript Addons: 
[10:18:40 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[10:18:40 INFO]: [Skript]  - SkBee v2.8.0-for-Skript-2.7.0-beta1 (https://github.com/ShaneBeee/SkBee)
[10:18:40 INFO]: [Skript] Installed dependencies: None
```

**Additional context**   
This is pointing the errors towards the Other Elements folder was unable to determine a proper root cause
originally thought this was caused by my build but tested with the official release and it continued

**Comment by Fusezion** [comment]
Tested this again in 1.19.3, this error seems fixed it's only for 1.19.2 and below it seems

**Comment by Fusezion** [comment]
As far as I remember didn't skbee support 1.17+, with the issue existing in 1.19.2 would it not mean it would also leads down to those as well? Unless I missed a release saying it was dropped which is very likely.

**Comment by ShaneBeee** [comment]
Ok I will re-open this and mark it as a bug, but I don't know that I'll put much effort into it.
Unfortunately the way Skript loads classes, lacks any real detail when an error occurs.
error:
`java.lang.NoClassDefFoundError: io/papermc/paper/math/Position`
Yet no where in SkBee's code am I touching this class, so Im quite unsure where its stemming from.
