### ISSUE TITLE
[BUG] NBT ERRORS on Skript 2.7.0-beta2

### ISSUE THREAD

**Issue by savoryninja1** [ShaneBeee/SkBee#371]
anywhere where you put nbt's expressions and try and do it ingame it throws back errors.

1 example
[01:56:08 ERROR]: Could not pass event BlockBreakEvent to Skript v2.7.0-beta2
java.lang.NoSuchMethodError: 'java.lang.Object[] com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(java.lang.Object[], org.skriptlang.skript.lang.converter.Converter)'
        at com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:79) ~[SkBee-2.8.1-for-Skript-2.7.0-beta1.jar:?]
        at com.shanebeestudios.skbee.elements.nbt.expressions.ExprNbtCompound.get(ExprNbtCompound.java:36) ~[SkBee-2.8.1-for-Skript-2.7.0-beta1.jar:?]
        at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:88) ~[Skript-2.7.0-beta2.jar:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101) ~[Skript-2.7.0-beta2.jar:?]
        at ch.njol.skript.effects.EffChange.execute(EffChange.java:272) ~[Skript-2.7.0-beta2.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript-2.7.0-beta2.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62) ~[Skript-2.7.0-beta2.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[Skript-2.7.0-beta2.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript-2.7.0-beta2.jar:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146) ~[Skript-2.7.0-beta2.jar:?]
        at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:47) ~[Skript-2.7.0-beta2.jar:?]
        at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:60) ~[Skript-2.7.0-beta2.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-471]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-471]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-471]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:377) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:336) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:274) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1861) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-471]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.4.jar:git-Paper-471]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-471]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.4.jar:git-Paper-471]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.4.jar:git-Paper-471]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.4.jar:git-Paper-471]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.4.jar:git-Paper-471]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-471]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ShaneBeee** [comment]
"2.8.1-for-Skript-2.7.0-beta1.jar" was a jar specifically built for Skript 2.7.0-beta1.
Please use SkBee 2.8.1
