### ISSUE TITLE
[BUG] "Entity NBT needs to be accessed sync!" error only in steering vehicle event.

### ISSUE THREAD

**Issue by HC-Emro** [ShaneBeee/SkBee#379]
**Describe the bug**   
When I want to edit nbt of an armor stand on steer vehicle event (from Skacket), it doesn't work and give me a console error.

**To Reproduce**   
`on steering vehicle:
    set {_tourne} to 6 - vector length of velocity of player's vehicle * 2 # This value is not important
    add nbt compound from "{Rotation:[%yaw of player's vehicle - {_tourne}%f,0.0f]}" to nbt compound of player's vehicle # The problem is here, It doesn't work and the console says "Entity NBT needs to be accessed sync!". The expression works very well in other events, but not there.
`

**Expected behavior**   
To not show a error and modify the nbt of player's vehicle (armor stand)

**Screenshots/Errors**   
`
[05:46:04 ERROR]: #!#!
>.... [05:46:04 ERROR]: #!#! [Skript] Severe Error:
>.... [05:46:04 ERROR]: #!#!
>.... [05:46:04 ERROR]: #!#! Something went horribly wrong with Skript.
>.... [05:46:04 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
>.... [05:46:04 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
>.... [05:46:04 ERROR]: #!#! Following plugins are probably related to this error in some way:
>.... [05:46:04 ERROR]: #!#! Skacket
>.... [05:46:04 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
>.... [05:46:04 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
>.... [05:46:04 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
>.... [05:46:04 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
>.... [05:46:04 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
>.... [05:46:04 ERROR]: #!#!
>.... [05:46:04 ERROR]: #!#! Stack trace:
>.... [05:46:04 ERROR]: #!#! com.shanebeestudios.skbee.api.nbt.NbtApiException: [?]Entity NBT needs to be accessed sync!
>.... [05:46:04 ERROR]: #!#! at SkBee-2.8.3.jar//com.shanebeestudios.skbee.api.nbt.NBTEntity.getCompound(NBTEntity.java:37)
>.... [05:46:04 ERROR]: #!#! at SkBee-2.8.3.jar//com.shanebeestudios.skbee.api.nbt.NBTReflectionUtil.mergeOtherNBTCompound(NBTReflectionUtil.java:369)
>.... [05:46:04 ERROR]: #!#! at SkBee-2.8.3.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.mergeCompound(NBTCompound.java:89)
>.... [05:46:04 ERROR]: #!#! at SkBee-2.8.3.jar//com.shanebeestudios.skbee.api.nbt.NBTCustomEntity.mergeCompound(NBTCustomEntity.java:62)
>.... [05:46:04 ERROR]: #!#! at SkBee-2.8.3.jar//com.shanebeestudios.skbee.elements.nbt.types.SkriptTypes$1.change(SkriptTypes.java:38)
>.... [05:46:04 ERROR]: #!#! at SkBee-2.8.3.jar//com.shanebeestudios.skbee.elements.nbt.types.SkriptTypes$1.change(SkriptTypes.java:23)
>.... [05:46:04 ERROR]: #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.util.SimpleExpression.change(SimpleExpression.java:240)
>.... [05:46:04 ERROR]: #!#! at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
>.... [05:46:04 ERROR]: #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
>.... [05:46:04 ERROR]: #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
>.... [05:46:04 ERROR]: #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
>.... [05:46:04 ERROR]: #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
>.... [05:46:04 ERROR]: #!#! at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
>.... [05:46:04 ERROR]: #!#! at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
>.... [05:46:04 ERROR]: #!#! at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
>.... [05:46:04 ERROR]: #!#! at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
>.... [05:46:04 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [05:46:04 ERROR]: #!#! at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
>.... [05:46:04 ERROR]: #!#! at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
>.... [05:46:04 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
>.... [05:46:04 ERROR]: #!#! at Skacket-1.0.13.jar//me.limeglass.skacket.listeners.PacketListeners$2.onPacketReceiving(PacketListeners.java:84)
>.... [05:46:04 ERROR]: #!#! at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:122)
>.... [05:46:04 ERROR]: #!#! at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:75)
>.... [05:46:04 ERROR]: #!#! at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:557)
>.... [05:46:04 ERROR]: #!#! at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:521)
>.... [05:46:04 ERROR]: #!#! at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:118)
>.... [05:46:04 ERROR]: #!#! at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:500)
>.... [05:46:04 ERROR]: #!#! at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
>.... [05:46:04 ERROR]: #!#! at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
>.... [05:46:04 ERROR]: #!#! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
>.... [05:46:04 ERROR]: #!#! at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
>.... [05:46:04 ERROR]: #!#! at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
>.... [05:46:04 ERROR]: #!#! at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
>.... [05:46:04 ERROR]: #!#! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
>.... [05:46:04 ERROR]: #!#! at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
>.... [05:46:04 ERROR]: #!#! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
>.... [05:46:04 ERROR]: #!#! at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
>.... [05:46:04 ERROR]: #!#! at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
>.... [05:46:04 ERROR]: #!#! at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
>.... [05:46:04 ERROR]: #!#! at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
>.... [05:46:04 ERROR]: #!#! at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>.... [05:46:04 ERROR]: #!#! at java.base/java.lang.Thread.run(Thread.java:833)
>.... [05:46:04 ERROR]: #!#!
>.... [05:46:04 ERROR]: #!#! Version Information:
>.... [05:46:04 ERROR]: #!#! Skript: 2.6.4 (latest)
>.... [05:46:04 ERROR]: #!#! Flavor: skriptlang-github
>.... [05:46:04 ERROR]: #!#! Date: 17:14:25.041218900
>.... [05:46:04 ERROR]: #!#! Bukkit: 1.19.4-R0.1-SNAPSHOT
>.... [05:46:04 ERROR]: #!#! Minecraft: 1.19.4
>.... [05:46:04 ERROR]: #!#! Java: 17.0.5 (OpenJDK 64-Bit Server VM 17.0.5+8)
>.... [05:46:04 ERROR]: #!#! OS: Linux amd64 4.9.0-16-amd64
>.... [05:46:04 ERROR]: #!#!
>.... [05:46:04 ERROR]: #!#! Server platform: Paper
>.... [05:46:04 ERROR]: #!#!
>.... [05:46:04 ERROR]: #!#! Current node: null
>.... [05:46:04 ERROR]: #!#! Current item: add nbt compound from "{Rotation:[%the yaw of (the vehicle of the player >> ch.njol.skript.classes.data.DefaultConverters$11@6e7a5d9d: entity -> location) - {_tourne} (as java.lang.Number)%f,0.0f]}" to nbt compound from the vehicle of the player
>.... [05:46:04 ERROR]: #!#! Current trigger: steering vehicle (on vehicle steer) (hcars.sk, line 280)
>.... [05:46:04 ERROR]: #!#!
>.... [05:46:04 ERROR]: #!#! Thread: Netty Epoll Server IO #3
>.... [05:46:04 ERROR]: #!#!
>.... [05:46:04 ERROR]: #!#! Language: english
>.... [05:46:04 ERROR]: #!#! Link parse mode: STRICT
>.... [05:46:04 ERROR]: #!#!
>.... [05:46:04 ERROR]: #!#! End of Error.
>.... [05:46:04 ERROR]: #!#!
`

**Version Info:**
```
>....=>.... [06:01:28 INFO]: --- [SkBee Loading Info] ---
>.... [06:01:28 INFO]: - [NBTAPI] Found Spigot: v1_19_R3! Trying to find NMS support
>.... [06:01:28 INFO]: - [NBTAPI] NMS support 'MC1_19_R3' loaded!
>.... [06:01:28 INFO]: - NBT Elements successfully loaded
>.... [06:01:28 INFO]: - Recipe Elements successfully loaded
>.... [06:01:28 INFO]: - Scoreboard Elements successfully loaded
>.... [06:01:28 INFO]: - Scoreboard Objective Elements successfully loaded
>.... [06:01:28 INFO]: - Team Elements successfully loaded
>.... [06:01:28 INFO]: - Bound Elements successfully loaded
>.... [06:01:28 INFO]: - Text Component Elements successfully loaded
>.... [06:01:28 INFO]: - Pathfinding Elements successfully loaded
>.... [06:01:28 INFO]: - Structure Elements successfully loaded
>.... [06:01:28 INFO]: - Other Elements successfully loaded
>.... [06:01:28 INFO]: - Virtual Furnace Elements disabled via config
>.... [06:01:28 INFO]: - World Creator Elements successfully loaded
>.... [06:01:28 INFO]: - Game Event Elements successfully loaded
>.... [06:01:28 INFO]: - BossBar Elements successfully loaded
>.... [06:01:28 INFO]: - Statistic Elements successfully loaded
>.... [06:01:28 INFO]: - Villager Elements successfully loaded
>.... [06:01:28 INFO]: - Advancement Elements successfully loaded
>.... [06:01:28 INFO]: - World Border Elements successfully loaded
>.... [06:01:28 INFO]: - Particle Elements successfully loaded
>.... [06:01:28 INFO]: - Minecraft Tag elements successfully loaded
>.... [06:01:28 INFO]: - RayTrace elements successfully loaded
>.... [06:01:28 INFO]: - Fishing elements successfully loaded
>.... [06:01:28 INFO]: - Display Entity elements disabled due to a Bukkit API change!
>.... [06:01:28 INFO]: - - You need to update your server to fix this issue!
>.... [06:01:28 INFO]: - Plugin is up to date!
>.... [06:01:28 INFO]: --- [Server Info] ---
>.... [06:01:28 INFO]: Server Version: git-Paper-510 (MC: 1.19.4)
>.... [06:01:28 INFO]: Skript Version: 2.6.4
>.... [06:01:28 INFO]: Skript Addons:
>.... [06:01:28 INFO]: - Skacket v1.0.13
>.... [06:01:28 INFO]: - skript-gui v1.3
>.... [06:01:28 INFO]: - Skellett v2.0.9
>.... [06:01:28 INFO]: - skUtilities v0.9.2
>.... [06:01:28 INFO]: - skript-db v1.3.9
>.... [06:01:28 INFO]: - skRayFall v1.9.28
>.... [06:01:28 INFO]: - SkQuery v4.1.9
>.... [06:01:28 INFO]: SkBee Version: 2.8.4
>.... [06:01:28 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee
```

**Additional context**   
Maybe it's because Skacket and non stable 1.19.4 Protocolib version but the steering event works very well, it's just causing trouble with nbt.

**Comment by ShaneBeee** [comment]
Sounds to me like the event is async or something.
The API is saying the nbt must be sync, so there's nothing I can do about that.
