### ISSUE TITLE
[BUG] Bounds expression

### ISSUE THREAD

**Issue by jurajplayercze** [ShaneBeee/SkBee#381]
**Describe the bug**   
That's going to be WTF moment
To reproduce it, i made simple script down here. it should broadcast both yellow and both red players, but it looks like the loop stops in middle. When i delete condition "if bound at...", it works as expected. 

**To Reproduce**   
```
    set {_players::*} to (players of bound with id "test")
    broadcast "&e%{_players::*}%"
    loop {_players::*}:
        broadcast "&c%loop-value%"
        if bound at loop-value is bound with id "test":
            broadcast "1"
```
**Expected behavior**   
broadcast both players yellow and both players red

**Screenshots/Errors**   
No errors
![image](https://user-images.githubusercontent.com/83863655/232313007-31c54000-c574-4d1d-9535-b6030a6b8f62.png)

**Version Info:**
```
Skript 2.6.4
SkBee (2.8.4)
```

**Additional context**

**Comment by AyhamAl-Ali** [comment]
Sounds like an NPE was thrown, check console maybe?

**Comment by jurajplayercze** [comment]
> 
That's why i wrote in section "Screenshots/Errors" 
No errors :D Because there are no errors :D

**Comment by ShaneBeee** [comment]
Ok so I tried your exact code, threw it in a command:
```vb
command /test:
	trigger:
		set {_players::*} to (players of bound with id "test")
		broadcast "&e%{_players::*}%"
		loop {_players::*}:
			broadcast "&c%loop-value%"
			if bound at loop-value is bound with id "test":
				broadcast "1"
```
Outcome:
<img width="966" alt="Screenshot 2023-04-16 at 8 18 50 AM" src="https://user-images.githubusercontent.com/20008482/232322718-73954029-b176-42ea-85ca-3fba6946adfa.png">

**Comment by ShaneBeee** [comment]
After further testing, there was an error:
```
[09:24:14 ERROR]: #!#! 
[09:24:14 ERROR]: #!#! [Skript] Severe Error:
[09:24:14 ERROR]: #!#! 
[09:24:14 ERROR]: #!#! Something went horribly wrong with Skript.
[09:24:14 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:24:14 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[09:24:14 ERROR]: #!#! Here is full list of them:
[09:24:14 ERROR]: #!#! skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) SkBee v2.8.4 (https://github.com/ShaneBeee/SkBee) 
[09:24:14 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[09:24:14 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[09:24:14 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[09:24:14 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[09:24:14 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[09:24:14 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[09:24:14 ERROR]: #!#! 
[09:24:14 ERROR]: #!#! Stack trace:
[09:24:14 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "loc" is null
[09:24:14 ERROR]: #!#!     at SkBee-2.8.4.jar//com.shanebeestudios.skbee.elements.bound.objects.Bound.isInRegion(Bound.java:70)
[09:24:14 ERROR]: #!#!     at SkBee-2.8.4.jar//com.shanebeestudios.skbee.elements.bound.expressions.ExprBoundAtLocation.get(ExprBoundAtLocation.java:63)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.VariableString.getMessageComponents(VariableString.java:442)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:120)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:83)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:251)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:256)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:261)
[09:24:14 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:178)
[09:24:14 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[09:24:14 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[09:24:14 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[09:24:14 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[09:24:14 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[09:24:14 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[09:24:14 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2266)
[09:24:14 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2250)
[09:24:14 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[09:24:14 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[09:24:14 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[09:24:14 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[09:24:14 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[09:24:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1342)
[09:24:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[09:24:14 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[09:24:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1319)
[09:24:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1312)
[09:24:14 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[09:24:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1290)
[09:24:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1178)
[09:24:14 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[09:24:14 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1589)
[09:24:14 ERROR]: #!#! 
[09:24:14 ERROR]: #!#! Version Information:
[09:24:14 ERROR]: #!#!   Skript: 2.6.4
[09:24:14 ERROR]: #!#!     Flavor: skriptlang-github
[09:24:14 ERROR]: #!#!     Date: 17:14:25.041218900
[09:24:14 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[09:24:14 ERROR]: #!#!   Minecraft: 1.19.4
[09:24:14 ERROR]: #!#!   Java: 19.0.2 (OpenJDK 64-Bit Server VM 19.0.2+7)
[09:24:14 ERROR]: #!#!   OS: Mac OS X aarch64 13.3.1
[09:24:14 ERROR]: #!#! 
[09:24:14 ERROR]: #!#! Server platform: Paper
[09:24:14 ERROR]: #!#! 
[09:24:14 ERROR]: #!#! Current node: null
[09:24:14 ERROR]: #!#! Current item: broadcast "§c%loop-value% :: %bounds at location (loop-value >> ch.njol.skript.classes.Converter$ConverterUtils$1@687aec60: object -> location)%"
[09:24:14 ERROR]: #!#! Current trigger: function JPLavaJumpingBoard (simple event) (test.sk, line 2)
[09:24:14 ERROR]: #!#! 
[09:24:14 ERROR]: #!#! Thread: Server thread
[09:24:14 ERROR]: #!#! 
[09:24:14 ERROR]: #!#! Language: english
[09:24:14 ERROR]: #!#! Link parse mode: LENIENT
[09:24:14 ERROR]: #!#! 
[09:24:14 ERROR]: #!#! End of Error.
[09:24:14 ERROR]: #!#! 
```

That said, I have fixed the error, but the issue itself stems from Skript, for some reason `location of loop-value` is returning null... therefore not able to get the region at the loop-value, that I cannot fix.
