### ISSUE TITLE
[BUG] skbee is disable

### ISSUE THREAD

**Issue by udukiukia** [ShaneBeee/SkBee#429]
**Describe the bug**   

skbee is disable

**To Reproduce**   
Please include clear steps to reproduce the behavior

command /skbee

**Expected behavior**   

idont know

**Screenshots/Errors**   
If applicable, add screenshots/errors to help explain your problem.
<img width="632" alt="スクリーンショット 2023-07-08 19 40 22" src="https://github.com/ShaneBeee/SkBee/assets/131680691/8aa14288-c80d-47f6-878c-d3eed17b6bf3">

**Version Info:**
```
Please provide output of '/skbee info' here!

[19:38:17 INFO]: [PLAYERCMD] udukiyukia: /skbee info
[19:38:17 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'skbee' in plugin SkBee v2.14.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1017) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2392) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2352) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1452) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Additional context**   

purpur #2001 MC v1.20.1
skript v2.7.0-beta3
skbee v2.14.1

**Comment by ShaneBeee** [comment]
this error doesn't provide any information as to why the plugin is actually disabled.
Please provide the section of your startup log that would show why SkBee failed to load

**Comment by ShaneBeee** [comment]
closing due to lack of response
