### ISSUE TITLE
[BUG] StackTrace error when ingredients are null

### ISSUE THREAD

**Issue by Abendsaufstehen** [ShaneBeee/SkBee#435]
### What happened?

```
[00:32:04] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[00:32:04] [Server thread/ERROR]: #!#! 
[00:32:04] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[00:32:04] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:32:04] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:32:04] [Server thread/ERROR]: #!#! Here is full list of them:
[00:32:04] [Server thread/ERROR]: #!#! Skript-AnvilGUI v1.2 MorkazSk v1.3 skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) PermSk v1.1.1 (https://iplexy.de) SkBee v2.14.1 (https://github.com/ShaneBeee/SkBee) SkQuery v4.1.9 
[00:32:04] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:32:04] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:32:04] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:32:04] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:32:04] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:32:04] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:32:04] [Server thread/ERROR]: #!#! 
[00:32:04] [Server thread/ERROR]: #!#! Stack trace:
[00:32:04] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Crafting recipes should be 1, 2 or 3 rows, not  [0]
[00:32:04] [Server thread/ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:193)
[00:32:04] [Server thread/ERROR]: #!#!     at org.bukkit.inventory.ShapedRecipe.shape(ShapedRecipe.java:78)
[00:32:04] [Server thread/ERROR]: #!#!     at SkBee-2.14.1.jar//com.shanebeestudios.skbee.elements.recipe.effects.EffCraftingRecipe.registerShaped(EffCraftingRecipe.java:149)
[00:32:04] [Server thread/ERROR]: #!#!     at SkBee-2.14.1.jar//com.shanebeestudios.skbee.elements.recipe.effects.EffCraftingRecipe.execute(EffCraftingRecipe.java:106)
[00:32:04] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[00:32:04] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[00:32:04] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[00:32:04] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[00:32:04] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.events.EvtScript.runTrigger(EvtScript.java:88)
[00:32:04] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.events.EvtScript.postLoad(EvtScript.java:61)
[00:32:04] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$9(ScriptLoader.java:572)
[00:32:04] [Server thread/ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
[00:32:04] [Server thread/ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
[00:32:04] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:568)
[00:32:04] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[00:32:04] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[00:32:04] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
[00:32:04] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:511)
[00:32:04] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[00:32:04] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.Skript$1.run(Skript.java:815)
[00:32:04] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[00:32:04] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[00:32:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
[00:32:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[00:32:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[00:32:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[00:32:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[00:32:04] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1623)
[00:32:04] [Server thread/ERROR]: #!#! 
[00:32:04] [Server thread/ERROR]: #!#! Version Information:
[00:32:04] [Server thread/ERROR]: #!#!   Skript: 2.7.0-beta3 (latest)
[00:32:04] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[00:32:04] [Server thread/ERROR]: #!#!     Date: 03:18:03.366646700
[00:32:04] [Server thread/ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[00:32:04] [Server thread/ERROR]: #!#!   Minecraft: 1.20.1
[00:32:04] [Server thread/ERROR]: #!#!   Java: 20.0.1 (Java HotSpot(TM) 64-Bit Server VM 20.0.1+9-29)
[00:32:04] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.19.0-46-generic
[00:32:04] [Server thread/ERROR]: #!#! 
[00:32:04] [Server thread/ERROR]: #!#! Server platform: Paper
[00:32:04] [Server thread/ERROR]: #!#! 
[00:32:04] [Server thread/ERROR]: #!#! Current node: on load: (items/NON STACKABLE/armor/heavy_armor/heavy_leggings.sk, line 1)
[00:32:04] [Server thread/ERROR]: #!#! Current item: Register new shaped recipe for {item::armor::heavy_leggings} (as ch.njol.skript.aliases.ItemType) using ({item::ingot::heavy_ingot} (as java.lang.Object), {item::ingot::heavy_ingot} (as java.lang.Object), {item::ingot::heavy_ingot} (as java.lang.Object), {item::ingot::heavy_ingot} (as java.lang.Object), [[itemtype:air]], {item::ingot::heavy_ingot} (as java.lang.Object), {item::ingot::heavy_ingot} (as java.lang.Object), [[itemtype:air]] and {item::ingot::heavy_ingot} (as java.lang.Object))[class java.lang.Object] with id '"HEAVY_LEGGINGS"' in group "RECIPE_HEAVY_LEGGINGS"
[00:32:04] [Server thread/ERROR]: #!#! Current trigger: load (script load) (items/NON STACKABLE/armor/heavy_armor/heavy_leggings.sk, line 1)
[00:32:04] [Server thread/ERROR]: #!#! 
[00:32:04] [Server thread/ERROR]: #!#! Thread: Server thread
[00:32:04] [Server thread/ERROR]: #!#! 
[00:32:04] [Server thread/ERROR]: #!#! Language: english
[00:32:04] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[00:32:04] [Server thread/ERROR]: #!#! 
[00:32:04] [Server thread/ERROR]: #!#! End of Error.
[00:32:04] [Server thread/ERROR]: #!#! 
```

### Steps to reproduce

use a recipe idk really i just used this line of code `	register shaped recipe for {item::armor::heavy_leggings} using {item::ingot::heavy_ingot}, {item::ingot::heavy_ingot}, {item::ingot::heavy_ingot}, {item::ingot::heavy_ingot}, air, {item::ingot::heavy_ingot}, {item::ingot::heavy_ingot}, air and {item::ingot::heavy_ingot} with id "HEAVY_LEGGINGS" in group "RECIPE_HEAVY_LEGGINGS"
`

### Expected behavior

FATAL SKRIPT ERROR logs shown before

### SkBee Version

2.14.1

### Server Version

git-Paper-61 MC: 1.20.1

### SkBee Info

```
[00:35:26 INFO]: --- [SkBee Loading Info] ---
[00:35:26 INFO]: - [NBTAPI] Found Spigot: v1_20_R1! Trying to find NMS support
[00:35:26 INFO]: - [NBTAPI] NMS support 'MC1_20_R1' loaded!
[00:35:26 INFO]: - NBT Elements successfully loaded
[00:35:26 INFO]: - Recipe Elements successfully loaded
[00:35:26 INFO]: - Scoreboard Elements successfully loaded
[00:35:26 INFO]: - Scoreboard Objective Elements successfully loaded
[00:35:26 INFO]: - Team Elements successfully loaded
[00:35:26 INFO]: - Bound Elements successfully loaded
[00:35:26 INFO]: - Text Component Elements successfully loaded
[00:35:26 INFO]: - Pathfinding Elements successfully loaded
[00:35:26 INFO]: - Structure Elements successfully loaded
[00:35:26 INFO]: - Other Elements successfully loaded
[00:35:26 INFO]: - Virtual Furnace Elements disabled via config
[00:35:26 INFO]: - World Creator Elements successfully loaded
[00:35:26 INFO]: - Game Event Elements successfully loaded
[00:35:26 INFO]: - BossBar Elements successfully loaded
[00:35:26 INFO]: - Statistic Elements successfully loaded
[00:35:26 INFO]: - Villager Elements successfully loaded
[00:35:26 INFO]: - Advancement Elements successfully loaded
[00:35:26 INFO]: - World Border Elements successfully loaded
[00:35:26 INFO]: - Particle Elements successfully loaded
[00:35:26 INFO]: - Minecraft Tag elements successfully loaded
[00:35:26 INFO]: - RayTrace elements successfully loaded
[00:35:26 INFO]: - Fishing elements successfully loaded
[00:35:26 INFO]: - Display Entity elements successfully loaded
[00:35:26 INFO]: --- [Server Info] ---
[00:35:26 INFO]: Server Version: git-Paper-61 (MC: 1.20.1)
[00:35:26 INFO]: Skript Version: 2.7.0-beta3
[00:35:26 INFO]: Skript Addons:
[00:35:26 INFO]: - PermSk v1.1.1
[00:35:26 INFO]: - Skript-AnvilGUI v1.2
[00:35:26 INFO]: - skript-gui v1.3
[00:35:26 INFO]: - MorkazSk v1.3
[00:35:26 INFO]: - SkQuery v4.1.9
[00:35:26 INFO]: SkBee Version: 2.14.1
[00:35:26 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

```

**Comment by ShaneBeee** [comment]
what is `{item::ingot::heavy_ingot}` set to?

**Comment by Abendsaufstehen** [comment]
set {item::ingot::heavy_ingot} to iron ingot with all flags hidden named "&aHeavy Ingot" with lore "", "&7A &avery &7massive and heavy", "&7ingot that can be &aforged", "&7into &aTools & Weapons", "", "", "&a&lUncommon Ingredient" and "&8ID: INGOT_HEAVY_INGOT" with nbt {_cmd}

**Comment by Abendsaufstehen** [comment]
@ShaneBeee

**Comment by ShaneBeee** [comment]
please stop tagging me in my repo, I very CLEARLY get emails/alerts for replies here.

That said, the issue is with your item, it doesn't appear to be creating, therefor leaving your recipe to not have ingredients

**Comment by Abendsaufstehen** [comment]
how can there be an issue with the item it worked like 1h before then i added 2 more recipies and it broke everything

**Comment by ShaneBeee** [comment]
I dunno but looking at the error:

Valid Item = `{item::armor::heavy_leggings} (as ch.njol.skript.aliases.ItemType)`
(notice how its as "ItemType")

Invalid Item = `{item::ingot::heavy_ingot} (as java.lang.Object)`
(notice how its as "Object" ... meaning nothing probably)

**Comment by Abendsaufstehen** [comment]
heavy ingot is just a iron ingot with a name & lore & and CustomModelDatahow can this be a Nothing thing

**Comment by ShaneBeee** [comment]
I dunno what to tell ya, according to the error the variable isn't set
I can suppress the error but I can't fix your code

**Comment by Abendsaufstehen** [comment]
wym suppress the error aint a genius lmao

**Comment by ShaneBeee** [comment]
suppress = no send error, make error go bye bye

**Comment by Abendsaufstehen** [comment]
so no error = work, no?

**Comment by ShaneBeee** [comment]
no, it means no errors

**Comment by Abendsaufstehen** [comment]
just no errors shown but still not work

**Comment by ShaneBeee** [comment]
yep, the issue here is the error.  That I can fix, but I can't fix the code you have written.

**Comment by Abendsaufstehen** [comment]
k do you have any tips how i can fix this cuz im dying inside rn lmfao

on load:
	set {item::customModel::heavy_ingot} to 639
	set {_cmd} to nbt compound from "{CustomModelData:%{item::customModel::heavy_ingot}%}"
	set {item::ingot::heavy_ingot} to iron ingot with all flags hidden named "&aHeavy Ingot" with lore "", "&7A &avery &7massive and heavy", "&7ingot that can be &aforged", "&7into &aTools & Weapons", "", "", "&a&lUncommon Ingredient" and "&8ID: INGOT_HEAVY_INGOT" with nbt {_cmd}
	set {item::ID::heavy_ingot} to "HEAVY_INGOT"
	set {item::heavy_ingot} to {item::ingot::heavy_ingot}
	register shaped recipe for {item::ingot::heavy_ingot} using iron ingot, iron ingot, iron ingot, iron ingot, air, iron ingot, iron ingot, iron ingot and iron ingot with id "HEAVY_INGOT" in group "RECIPE_HEAVY_INGOT"
	
this is my ingot code

**Comment by Abendsaufstehen** [comment]
Shane why does it work for my Sword but not for my Armor like look for a sec:
`	register shaped recipe for {item::armor::heavy_boots} using {item::ingot::heavy_ingot}, air ,air ,air ,air ,air ,air, air and air with id "HEAVY_BOOTS" in group "RECIPE_HEAVY_BOOTS"`
This does NOT work

`	register shaped recipe for {item::weapon::heavy_sword} using air, {item::ingot::heavy_ingot}, {item::ingot::heavy_ingot}, {item::ingot::heavy_ingot}, {item::ingot::heavy_ingot}, {item::ingot::heavy_ingot}, stick, {item::ingot::heavy_ingot} and air with id "HEAVY_SWORD" in group "RECIPE_HEAVY_SWORD"`
This DOES work like why is that

**Comment by ShaneBeee** [comment]
I dunno, this is an issue tracker not a help channel.
If you need help with your code, please use skUnity's discord
