### ISSUE TITLE
[BUG] Structures giving weird error in console when loading script

### ISSUE THREAD

**Issue by not-3than** [ShaneBeee/SkBee#440]
### What happened?

I previously was on 2.5.3, and now that I updated to 2.15.0, my structures aren't working anymore. No errors when the script reloads, but a long error in console. I had to change syntax for disabling saving entities in this script, but even then nothing has changed.

### Steps to reproduce

1. Upload https://pastebin.com/HKBdXBv5 (script file) to server. I'm using Paper 1.18.2, Skript 2.6.3, and SkBee 2.15.0
2. Load, and an error appears in console and the structures/script itself doesn't work.

### Expected behavior

Previous to me updating SkBee, this script worked fine and no errors in console.

### SkBee Version

2.15.0

### Server Version

Paper 1.18.2

### SkBee Info

[01:59:10 INFO]: --- [SkBee Loading Info] ---
[01:59:10 INFO]: - Other Elements successfully loaded
[01:59:10 INFO]: - [NBTAPI] Found Spigot: v1_18_R2! Trying to find NMS support
[01:59:10 INFO]: - [NBTAPI] NMS support 'MC1_18_R2' loaded!
[01:59:10 INFO]: - NBT Elements successfully loaded
[01:59:10 INFO]: - Text Component Elements successfully loaded
[01:59:10 INFO]: - Advancement Elements successfully loaded
[01:59:10 INFO]: - BossBar Elements successfully loaded
[01:59:10 INFO]: - Bound Elements successfully loaded
[01:59:10 INFO]: - Display Entity elements disabled (Requires Minecraft 1.19.4+)
[01:59:10 INFO]: - Fishing elements successfully loaded
[01:59:10 INFO]: - Game Event Elements successfully loaded
[01:59:10 INFO]: - Particle Elements successfully loaded
[01:59:10 INFO]: - Particle Elements successfully loaded
[01:59:10 INFO]: - RayTrace elements successfully loaded
[01:59:10 INFO]: - Recipe Elements successfully loaded
[01:59:10 INFO]: - Scoreboard Elements successfully loaded
[01:59:10 INFO]: - Scoreboard Objective Elements successfully loaded
[01:59:10 INFO]: - Statistic Elements successfully loaded
[01:59:10 INFO]: - Structure Elements successfully loaded
[01:59:10 INFO]: - Minecraft Tag elements successfully loaded
[01:59:10 INFO]: - Team Elements successfully loaded
[01:59:10 INFO]: - Villager Elements successfully loaded
[01:59:10 INFO]: - Virtual Furnace Elements disabled via config
[01:59:10 INFO]: - World Border Elements successfully loaded
[01:59:10 INFO]: - World Creator Elements successfully loaded
[01:59:10 INFO]: - Checking for update failed!
[01:59:10 INFO]: - Checking for update failed!
[01:59:10 INFO]: - Checking for update failed!
[01:59:10 INFO]: --- [Server Info] ---
[01:59:10 INFO]: Server Version: git-Paper-372 (MC: 1.18.2)
[01:59:10 INFO]: Skript Version: 2.6.3
[01:59:10 INFO]: Skript Addons:
[01:59:10 INFO]: - skript-placeholders v1.5.2
[01:59:10 INFO]: - skript-gui v1.3
[01:59:10 INFO]: - DiSky v4.7.0
[01:59:10 INFO]: - MorkazSk v1.3
[01:59:10 INFO]: - skript-reflect v2.3
[01:59:10 INFO]: - skRayFall v1.9.28
[01:59:10 INFO]: SkBee Version: 2.15.0
[01:59:10 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

### Additional Information

Haven't updated any plugins or anything on my server in about 6 months.

**Comment by ShaneBeee** [comment]
> Load, and an error appears in console and the structures/script itself doesn't work.

What is the error?

**Comment by not-3than** [comment]
Oops haha. Here's the error:
`[02:04:40 INFO]: ethanovich issued server command: /sk reload clearmap
[02:04:40 INFO]: [PlaceholderAPI] Successfully registered expansion: skript [1.5.2]
[02:04:40 ERROR]: #!#! 
[02:04:40 ERROR]: #!#! [Skript] Severe Error:
[02:04:40 ERROR]: #!#! 
[02:04:40 ERROR]: #!#! Something went horribly wrong with Skript.
[02:04:40 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[02:04:40 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[02:04:40 ERROR]: #!#! Here is full list of them:
[02:04:40 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.28 (https://sk.rayfall.net/) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) MorkazSk v1.3 skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) DiSky v4.7.0 SkBee v2.15.0 (https://github.com/ShaneBeee/SkBee) DiscordSRV v1.26.0 (https://github.com/DiscordSRV/DiscordSRV) 
[02:04:40 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[02:04:40 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[02:04:40 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[02:04:40 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[02:04:40 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[02:04:40 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[02:04:40 ERROR]: #!#! 
[02:04:40 ERROR]: #!#! Stack trace:
[02:04:40 ERROR]: #!#! java.lang.NoClassDefFoundError: Could not initialize class com.shanebeestudios.skbee.api.wrapper.PDCWrapper
[02:04:40 ERROR]: #!#!     at SkBee-2.15.0.jar//com.shanebeestudios.skbee.api.structure.StructureWrapper.<init>(StructureWrapper.java:60)
[02:04:40 ERROR]: #!#!     at SkBee-2.15.0.jar//com.shanebeestudios.skbee.api.structure.StructureWrapper.wrap(StructureWrapper.java:44)
[02:04:40 ERROR]: #!#!     at SkBee-2.15.0.jar//com.shanebeestudios.skbee.api.structure.StructureManager.getStructure(StructureManager.java:36)
[02:04:40 ERROR]: #!#!     at SkBee-2.15.0.jar//com.shanebeestudios.skbee.elements.structure.expressions.ExprStructureObject.get(ExprStructureObject.java:60)
[02:04:40 ERROR]: #!#!     at SkBee-2.15.0.jar//com.shanebeestudios.skbee.elements.structure.expressions.ExprStructureObject.get(ExprStructureObject.java:22)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.events.EvtScript.runTrigger(EvtScript.java:88)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.events.EvtScript.register(EvtScript.java:68)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.lambda$loadScript$7(ScriptLoader.java:811)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:834)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[02:04:40 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:04:40 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[02:04:40 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2307)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2118)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[02:04:40 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[02:04:40 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[02:04:40 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:04:40 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[02:04:40 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[02:04:40 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[02:04:40 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[02:04:40 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[02:04:40 ERROR]: #!#! Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: BOOLEAN [in thread "Server thread"]
[02:04:40 ERROR]: #!#!     at SkBee-2.15.0.jar//com.shanebeestudios.skbee.api.wrapper.PDCWrapper.<clinit>(PDCWrapper.java:25)
[02:04:40 ERROR]: #!#!     at SkBee-2.15.0.jar//com.shanebeestudios.skbee.api.structure.StructureWrapper.<init>(StructureWrapper.java:60)
[02:04:40 ERROR]: #!#!     at SkBee-2.15.0.jar//com.shanebeestudios.skbee.api.structure.StructureWrapper.wrap(StructureWrapper.java:44)
[02:04:40 ERROR]: #!#!     at SkBee-2.15.0.jar//com.shanebeestudios.skbee.api.structure.StructureManager.getStructure(StructureManager.java:36)
[02:04:40 ERROR]: #!#!     at SkBee-2.15.0.jar//com.shanebeestudios.skbee.elements.structure.expressions.ExprStructureObject.get(ExprStructureObject.java:60)
[02:04:40 ERROR]: #!#!     at SkBee-2.15.0.jar//com.shanebeestudios.skbee.elements.structure.expressions.ExprStructureObject.get(ExprStructureObject.java:22)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.events.EvtScript.runTrigger(EvtScript.java:88)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.events.EvtScript.register(EvtScript.java:68)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.lambda$loadScript$7(ScriptLoader.java:811)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:834)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[02:04:40 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[02:04:40 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[02:04:40 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1172)
[02:04:40 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[02:04:40 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[02:04:40 ERROR]: #!#! 
[02:04:40 ERROR]: #!#! Version Information:
[02:04:40 ERROR]: #!#!   Skript: 2.6.3
[02:04:40 ERROR]: #!#!     Flavor: skriptlang-github
[02:04:40 ERROR]: #!#!     Date: 00:55:22.847925631
[02:04:40 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[02:04:40 ERROR]: #!#!   Minecraft: 1.18.2
[02:04:40 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[02:04:40 ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic
[02:04:40 ERROR]: #!#! 
[02:04:40 ERROR]: #!#! Server platform: Paper
[02:04:40 ERROR]: #!#! 
[02:04:40 ERROR]: #!#! Current node: null
[02:04:40 ERROR]: #!#! Current item: null
[02:04:40 ERROR]: #!#! 
[02:04:40 ERROR]: #!#! Thread: Server thread
[02:04:40 ERROR]: #!#! 
[02:04:40 ERROR]: #!#! Language: english
[02:04:40 ERROR]: #!#! Link parse mode: STRICT
[02:04:40 ERROR]: #!#! 
[02:04:40 ERROR]: #!#! End of Error.
[02:04:40 ERROR]: #!#! `

**Comment by ShaneBeee** [comment]
thank you
