### ISSUE TITLE
[BUG] Variable return error

### ISSUE THREAD

**Issue by JustIlas69** [ShaneBeee/SkBee#45]
**Describe the bug**
I added an nbt to a sword, but I can't use the variable `%tag ""Enchantments"" of nbt of player's tool%` or `set {_tag} to "Enchantments" tag of nbt of player's tool`.

**To Reproduce**
```
command /givesword:
	trigger:
		give player diamond sword with nbt "{Enchantments:[{id:""sharpness"",lvl:5}]}"

command /nbt:
	trigger:
		broadcast "%tag ""Enchantments"" of nbt of player's held item%"
```

**Expected behavior**
I want to broadcast the tag "Enchantments" of nbt of the sword in chat.

**Screenshots/Errors**
In-game error:
`An internal error occurred while attempting to perform this command`

Console error:
```
[12:44:05 INFO]: [Skript] # /nbt
[12:44:05 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nbt' in plugin Skript v2.2-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: ch/njol/skript/util/slot/Slot
        at tk.shanebee.bee.elements.nbt.expressions.ExprObjectNBT.convert(ExprObjectNBT.java:40) ~[?:?]
        at tk.shanebee.bee.elements.nbt.expressions.ExprObjectNBT.convert(ExprObjectNBT.java:19) ~[?:?]
        at ch.njol.skript.registrations.Converters.convert(Converters.java:305) ~[?:?]
        at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:296) ~[?:?]
        at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:105) ~[?:?]
        at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:56) ~[?:?]
        at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:76) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:61) ~[?:?]
        at tk.shanebee.bee.elements.nbt.expressions.ExprTagOfNBT.get(ExprTagOfNBT.java:58) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) ~[?:?]
        at ch.njol.skript.lang.VariableString.toString(VariableString.java:383) ~[?:?]
        at ch.njol.skript.lang.VariableString.getArray(VariableString.java:488) ~[?:?]
        at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1) ~[?:?]
        at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:69) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:54) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:161) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        ... 15 more
```

**Version Info:**
 - **SkBee Version:** 1.4.6
-  **Skript Version:** skript2.2-SNAPSHOT
 - **Server Version/Platform** Spigot 1.8.8

**Comment by ShaneBeee** [comment]
`Skript Version: skript2.2-SNAPSHOT` 
It appears you're using an unsupported version of Skript.

As stated in the overview of SkBee
```
Requirements:
- Skript - Supported on bensku's fork (tested on 2.5-alpha2)
```

Looking thru the error I see this:
```
Caused by: java.lang.NoClassDefFoundError: ch/njol/skript/util/slot/Slot
```
That class was added I believe in Skript 2.2-dev34
Most 1.8.8 servers use Skript 2.2-dev36, I recommend upgrading to that. 


I just did a test on Skript 2.2-dev36 with your code and here is the result (works fine):
<img width="966" alt="Screen Shot 2020-07-17 at 1 30 21 PM" src="https://user-images.githubusercontent.com/20008482/87828403-b3941300-c831-11ea-8f09-a75491a1557f.png">

**Comment by JustIlas69** [comment]
I can't update Skript to dev36, it gives me this error:
```
[11:11:24] [Server thread/ERROR]: #!#! 
[11:11:24] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[11:11:24] [Server thread/ERROR]: #!#! Could not load RealKeys 1.1.sk
[11:11:24] [Server thread/ERROR]: #!#! 
[11:11:24] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[11:11:24] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:11:24] [Server thread/ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[11:11:24] [Server thread/ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[11:11:24] [Server thread/ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[11:11:24] [Server thread/ERROR]: #!#! nor it will work, unless you switch to supported platform.
[11:11:24] [Server thread/ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[11:11:24] [Server thread/ERROR]: #!#! 
[11:11:24] [Server thread/ERROR]: #!#! Stack trace:
[11:11:24] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for lambda
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1804)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1771)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1519)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:325)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:627)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseFunction(SkriptParser.java:1117)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.parse(EffFunctionCall.java:45)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:46)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:972)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1058)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:621)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:389)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:401)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:331)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:361)
[11:11:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:490)
[11:11:24] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[11:11:24] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[11:11:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[11:11:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[11:11:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[11:11:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[11:11:24] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[11:11:24] [Server thread/ERROR]: #!#! 
[11:11:24] [Server thread/ERROR]: #!#! Version Information:
[11:11:24] [Server thread/ERROR]: #!#!   Skript: 2.2-dev36
[11:11:24] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[11:11:24] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[11:11:24] [Server thread/ERROR]: #!#!   Java: 11.0.7 (OpenJDK 64-Bit Server VM 11.0.7+10)
[11:11:24] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[11:11:24] [Server thread/ERROR]: #!#! 
[11:11:24] [Server thread/ERROR]: #!#! Server platform: Spigot
[11:11:24] [Server thread/ERROR]: #!#! 
[11:11:24] [Server thread/ERROR]: #!#! Current node: realHelp(player) (RealKeys 1.1.sk, line 105)
[11:11:24] [Server thread/ERROR]: #!#! Current item: null
[11:11:24] [Server thread/ERROR]: #!#! 
[11:11:24] [Server thread/ERROR]: #!#! Thread: Server thread
[11:11:24] [Server thread/ERROR]: #!#! 
[11:11:24] [Server thread/ERROR]: #!#! Language: english
[11:11:24] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[11:11:24] [Server thread/ERROR]: #!#! 
[11:11:24] [Server thread/ERROR]: #!#! End of Error.
[11:11:24] [Server thread/ERROR]: #!#! 
```

My script:
```
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#      ██▀███  ▓█████ ▄▄▄       ██▓     ██ ▄█▀▓█████▓██   ██▓  ██████ 
#     ▓██ ▒ ██▒▓█   ▀▒████▄    ▓██▒     ██▄█▒ ▓█   ▀ ▒██  ██▒▒██    ▒ 
#     ▓██ ░▄█ ▒▒███  ▒██  ▀█▄  ▒██░    ▓███▄░ ▒███    ▒██ ██░░ ▓██▄   
#    ▒██▀▀█▄  ▒▓█  ▄░██▄▄▄▄██ ▒██░    ▓██ █▄ ▒▓█  ▄  ░ ▐██▓░  ▒   ██▒
#    ░██▓ ▒██▒░▒████▒▓█   ▓██▒░██████▒▒██▒ █▄░▒████▒ ░ ██▒▓░▒██████▒▒
#    ░ ▒▓ ░▒▓░░░ ▒░ ░▒▒   ▓▒█░░ ▒░▓  ░▒ ▒▒ ▓▒░░ ▒░ ░  ██▒▒▒ ▒ ▒▓▒ ▒ ░
#      ░▒ ░ ▒░ ░ ░  ░ ▒   ▒▒ ░░ ░ ▒  ░░ ░▒ ▒░ ░ ░  ░▓██ ░▒░ ░ ░▒  ░ ░
#      ░░   ░    ░    ░   ▒     ░ ░   ░ ░░ ░    ░   ▒ ▒ ░░  ░  ░  ░  
#       ░        ░  ░     ░  ░    ░  ░░  ░      ░  ░░ ░           ░  
#                                                   ░ ░              
# # # # # # # # # # # # # # # # # # # #
# Credits:                            #     All Rights Reserved
# - Author: @Cattivah (Telegram)      #              /
# - Created for @Skriptify (Telegram) # Tutti i diritti sono riservati
# # # # # # # # # # # # # # # # # # # # 


#-=-################################# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-# █▀▄▀█ █▀▀ █▀ █▀ ▄▀█ █▀▀ █▀▀ █ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-# █░▀░█ ██▄ ▄█ ▄█ █▀█ █▄█ █▄█ █ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-################################# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

options:

	# Messaggio che appare quando blocchi una porta ↓
	door-locked: &2&l»&a&l»&f&l» &7Porta bloccata correttamente!

	# Messaggio che appare quando sblocchi una porta ↓
	door-unlocked: &2&l»&a&l»&f&l» &7Porta sbloccata correttamente!
	
	# Messaggio che appare quando generi una chiave ↓
	give-key: &2&l»&a&l»&f&l» &7Hai ricevuto la chiave senza errori.
	
	# Messaggio che appare quando aggiungi una porta a una chiave ↓
	door-set: &2&l»&a&l»&f&l» &7Hai aggiunto la porta alla chiave.
	
	# Messaggio che appare quando distruggi una porta bloccata ↓
	door-broken: &2&l»&a&l»&f&l» &7Hai distrutto una porta bloccata.

	# Messaggio che appare quando provi a bloccare una porta già bloccata ↓
	door-already-locked: &c&l»&6&l»&e&l» &7Questa porta è già bloccata.

	# Messaggio che appare quando provi a sbloccare una porta non bloccata bloccata ↓
	door-not-locked: &c&l»&6&l»&e&l» &7Questa porta non è bloccata.
	
	# Messaggio che appare quando provi a bloccare una porta di ferro o qualcos'altro che non sia una porta ↓
	not-a-door: &c&l»&6&l»&e&l» &7Devi guardare una porta di legno per eseguire questo comando.
	
	# Messaggio che appare quando provi ad aggiungere la stessa porta a una chiave per due volte ↓
	already-set: &c&l»&6&l»&e&l» &7Hai già aggiunto questa porta alla chiave.
	
	# Messaggio che appare quando esegui un comando dove è necessaria una chiave, ma non la hai in mano ↓
	key-needed: &c&l»&6&l»&e&l» &7Hai bisogno di una chiave per eseguire questo comando.
	
	# Messaggio che appare quando cerchi di aprire o chiudere una porta senza una chiave ↓
	key-needed: &c&l» &7Hai bisogno di una chiave per aprire o chiudere questa porta.
	
	# Messaggio che appare quando cerchi di aprire o chiudere una porta con una chiave sbagliata ↓
	wrong-key: &c&l» &7La chiave non corrisponde con la serratura della porta.
	
	# Messaggio che appare quando provi a rompere una porta bloccata senza il permesso 𝐫𝐤.𝐛𝐫𝐞𝐚𝐤 ↓
	no-perm-break: &c&l» &7Non hai i permessi per distruggere una porta bloccata.
	
	# Messaggio che appare quando esegui il comando senza il permesso 𝐫𝐤.𝐚𝐝𝐦𝐢𝐧 ↓
	no-perm-cmd: &c&l» &7Non hai i permessi per eseguire questo comando.
	
	# Il prefisso nel nome della chiave ↓
	key-prefix: &b&l» &7
	



#-=-##################################################### # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-# █▀▀ █░█ █▄░█ █▀▀ ▀█▀ █ █▀█ █▄░█   █░█ █▀▀ █░░ █▀█ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-# █▀░ █▄█ █░▀█ █▄▄ ░█░ █ █▄█ █░▀█   █▀█ ██▄ █▄▄ █▀▀ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-##################################################### # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

function realHelp(p: player):
	send "" to {_p}
	send "&9&l»&3&l»&b&l» &f&lREALKEYS &7(by realChampo)" to {_p}
	send "&8&l» &f/rk &8&l- &7Ricevi questo messaggio." to {_p}
	send "&8&l» &f/rk lock &8&l- &8- &7Blocca una porta." to {_p}
	send "&8&l» &f/rk unlock &8&l- &7Sblocca una porta." to {_p}
	send "&8&l» &f/rk get &8&l- &7Ricevi la chiave della porta che guardi." to {_p}
	send "&8&l» &f/rk add &8&l- &7Aggiungi una porta alla chiave che impugni." to {_p}
	send "&8&l» &f/rk name &8&l- &7Cambia il nome della chiave." to {_p}
#	send "&8&l» &f/rk lockall &8&l- &7Blocca tutte le porte." to {_p}
#	send "&8&l» &f/rk unlockall &8&l- &7Sblocca tutte le porte." to {_p}
	send "" to {_p}


#-=-######################################################################### # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-# █▀▀ █▀█ █▀▄▀█ ▄▀█ █▄░█ █▀▄ █▀█   █▀█ █▀█ █ █▄░█ █▀▀ █ █▀█ ▄▀█ █░░ █▀▀ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-# █▄▄ █▄█ █░▀░█ █▀█ █░▀█ █▄▀ █▄█   █▀▀ █▀▄ █ █░▀█ █▄▄ █ █▀▀ █▀█ █▄▄ ██▄ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-######################################################################### # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

command /realkey [<string>] [<string>]:
	aliases: realkeys, rk
	permission: rk.admin
	permission message: {@no-perm-cmd}
	trigger:
		if arg 1 is not set:
			realHelp(player)
		else:
			if arg 1 is "lock":
				if "%targeted block%" contains "door" or "gate":
					if "%targeted block%" doesn't contain "iron":
						if {lock.%targeted block's location%} is not set:
							set {lock.%targeted block's location%} to true
							if "%targeted block%" contains "door":
								if "%block at block 1 above targeted block%" contains "door":
									"%block at block 1 under targeted block%" doesn't contain "iron"
									set {lock.%location of block at block 1 above targeted block%} to true
								if "%block at block 1 under targeted block%" contains "door":
									"%block at block 1 under targeted block%" doesn't contain "iron"
									set {lock.%location of block at block 1 under targeted block%} to true
							else:
								send "{@door-locked}"
						else:
							send "{@door-already-locked}"
					else:
						send "{@not-a-door}"
				else:
					send "{@not-a-door}"
			else if arg 1 is "unlock":
				if "%targeted block%" contains "door":
					if "%targeted block%" doesn't contain "iron":
						if {lock.%targeted block's location%} is set:
							delete {lock.%targeted block's location%}
							if "%block at block 1 above targeted block%" contains "door":
								"%block at block 1 under targeted block%" doesn't contain "iron"
								delete {lock.%location of block at block 1 above targeted block%}
							if "%block at block 1 under targeted block%" contains "door":
								"%block at block 1 under targeted block%" doesn't contain "iron"
								delete {lock.%location of block at block 1 under targeted block%}
							send "{@door-unlocked}"
						else:
							send "{@door-not-locked}"
					else:
						send "{@not-a-door}"
				else:
					send "{@not-a-door}"
			else if arg 1 is "get":
				set {_item} to tripwire hook named "{@key-prefix}Chiave"
				add "{Locations:[{id:""sharpness"",lvl:2}]}" to nbt of {_item}
				if {lock.%targeted block's location%} is set:
					add "%targeted block's location%" to {_lore::*}
					if "%block at block 1 above targeted block%" contains "door":
						"%block at block 1 under targeted block%" doesn't contain "iron"
						add "%location of block at block 1 above targeted block%" to {_lore::*}
					if "%block at block 1 under targeted block%" contains "door":
						"%block at block 1 under targeted block%" doesn't contain "iron"
						add "%location of block at block 1 under targeted block%" to {_lore::*}
					give {_item} to player
					send "{@give-key}"
				else:
					send "{@not-a-door}"
			else if arg 1 is "add":
				player's held item is tripwire hook
				if player's held item's name contains "{@key-prefix}":
					if {lock.%targeted block's location%} is set:
						if player's held item's lore contains targeted block's location:
							send "{@already-set}"
							stop
						else:
							set {_lore::*} to player's held item's lore
							set {_linea} to size of {_lore::*} + 1
							if "%block at block 1 above targeted block%" contains "door":
								"%block at block 1 under targeted block%" doesn't contain "iron"
								set line {_linea} of player's tool's lore to "&7%location of block at block 1 above targeted block%"
							if "%block at block 1 under targeted block%" contains "door":
								"%block at block 1 under targeted block%" doesn't contain "iron"
								set line {_linea} of player's tool's lore to "&7%location of block at block 1 under targeted block%"
							add 1 to {_linea}
							set line {_linea} of player's tool's lore to "&7%targeted block's location%"
							send "{@door-set}"
					else:
						send "{@not-a-door}"
				else:
					send "{@key-needed}"
			else if arg 1 is "name":
				player's held item is tripwire hook
				if player's held item's name contains "{@key-prefix}":
					if arg 2 is set:
						set name of player's held item to "{@key-prefix}%colored arg 2%"
					else:
						send "&c&l»&6&l»&e&l» &7Utilizzo: &c/rk name <nome>"
				else:
					send "{@key-needed}"
#			else if arg 1 is "lockall":
#				set {lockall} to true
#				send "&2&l»&a&l»&f&l» &7Hai bloccato tutte le porte. Usa /rk unlockall per annullare."
#			else if arg 1 is "unlockall":
#				set {lockall} to false
#				send "&2&l»&a&l»&f&l» &7Hai sbloccato tutte le porte."
			else:
				realHelp(player)


#-=-######################################## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-# ▄▀█ █░░ ▀█▀ █▀█ █▀▀   █▀▀ █▀█ █▀ █▀▀ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-# █▀█ █▄▄ ░█░ █▀▄ ██▄   █▄▄ █▄█ ▄█ ██▄ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#-=-######################################## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

on right click:
	"%event-block%" contains "door" or "gate"
	"%event-block%" doesn't contain "iron"
	if {lock.%event-block's location%} is set:
		if player's tool is tripwire hook:
			if name of player's held item contains "{@key-prefix}":
				set {_lore} to player's tool's lore
				set {_lore::*} to player's tool's lore
				set {_location} to "&7%location of event-block%"
				if {_lore} or {_lore::*} doesn't contain {_location}:
					cancel event
					send "{@wrong-key}"
			else:
				cancel event
				send "{@key-needed}"
		else:
			cancel event
			send "{@key-needed}"
#	else:
#		if {lockall} is true:
#			if player's tool is tripwire hook:
#				if name of player's held item contains "{@key-prefix}":
#					set {_lore::*} to player's tool's lore
#					set {_location} to "&7%event-block's location%"
#					if {_lore::*} doesn't contain {_location}:
#						cancel event
#						send "{@wrong-key}"
#				else:
#					cancel event
#					send "{@key-needed}"
#			else:
#				cancel event
#				send "{@key-needed}"

on block break:
	if {lock.%event-block's location%} is set:
		if player has permission "rk.break" or "rk.*":
			delete {lock.%event-block's location%}
			if "%block at block 1 above event-block%" contains "door":
				"%block at block 1 under targeted block%" doesn't contain "iron"
				delete {lock.%location of block at block 1 above event-block%}
			if "%block at block 1 under event-block%" contains "door":
				"%block at block 1 under targeted block%" doesn't contain "iron"
				delete {lock.%location of block at block 1 above event-block%}
			send "{@door-broken}" to player
		else:
			send "{@no-perm-break}"

command /givesword:
	trigger:
		give player diamond sword with nbt "{Enchantments:[{id:""sharpness"",lvl:5}]}"

command /nbt:
	trigger:
		broadcast "%tag ""Enchantments"" of nbt of player's held item%"
```
I know this is not the good place to solve this error, but Idk what to do.

**Comment by ShaneBeee** [comment]
That error is not from SkBee, I believe it is caused by SkQuery.

**Comment by JustIlas69** [comment]
Thank you.
I just fixed it by removing SkQuery.
I have another question: is there a way to prevent item with different nbt from stacking in inventory?

**Comment by ShaneBeee** [comment]
> I have another question: is there a way to prevent item with different nbt from stacking in inventory?

I have no clue how it works on ancient server versions, but on newer versions, items that dont match, dont stack. So I really have no clue.
