### ISSUE TITLE
[BUG] Plugin SkBee v1.4.7 generated an exception while executing task 393 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Galajus** [ShaneBeee/SkBee#49]
**Describe the bug**
[Craft Scheduler Thread - 100/WARN]: [SkBee] Plugin SkBee v1.4.7 generated an exception while executing task 393
java.lang.NullPointerException: null
	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:118) ~[patched_1.15.2.jar:git-Paper-369]
	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:107) ~[patched_1.15.2.jar:git-Paper-369]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:308) ~[patched_1.15.2.jar:git-Paper-369]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:271) ~[patched_1.15.2.jar:git-Paper-369]
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:246) ~[patched_1.15.2.jar:git-Paper-369]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39) ~[patched_1.15.2.jar:git-Paper-369]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[patched_1.15.2.jar:git-Paper-369]
	at tk.shanebee.bee.api.virtualfurnace.api.FurnaceManager.saveConfig(FurnaceManager.java:335) ~[?:?]
	at tk.shanebee.bee.api.virtualfurnace.api.FurnaceManager.saveAll(FurnaceManager.java:327) ~[?:?]
	at tk.shanebee.bee.api.virtualfurnace.api.task.FurnaceTick.run(FurnaceTick.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-369]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-369]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-369]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**To Reproduce**
I dont know :/

**Screenshots/Errors**
up

**Version Info:**
 - **SkBee Version:** 1.4.7
-  **Skript Version:** Skript 2.5-alpha5
 - **Server Version/Platform** Paperspigot 369

**Additional context**

**Comment by ShaneBeee** [comment]
Can you please update the plugin and see if the issue still continues

**Comment by ShaneBeee** [comment]
I've done some small edits to SkBee and the VirtualFurnaceAPI, I'm hoping this issue is fixed.

Since I couldn't replicate it myself, could you please try version 1.6.0 and let me know if you still have this issue.

**Comment by ShaneBeee** [comment]
Closing due to lack of response.
