### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by KmanPlayz** [ShaneBeee/SkBee#5]
My Code:
```vb
command /extract [<text>]:
  trigger:
    if arg-1 is set:
      set {_energy} to tag "chargable;energy" of nbt of player's tool
      set {_energy} to "%{_energy}%" parsed as number
      if {_energy} > 0:
        if arg-1 is "all":
          add "{chargable: {energy: 0}}" to nbt of player's tool
          give player shiny light blue dye named "&f&l%(0.9*{_energy})% &b&lCosmic Energy" with lore "", "&6Contains &f&l%(0.9*{_energy})% &b&lCosmic Energy", " &6that is used for enchanting", "", "&7Hint: Drag and drop onto a pickaxe,", " &7sword, or piece of armor to add", " &7to its energy!", "" and "&6Extracted by &f%player%" with NBT "{chargable: {energy: %(0.9*{_energy})%}}"
          send "&6&l(!) &6Extracted &f&l%(0.9*{_energy})% &b&lCosmic Energy" to player
          send "&f&l%(0.1*{_energy})% &b&lCosmic Energy &7was lost in the process." to player
          set {_toolname} to name of player's tool
          send "%{_toolname}% &7has &f&l0 &b&lCosmic Energy &7left on it." to player
          update score with id "%uuid of player%.1" to "  &7(&f0&7/?)" and 1
        else:
          set {_num} to arg-1 parsed as an integer
          if {_num} is set:
            if {_num} <= {_energy}:
              set {_remenergy} to {_energy}-{_num}
              add "{chargable: {energy: %{_remenergy}%}}}" to nbt of player's tool
              give player shiny light blue dye named "&f&l%(0.9*{_num})% &b&lCosmic Energy" with lore "", "&6Contains &f&l%(0.9*{_num})% &b&lCosmic Energy", " &6that is used for enchanting", "", "&7Hint: Drag and drop onto a pickaxe,", " &7sword, or piece of armor to add", " &7to its energy!", "" and "&6Extracted by &f%player%" with NBT "{chargable: {energy: %(0.9*{_num})%}}"
              send "&6&l(!) &6Extracted &f&l%(0.9*{_energy})% &b&lCosmic Energy" to player
              send "&f&l%(0.1*{_num})% &b&lCosmic Energy &7was lost in the process." to player
              set {_toolname} to name of player's tool
              set {_endenergy} to tag "chargable;energy" of nbt of player's tool
              send "%{_toolname}% &7has &f&l%{_endenergy}% &b&lCosmic Energy &7left on it." to player
              update score with id "%uuid of player%.1" to "  &7(&f%{_endenergy}%&7/?)" and 1
            else:
              send "&c&l(!) %name of player's tool% &cdoesn't have enough energy!"
          else:
            send "no" to player
      else:
        send "&dUsage: &f/extract <charge to withdraw>" to player
```

No Reload erros

CONSOLE error:
```
[00:28:32] [Server thread/INFO]: Zerity issued server command: /extract 5
[00:28:32] [Server thread/INFO]: Zerity [d6427876-e941-44f2-a560-041d05840ed5]: /extract 5
[00:28:32] [Server thread/ERROR]: #!#!
[00:28:32] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[00:28:32] [Server thread/ERROR]: #!#!
[00:28:32] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[00:28:32] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:28:32] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:28:32] [Server thread/ERROR]: #!#! Here is full list of them:
[00:28:32] [Server thread/ERROR]: #!#! skRayFall v1.9.20 (https://sk.rayfall.net/) SkBee v1.1.0 skDragon v0.16 skript-yaml v1.3.2 ThatPacketAddon v1.0-BETA.3 (tlatoani.us/thatpacketaddon) SkQuery v3.6.5 Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24/)
[00:28:32] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:28:32] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:28:32] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:28:32] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:28:32] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:28:32] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:28:32] [Server thread/ERROR]: #!#!
[00:28:32] [Server thread/ERROR]: #!#! Stack trace:
[00:28:32] [Server thread/ERROR]: #!#! tk.shanebee.bee.api.NBT.NbtApiException: Unable to parse Malformed Json!
[00:28:32] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBT.NBTContainer.<init>(NBTContainer.java:46)
[00:28:32] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBTApi.addNBT(NBTApi.java:60)
[00:28:32] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprObjectNBT.change(ExprObjectNBT.java:67)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
[00:28:32] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1649)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
[00:28:32] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#! Caused by: tk.shanebee.bee.api.NBT.NbtApiException: Error while calling the method 'parse', loaded: true, Enum: PARSE_NBT
[00:28:32] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBT.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:148)
[00:28:32] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBT.NBTContainer.<init>(NBTContainer.java:44)
[00:28:32] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBTApi.addNBT(NBTApi.java:60)
[00:28:32] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprObjectNBT.change(ExprObjectNBT.java:67)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
[00:28:32] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1649)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
[00:28:32] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#! Caused by: java.lang.reflect.InvocationTargetException
[00:28:32] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBT.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:146)
[00:28:32] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBT.NBTContainer.<init>(NBTContainer.java:44)
[00:28:32] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBTApi.addNBT(NBTApi.java:60)
[00:28:32] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprObjectNBT.change(ExprObjectNBT.java:67)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)
[00:28:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
[00:28:32] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[00:28:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1649)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)
[00:28:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
[00:28:32] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[00:28:32] [Server thread/ERROR]: #!#! Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unexpected trailing data at position 25: ...ergy: 15}}<--[HERE]
[00:28:32] [Server thread/ERROR]: #!#!
[00:28:32] [Server thread/ERROR]: #!#! Version Information:
[00:28:32] [Server thread/ERROR]: #!#!   Skript: 2.5-alpha3 (latest)
[00:28:32] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[00:28:32] [Server thread/ERROR]: #!#!     Date: 2020-03-28
[00:28:32] [Server thread/ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[00:28:32] [Server thread/ERROR]: #!#!   Minecraft: 1.15.2
[00:28:32] [Server thread/ERROR]: #!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
[00:28:32] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[00:28:32] [Server thread/ERROR]: #!#!
[00:28:32] [Server thread/ERROR]: #!#! Server platform: Spigot
[00:28:32] [Server thread/ERROR]: #!#!
[00:28:32] [Server thread/ERROR]: #!#! Current node: null
[00:28:32] [Server thread/ERROR]: #!#! Current item: add "{chargable: {energy: %{_remenergy}(as java.lang.Object)%}}}" to the object nbt of (the tool of the player >> ch.njol.skript.classes.data.DefaultConverters$18@79515450: slot -> itemstack)
[00:28:32] [Server thread/ERROR]: #!#! Current trigger: command /extract (simple event) (Energy.sk, line -1)
[00:28:32] [Server thread/ERROR]: #!#!
[00:28:32] [Server thread/ERROR]: #!#! Thread: Server thread
[00:28:32] [Server thread/ERROR]: #!#!
[00:28:32] [Server thread/ERROR]: #!#! Language: english
[00:28:32] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[00:28:32] [Server thread/ERROR]: #!#!
[00:28:32] [Server thread/ERROR]: #!#! End of Error.
[00:28:32] [Server thread/ERROR]: #!#!
```

**Comment by ShaneBeee** [comment]
You have 2 `{` at the beginning of the NBT and 3 at the end
<img width="477" alt="Screen Shot 2020-04-09 at 3 17 23 AM" src="https://user-images.githubusercontent.com/20008482/78885008-b2707000-7a10-11ea-8324-a3af1901d7bb.png">

**Comment by KmanPlayz** [comment]
Thank you! My bad
