### ISSUE TITLE
[BUG] [SkBee] Plugin SkBee v1.4.11 generated an exception while executing task 406

### ISSUE THREAD

**Issue by Galajus** [ShaneBeee/SkBee#50]
**Describe the bug**
[01:09:24] [Craft Scheduler Thread - 16/WARN]: [SkBee] Plugin SkBee v1.4.11 generated an exception while executing task 406
java.lang.NullPointerException: Nodes must be provided.
	at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28) ~[patched_1.15.2.jar:git-Paper-369]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:164) ~[patched_1.15.2.jar:git-Paper-369]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.15.2.jar:git-Paper-369]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.15.2.jar:git-Paper-369]
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[patched_1.15.2.jar:git-Paper-369]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:307) ~[patched_1.15.2.jar:git-Paper-369]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:271) ~[patched_1.15.2.jar:git-Paper-369]
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:246) ~[patched_1.15.2.jar:git-Paper-369]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39) ~[patched_1.15.2.jar:git-Paper-369]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[patched_1.15.2.jar:git-Paper-369]
	at tk.shanebee.bee.api.virtualfurnace.api.FurnaceManager.saveConfig(FurnaceManager.java:335) ~[?:?]
	at tk.shanebee.bee.api.virtualfurnace.api.FurnaceManager.saveAll(FurnaceManager.java:327) ~[?:?]
	at tk.shanebee.bee.api.virtualfurnace.api.task.FurnaceTick.run(FurnaceTick.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-369]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-369]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-369]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**To Reproduce**
I dont know :/

**Screenshots/Errors**
up

**Version Info:**
 - **SkBee Version:** 1.4.11
-  **Skript Version:** Skript 2.5-alpha5
 - **Server Version/Platform** Paperspigot 369

**Additional context**

**Comment by ShaneBeee** [comment]
Duplicate for #49
