### ISSUE TITLE
[BUG] type int tag for nbt compound creating internal errors

### ISSUE THREAD

**Issue by Henry-Bonikowsky** [ShaneBeee/SkBee#516]
### What happened?

I hope this isn't just because I'm using a different identifier for my tags.. . I'm trying to set an int tag "Stats;Health" for the nbt compound of the player, but it's said that the compound is returned null. 

### Steps to reproduce

1.`command tests:
    trigger:
        set int tag "Stats;Health" of nbt compound of player to 100`
2.
3.

### Expected behavior

internal error message

### SkBee Version

2.18.4

### Server Version

1.19.4

### SkBee Info

Everything is fine here

**Comment by ShaneBeee** [comment]
were you going to provide the error?

**Comment by Merrrical** [comment]
> were you going to provide the error?

Sorry for late reply, I fixed it by replacing "Stats;Health" with "custom;Health", this isn't ideal for me but I can live with it. The error was: `[06:38:29 ERROR]: #!#! 
[06:38:29 ERROR]: #!#! [Skript] Severe Error:
[06:38:29 ERROR]: #!#! 
[06:38:29 ERROR]: #!#! Something went horribly wrong with Skript.
[06:38:29 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[06:38:29 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[06:38:29 ERROR]: #!#! Here is full list of them:
[06:38:29 ERROR]: #!#! SkBee v2.18.4 (https://github.com/ShaneBeee/SkBee) 
[06:38:29 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[06:38:29 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[06:38:29 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[06:38:29 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[06:38:29 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[06:38:29 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[06:38:29 ERROR]: #!#! 
[06:38:29 ERROR]: #!#! Stack trace:
[06:38:29 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "com.shanebeestudios.skbee.api.nbt.NBTCompound.setInteger(String, java.lang.Integer)" because "compound" is null
[06:38:29 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.nbt.NBTApi.setTag(NBTApi.java:280)
[06:38:29 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprTagOfNBT.change(ExprTagOfNBT.java:151)
[06:38:29 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:280)
[06:38:29 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[06:38:29 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[06:38:29 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[06:38:29 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.Delay.lambda$walk$0(Delay.java:107)
[06:38:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[06:38:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[06:38:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[06:38:29 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[06:38:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[06:38:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[06:38:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[06:38:29 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[06:38:29 ERROR]: #!#! 
[06:38:29 ERROR]: #!#! Version Information:
[06:38:29 ERROR]: #!#!   Skript: 2.7.2
[06:38:29 ERROR]: #!#!     Flavor: skriptlang-github
[06:38:29 ERROR]: #!#!     Date: 17:46:44.085781900
[06:38:29 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[06:38:29 ERROR]: #!#!   Minecraft: 1.19.4
[06:38:29 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[06:38:29 ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic
[06:38:29 ERROR]: #!#! 
[06:38:29 ERROR]: #!#! Server platform: Paper
[06:38:29 ERROR]: #!#! 
[06:38:29 ERROR]: #!#! Current node: null
[06:38:29 ERROR]: #!#! Current item: set [[nbttype:int tag]] "Stats;Health" of nbt compound from {_p} (as java.lang.Object) to [[long:100]]
[06:38:29 ERROR]: #!#! Current trigger: function createPlayer (simple event) (join.sk, line 52)
[06:38:29 ERROR]: #!#! 
[06:38:29 ERROR]: #!#! Thread: Server thread
[06:38:29 ERROR]: #!#! 
[06:38:29 ERROR]: #!#! Language: english
[06:38:29 ERROR]: #!#! Link parse mode: DISABLED
[06:38:29 ERROR]: #!#! 
[06:38:29 ERROR]: #!#! End of Error.
[06:38:29 ERROR]: #!#! `

**Comment by ShaneBeee** [comment]
I tried to send you a build on discord, but you didn't reply.
Please try 3.0.0-beta2 to see if the bug was fixed
https://github.com/ShaneBeee/SkBee/releases/tag/3.0.0-beta2

I believe the bug was in NBT-API, which I have updated.... please let me know

**Comment by ShaneBeee** [comment]
closing due to lack of reply and inability to replicate
