### ISSUE TITLE
[BUG] Can't directly get nbt item from a compound tag on player's tool

### ISSUE THREAD

**Issue by cheeezburga** [ShaneBeee/SkBee#521]
### What happened?

I get the following error on SkBee 2.18.4 (and 2.18.3 if that matters) from the line of code below:
```
set {_tool} to nbt item from (compound tag "tool" of nbt of (player's tool))

java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lcom.shanebeestudios.skbee.api.nbt.NBTCompound; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lcom.shanebeestudios.skbee.api.nbt.NBTCompound; is in unnamed module of loader 'SkBee-2.18.4.jar' @7747f217)
```
The full stack trace is below in the Additional Information section of this issue.

Changing the code to the following fixes the error:
```
set {_tool} to (compound tag "tool" of nbt of (player's tool))
set {_tool} to nbt item from {_tool}
```

### Steps to reproduce

1. Set a compound tag on the player's tool to the full nbt of an itemtype (I used `set (compound tag "tool" of nbt of {_i}) to (full nbt of wooden pickaxe)` to set the tag)
2. Try to get the nbt item from that tag on the player's tool (I used `set {_tool} to nbt item from (compound tag "tool" of nbt of (player's tool))` to try to get the tag)

### Expected behavior

I expected to get the item from the compound tag, instead of running into an internal error.

### SkBee Version

2.18.4

### Server Version

Paper 1.20.2

### SkBee Info

```
[11:41:51 INFO]: --- [SkBee Loading Info] ---
[11:41:51 INFO]: - [NBTAPI] Found Spigot: v1_20_R2! Trying to find NMS support
[11:41:51 INFO]: - [NBTAPI] NMS support 'MC1_20_R2' loaded!
[11:41:51 INFO]: - NBT Elements successfully loaded
[11:41:51 INFO]: - Text Component Elements successfully loaded
[11:41:51 INFO]: - Advancement Elements successfully loaded
[11:41:51 INFO]: - BossBar Elements successfully loaded
[11:41:51 INFO]: - Bound Elements successfully loaded
[11:41:51 INFO]: - Display Entity elements successfully loaded
[11:41:51 INFO]: - Fishing elements successfully loaded
[11:41:51 INFO]: - Game Event Elements successfully loaded
[11:41:51 INFO]: - Particle Elements successfully loaded
[11:41:51 INFO]: - RayTrace elements successfully loaded
[11:41:51 INFO]: - Recipe Elements successfully loaded
[11:41:51 INFO]: - Scoreboard Elements successfully loaded
[11:41:51 INFO]: - Scoreboard Objective Elements successfully loaded
[11:41:51 INFO]: - Statistic Elements successfully loaded
[11:41:51 INFO]: - Structure Elements successfully loaded
[11:41:51 INFO]: - Minecraft Tag elements successfully loaded
[11:41:51 INFO]: - Team Elements successfully loaded
[11:41:51 INFO]: - Villager Elements successfully loaded
[11:41:51 INFO]: - Virtual Furnace Elements disabled via config
[11:41:51 INFO]: - World Border Elements successfully loaded
[11:41:51 INFO]: - World Creator Elements successfully loaded
[11:41:51 INFO]: - Plugin is up to date!
[11:41:51 INFO]: --- [Server Info] ---
[11:41:51 INFO]: Server Version: git-Paper-217 (MC: 1.20.2)
[11:41:51 INFO]: Skript Version: 2.7.2
[11:41:51 INFO]: Skript Addons:
[11:41:51 INFO]: - skript-gui v1.3
[11:41:51 INFO]: - skript-reflect v2.3.1-for-Skript-2.7
[11:41:51 INFO]: SkBee Version: 2.18.4
[11:41:51 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee
```

### Additional Information

```
[11:31:30 ERROR]: #!#!
[11:31:30 ERROR]: #!#! [Skript] Severe Error:
[11:31:30 ERROR]: #!#!
[11:31:30 ERROR]: #!#! Something went horribly wrong with Skript.
[11:31:30 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:31:30 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:31:30 ERROR]: #!#! Here is full list of them:
[11:31:30 ERROR]: #!#! skript-reflect v2.3.1-for-Skript-2.7 (https://github.com/TPGamesNL/skript-reflect) skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) SkBee v2.18.4 (https://github.com/ShaneBeee/SkBee)
[11:31:30 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[11:31:30 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:31:30 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:31:30 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:31:30 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:31:30 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[11:31:30 ERROR]: #!#!
[11:31:30 ERROR]: #!#! Stack trace:
[11:31:30 ERROR]: #!#! java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lcom.shanebeestudios.skbee.api.nbt.NBTCompound; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lcom.shanebeestudios.skbee.api.nbt.NBTCompound; is in unnamed module of loader 'SkBee-2.18.4.jar' @7747f217)
[11:31:30 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.elements.nbt.expressions.ExprItemFromNBT.get(ExprItemFromNBT.java:22)
[11:31:30 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:88)
[11:31:30 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
[11:31:30 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:272)
[11:31:30 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[11:31:30 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[11:31:30 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[11:31:30 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[11:31:30 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316)
[11:31:30 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275)
[11:31:30 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286)
[11:31:30 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221)
[11:31:30 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:31:30 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[11:31:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
[11:31:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[11:31:30 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[11:31:30 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[11:31:30 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[11:31:30 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2207)
[11:31:30 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2167)
[11:31:30 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[11:31:30 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[11:31:30 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:31:30 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[11:31:30 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[11:31:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[11:31:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[11:31:30 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[11:31:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[11:31:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[11:31:30 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[11:31:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[11:31:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[11:31:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[11:31:30 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[11:31:30 ERROR]: #!#!
[11:31:30 ERROR]: #!#! Version Information:
[11:31:30 ERROR]: #!#!   Skript: 2.7.2 (latest)
[11:31:30 ERROR]: #!#!     Flavor: skriptlang-github
[11:31:30 ERROR]: #!#!     Date: 17:46:44.085781900
[11:31:30 ERROR]: #!#!   Bukkit: 1.20.2-R0.1-SNAPSHOT
[11:31:30 ERROR]: #!#!   Minecraft: 1.20.2
[11:31:30 ERROR]: #!#!   Java: 17.0.8 (Java HotSpot(TM) 64-Bit Server VM 17.0.8+9-LTS-211)
[11:31:30 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[11:31:30 ERROR]: #!#!
[11:31:30 ERROR]: #!#! Server platform: Paper
[11:31:30 ERROR]: #!#!
[11:31:30 ERROR]: #!#! Current node: null
[11:31:30 ERROR]: #!#! Current item: set {_tool} (as java.lang.Object) to item from nbt [[nbttype:compound tag]] "tool" of nbt compound from  tool of the player
[11:31:30 ERROR]: #!#! Current trigger: command /excavator (simple event) (excavator.sk, line 109)
[11:31:30 ERROR]: #!#!
[11:31:30 ERROR]: #!#! Thread: Server thread
[11:31:30 ERROR]: #!#!
[11:31:30 ERROR]: #!#! Language: english
[11:31:30 ERROR]: #!#! Link parse mode: DISABLED
[11:31:30 ERROR]: #!#!
[11:31:30 ERROR]: #!#! End of Error.
[11:31:30 ERROR]: #!#!
```

**Comment by cheeezburga** [comment]
Seems to be persistent on both beta1 and beta2. I used almost the exact same code and was able to recreate the error with effect commands.

**Comment by ShaneBeee** [comment]
well dammit.
I could have sworn I finally fixed this.
I'm going to mark this as a bug, but also investigating, because I'm really not sure how to fix it.

**Comment by ShaneBeee** [comment]
Im closing this for now.
I've tried over and over again and I can't seem to find anywhere in the code I can possibly fix this.
I have a feeling its an issue with Skript itself.
Everything on SkBee's end seems to make sense.
