### ISSUE TITLE
[BUG] severe issue when following examples provided by docs

### ISSUE THREAD

**Issue by patc4** [ShaneBeee/SkBee#527]
### What happened?

when using "nbt tags of nbt compound of player" it will cause a severe issue on the server.

### Steps to reproduce

use code;
on rightclick holding stick:
	send "t %nbt tags of nbt compound of player%" to player

### Expected behavior

that it tells me the nbt tags of the player.

### SkBee Version

2.18.4

### Server Version

paper 1.20

### SkBee Info

[22:33:47 INFO]: --- [SkBee Loading Info] ---
[22:33:47 INFO]: - [NBTAPI] Found Spigot: v1_20_R1! Trying to find NMS support
[22:33:47 INFO]: - [NBTAPI] NMS support 'MC1_20_R1' loaded!
[22:33:47 INFO]: - NBT Elements successfully loaded
[22:33:47 INFO]: - Text Component Elements successfully loaded
[22:33:47 INFO]: - Advancement Elements successfully loaded
[22:33:47 INFO]: - BossBar Elements successfully loaded
[22:33:47 INFO]: - Bound Elements successfully loaded
[22:33:47 INFO]: - Display Entity elements successfully loaded
[22:33:47 INFO]: - Fishing elements successfully loaded
[22:33:47 INFO]: - Game Event Elements successfully loaded
[22:33:47 INFO]: - Particle Elements successfully loaded
[22:33:47 INFO]: - RayTrace elements successfully loaded
[22:33:47 INFO]: - Recipe Elements successfully loaded
[22:33:47 INFO]: - Scoreboard Elements successfully loaded
[22:33:47 INFO]: - Scoreboard Objective Elements successfully loaded
[22:33:47 INFO]: - Statistic Elements successfully loaded
[22:33:47 INFO]: - Structure Elements successfully loaded
[22:33:47 INFO]: - Minecraft Tag elements successfully loaded
[22:33:47 INFO]: - Team Elements successfully loaded
[22:33:47 INFO]: - Villager Elements successfully loaded
[22:33:47 INFO]: - Virtual Furnace Elements disabled via config
[22:33:47 INFO]: - World Border Elements successfully loaded
[22:33:47 INFO]: - World Creator Elements successfully loaded
[22:33:47 INFO]: - Plugin is up to date!
[22:33:47 INFO]: --- [Server Info] ---
[22:33:47 INFO]: Server Version: git-Paper-17 (MC: 1.20)
[22:33:47 INFO]: Skript Version: 2.7.2
[22:33:47 INFO]: Skript Addons:
[22:33:47 INFO]: SkBee Version: 2.18.4
[22:33:47 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by Fusezion** [comment]
So uh you planning to provide the error?

**Comment by patc4** [comment]
[22:18:35] [Server thread/ERROR]: #!#! 
[22:18:35] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:18:35] [Server thread/ERROR]: #!#! 
[22:18:35] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[22:18:35] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:18:35] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:18:35] [Server thread/ERROR]: #!#! Here is full list of them:
[22:18:35] [Server thread/ERROR]: #!#! SkBee v2.18.4 (https://github.com/ShaneBeee/SkBee) 
[22:18:35] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:18:35] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:18:35] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:18:35] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:18:35] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:18:35] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:18:35] [Server thread/ERROR]: #!#! 
[22:18:35] [Server thread/ERROR]: #!#! Stack trace:
[22:18:35] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[22:18:35] [Server thread/ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[22:18:35] [Server thread/ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[22:18:35] [Server thread/ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[22:18:35] [Server thread/ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[22:18:35] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195)
[22:18:35] [Server thread/ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[22:18:35] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[22:18:35] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[22:18:35] [Server thread/ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[22:18:35] [Server thread/ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:546)
[22:18:35] [Server thread/ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:817)
[22:18:35] [Server thread/ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:795)
[22:18:35] [Server thread/ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:742)
[22:18:35] [Server thread/ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:719)
[22:18:35] [Server thread/ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:79)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.improveBungeeComponentSerialization(ClientboundSystemChatPacket.java:33)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:17)
[22:18:35] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3075)
[22:18:35] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3063)
[22:18:35] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3043)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:154)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:128)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:152)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$5(SkriptEventHandler.java:166)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:163)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[22:18:35] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[22:18:35] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[22:18:35] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:18:35] [Server thread/ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:18:35] [Server thread/ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[22:18:35] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[22:18:35] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:564)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:537)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1960)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
[22:18:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[22:18:35] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[22:18:35] [Server thread/ERROR]: #!#! 
[22:18:35] [Server thread/ERROR]: #!#! Version Information:
[22:18:35] [Server thread/ERROR]: #!#!   Skript: 2.7.2
[22:18:35] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[22:18:35] [Server thread/ERROR]: #!#!     Date: 17:46:44.085781900
[22:18:35] [Server thread/ERROR]: #!#!   Bukkit: 1.20-R0.1-SNAPSHOT
[22:18:35] [Server thread/ERROR]: #!#!   Minecraft: 1.20
[22:18:35] [Server thread/ERROR]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8)
[22:18:35] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:18:35] [Server thread/ERROR]: #!#! 
[22:18:35] [Server thread/ERROR]: #!#! Server platform: Paper
[22:18:35] [Server thread/ERROR]: #!#! 
[22:18:35] [Server thread/ERROR]: #!#! Current node: null
[22:18:35] [Server thread/ERROR]: #!#! Current item: send "t %{_t::*} (as java.lang.Object)%" to the player
[22:18:35] [Server thread/ERROR]: #!#! Current trigger: rightclick holding stick (rightclick holding [[itemtype:stick]]) (wolfe testing\amethyst magic system\wands\casting.sk, line 3)
[22:18:35] [Server thread/ERROR]: #!#! 
[22:18:35] [Server thread/ERROR]: #!#! Thread: Server thread
[22:18:35] [Server thread/ERROR]: #!#! 
[22:18:35] [Server thread/ERROR]: #!#! Language: english
[22:18:35] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[22:18:35] [Server thread/ERROR]: #!#! 
[22:18:35] [Server thread/ERROR]: #!#! End of Error.
[22:18:35] [Server thread/ERROR]: #!#!

**Comment by patc4** [comment]
yes, i do /reload whenever i need to recompile the skripts after an edit

**Comment by Fusezion** [comment]
Have you restarted your server **properly** since then?

**Comment by patc4** [comment]
just did, works fine now.  ended up finding the /skript reload command, apologies for the troubles.
