### ISSUE TITLE
[BUG] Can't load with 3.0

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [ShaneBeee/SkBee#530]
### What happened?

I just updated Skript 2.7.2 > 2.7.3 and Skbee to 3.0, after doing so I only get a loading error. Removing SkBee seems to resolve it, however skbee required scripts don't work anymore obviously.
The error I got is this:
Upon starting and using any sk reload command I just get this error listed below:
```
[21:00:00 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[21:00:00 ERROR]: #!#! Here is full list of them:
[21:00:00 ERROR]: #!#! skript-placeholders v1.5 (https://github.com/APickledWalrus/skript-placeholders) skript-reflect v2.4-dev1 (https://github.com/TPGamesNL/skript-reflect) skript-yaml v1.4.1-for-MC-1.20 skUtilities v0.9.2 (https://tim740.github.io/) SkBee v3.0.0 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.0 (https://forums.skunity.com/resources/skellett.24/)
[21:00:00 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[21:00:00 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[21:00:00 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[21:00:00 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[21:00:00 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[21:00:00 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[21:00:00 ERROR]: #!#!
[21:00:00 ERROR]: #!#! Stack trace:
[21:00:00 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.command.ScriptCommand.unregisterHelp()" because "scriptCommand" is null
[21:00:00 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.unregisterCommand(Commands.java:276)
[21:00:00 ERROR]: #!#!     at Skript.jar//ch.njol.skript.structures.StructCommand.unload(StructCommand.java:325)
[21:00:00 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:830)
[21:00:00 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:140)
[21:00:00 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:00:00 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[21:00:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:985)
[21:00:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:970)
[21:00:00 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:500)
[21:00:00 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[21:00:00 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[21:00:00 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[21:00:00 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[21:00:00 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[21:00:00 ERROR]: #!#!
[21:00:00 ERROR]: #!#! Version Information:
[21:00:00 ERROR]: #!#!   Skript: 2.7.3 (latest)
[21:00:00 ERROR]: #!#!     Flavor: skriptlang-github
[21:00:00 ERROR]: #!#!     Date: 15:29:36.833117400
[21:00:00 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[21:00:00 ERROR]: #!#!   Minecraft: 1.20.1
[21:00:00 ERROR]: #!#!   Java: 17.0.6 (Java HotSpot(TM) 64-Bit Server VM 17.0.6+9-LTS-190)
[21:00:00 ERROR]: #!#!   OS: Linux amd64 5.4.0-90-generic
[21:00:00 ERROR]: #!#!
[21:00:00 ERROR]: #!#! Server platform: Paper
[21:00:00 ERROR]: #!#!
[21:00:00 ERROR]: #!#! Current node: null
[21:00:00 ERROR]: #!#! Current item: null
[21:00:00 ERROR]: #!#!
[21:00:00 ERROR]: #!#! Thread: Server thread
[21:00:00 ERROR]: #!#!
[21:00:00 ERROR]: #!#! Language: english
[21:00:00 ERROR]: #!#! Link parse mode: DISABLED
[21:00:00 ERROR]: #!#!
[21:00:00 ERROR]: #!#! End of Error.
[21:00:00 ERROR]: #!#!
```

Here are the issues which come up without skbee (in case one of them is involved)
```
[21:04:58 INFO]: Line 70: (entity.sk)
[21:04:58 INFO]:     There's no loop that matches 'loop-entity does not have tag "Owner"'
[21:04:58 INFO]:     Line: if nbt compound of loop-entity does not have tag "Owner":
[21:04:58 INFO]:
[21:04:58 INFO]: Line 77: (entity.sk)
[21:04:58 INFO]:     There's no loop that matches 'loop-entity does not have tag "Owner"'
[21:04:58 INFO]:     Line: if nbt compound of loop-entity does not have tag "Owner":
[21:04:58 INFO]:
[21:04:58 INFO]: Line 339: (util.sk)
[21:04:58 INFO]:     Can't understand this condition/effect: draw 1 of vibration using vibration({_loc2}, 1 second) at {_loc1}
[21:04:58 INFO]:     Line: draw 1 of vibration using vibration({_loc2}, 1 second) at {_loc1}
[21:04:58 INFO]:
```

### Steps to reproduce

1. Download my used plugins
2. Eventually make a random script with used actions I listed above.
3. 

### Expected behavior

To load without issues and be usable.

### SkBee Version

3.0.0

### Server Version

1.20.1 #194

### SkBee Info

> skbee info
[21:10:53 INFO]: --- [SkBee Loading Info] ---
[21:10:53 INFO]: - [NBTAPI] Found Spigot: v1_20_R1! Trying to find NMS support
[21:10:53 INFO]: - [NBTAPI] NMS support 'MC1_20_R1' loaded!
[21:10:53 INFO]: - NBT Elements successfully loaded
[21:10:53 INFO]: - Text Component Elements disabled via config
[21:10:53 INFO]: - Advancement Elements successfully loaded
[21:10:53 INFO]: - BossBar Elements disabled
[21:10:53 INFO]: - It appears another Skript addon may have registered BossBar syntax.
[21:10:53 INFO]: - To use SkBee BossBars, please remove the addon which has registered BossBars already.
[21:10:53 INFO]: - Bound Elements disabled via config
[21:10:53 INFO]: - Display Entity elements successfully loaded
[21:10:53 INFO]: - Fishing elements successfully loaded
[21:10:53 INFO]: - Game Event Elements successfully loaded
[21:10:53 INFO]: - Particle Elements successfully loaded
[21:10:53 INFO]: - RayTrace elements successfully loaded
[21:10:53 INFO]: - Recipe Elements successfully loaded
[21:10:53 INFO]: - Scoreboard Elements disabled via config
[21:10:53 INFO]: - Scoreboard Objective Elements disabled
[21:10:53 INFO]: - It appears another Skript addon may have registered Scoreboard Objective syntax.
[21:10:53 INFO]: - To use SkBee Scoreboard Objectives, please remove the addon which has registered Scoreboard Objective already.
[21:10:53 INFO]: - Statistic Elements successfully loaded
[21:10:53 INFO]: - Structure Elements disabled via config
[21:10:53 INFO]: - Minecraft Tag elements successfully loaded
[21:10:53 INFO]: - Team Elements disabled
[21:10:53 INFO]: - It appears another Skript addon may have registered Team syntax.
[21:10:53 INFO]: - To use SkBee Teams, please remove the addon which has registered Teams already.
[21:10:53 INFO]: - Villager Elements successfully loaded
[21:10:53 INFO]: - Virtual Furnace Elements disabled via config
[21:10:53 INFO]: - World Border Elements successfully loaded
[21:10:53 INFO]: - World Creator Elements disabled via config
[21:10:53 INFO]: - Plugin is up to date!
[21:10:53 INFO]: --- [Server Info] ---
[21:10:53 INFO]: Server Version: git-Paper-194 (MC: 1.20.1)
[21:10:53 INFO]: Skript Version: 2.7.3
[21:10:53 INFO]: Skript Addons:
[21:10:53 INFO]: - skript-placeholders v1.5
[21:10:53 INFO]: - Skellett v2.0.0
[21:10:53 INFO]: - skript-yaml v1.4.1-for-MC-1.20
[21:10:53 INFO]: - skUtilities v0.9.2
[21:10:53 INFO]: - skript-reflect v2.4-dev1
[21:10:53 INFO]: SkBee Version: 3.0.0
[21:10:53 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

### Additional Information

I first thought it was related to the new skript version 2.7.3, but as stated it seems to work when removing SkBee, so yeah.. 
Thanks for looking into it!:)

**Comment by ILikeOrangeJuice** [comment]
Proper stop and start again.

**Comment by ShaneBeee** [comment]
Please try updating to MC 1.20.2, as 1.20.1 is no longer supported

**Comment by ILikeOrangeJuice** [comment]
Mhm, I have to see about that, as other major Plugins are not rdy yet, unfortunately, I also tried the update on my hub, same issue appeared and tried it on another network with 6 Servers (all the same 1.19.1 version), but there it was fine, so it was weird anyway. Using the previous Skbee Version seems to work fine. 
I try to update asap and come back if the error persists. But still weird it works on some servers and some not :x.

**Comment by ILikeOrangeJuice** [comment]
I updated to 1.20.2, latest relase from paper, still the same error persists with SkBee 3.0.0.

**Comment by ShaneBeee** [comment]
I've been running this build on my server for weeks, and never had any error like this.
Its definitely an odd one.

That said, the only other addons I have is Skript-Reflect.
I recommend trying to remove Skellett and maybe skUtilities. (just to test)
I feel like something is clashing here.

**Comment by ILikeOrangeJuice** [comment]
It seems to indeed load without the Skellett plugin, tbh it was just used for centered text anyway. Glad to have this resolved for now! Thanks :)

**Comment by Fusezion** [comment]
Gonna go ahead and say its likely not an skbee issie but some form of conflict with skellet so gonna close this issue
