### ISSUE TITLE
[BUG] Can't load when using 3.0

### ISSUE THREAD

**Issue by samlight234** [ShaneBeee/SkBee#531]
### What happened?

Whenever I try using v3.0 I get this error (I have nothing but Skript 2.7.3 installed)
```
java.lang.NoSuchMethodError: 'org.bukkit.potion.PotionBrewer org.bukkit.Bukkit.getPotionBrewer()'
	at com.shanebeestudios.skbee.elements.recipe.sections.SecRecipeBrewing.<clinit>(SecRecipeBrewing.java:55) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.lang.Class.forName(Class.java:513) ~[?:?]
	at ch.njol.skript.util.Utils.getClasses(Utils.java:201) ~[?:?]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82) ~[?:?]
	at com.shanebeestudios.skbee.AddonLoader.loadRecipeElements(AddonLoader.java:170) ~[?:?]
	at com.shanebeestudios.skbee.AddonLoader.loadSkriptElements(AddonLoader.java:111) ~[?:?]
	at com.shanebeestudios.skbee.AddonLoader.canLoadPlugin(AddonLoader.java:87) ~[?:?]
	at com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:52) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3948-Spigot-e3c3140-e54f39a]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3948-Spigot-e3c3140-e54f39a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3948-Spigot-e3c3140-e54f39a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3948-Spigot-e3c3140-e54f39a]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3948-Spigot-e3c3140-e54f39a]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3948-Spigot-e3c3140-e54f39a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3948-Spigot-e3c3140-e54f39a]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps to reproduce

1. setup 1.20.2 Spigot server (using the BuildTools.jar)
2. add Skript 2.7.3 and Skbee 3.0 to plugins folder
3. run server using the spigot-1.20.2.jar

### Expected behavior

For it to load without issues

### SkBee Version

3.0.0

### Server Version

1.20.2

### SkBee Info

nothing happened after I ran it so I will just put the info before the error here
[12:53:31 INFO]: [Skript] Enabling Skript v2.7.3
[12:53:32 INFO]: [Skript] You're currently running the latest stable version of Skript.
[12:53:38 INFO]: [Skript] Loaded 232530 aliases in 6355ms
[12:53:38 INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
[12:53:38 INFO]: [SkBee] Enabling SkBee v3.0.0
[12:53:38 INFO]: [SkBee] Loading NBTApi...
[12:53:38 INFO]: [SkBee] [NBTAPI] Found Spigot: v1_20_R2! Trying to find NMS support
[12:53:38 INFO]: [SkBee] [NBTAPI] NMS support 'MC1_20_R2' loaded!
[12:53:38 INFO]: [SkBee] Successfully loaded NBTApi!
[12:53:38 INFO]: [SkBee] NBT Elements successfully loaded
[12:53:38 INFO]: [SkBee] Text Component Elements disabled
[12:53:38 INFO]: [SkBee] - Text components require a PaperMC server.
[12:53:38 INFO]: [SkBee] Advancement Elements successfully loaded
[12:53:38 INFO]: [SkBee] BossBar Elements successfully loaded
[12:53:38 INFO]: [SkBee] Bound Elements successfully loaded
[12:53:38 INFO]: [SkBee] Display Entity elements successfully loaded
[12:53:38 INFO]: [SkBee] Fishing elements successfully loaded
[12:53:38 INFO]: [SkBee] Game Event Elements successfully loaded
[12:53:38 INFO]: [SkBee] Particle Elements successfully loaded
[12:53:38 INFO]: [SkBee] RayTrace elements successfully loaded

### Additional Information

It works fine without it or using v2.18.4 of Skbee I'm using a spigot server

**Comment by ShaneBeee** [comment]
looks like I forgot a check for that, oops!

**Comment by samlight234** [comment]
Is there anything I have to do or no

**Comment by ShaneBeee** [comment]
nope, its a bug I have to fix. Its code that requires paper, and I apparently didn't do a paper check.
