### ISSUE TITLE
[Skript] Severe Error

### ISSUE THREAD

**Issue by XviEpe** [ShaneBeee/SkBee#547]
### What happened?

I joined my server and console says:
```
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! [Skript] Severe Error:
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[17:57:17 ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[17:57:17 ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Stack trace:
[17:57:17 ERROR]: #!#! java.lang.RuntimeException: Unable to update scoreboard lines
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.fastboard.FastBoardBase.updateLines(FastBoardBase.java:350)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.scoreboard.FastBoardWrapper.updateLines(FastBoardWrapper.java:104)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.scoreboard.FastBoardWrapper.setLine(FastBoardWrapper.java:45)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.elements.scoreboard.expressions.ExprScoreboardLine.change(ExprScoreboardLine.java:93)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[17:57:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:57:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1639)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1518)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1214)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:57:17 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[17:57:17 ERROR]: #!#! Caused by: java.lang.IllegalAccessException: Can not set final java.lang.String field net.minecraft.network.protocol.game.PacketPlayOutScoreboardScore.a to java.lang.String
[17:57:17 ERROR]: #!#!     at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[17:57:17 ERROR]: #!#!     at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[17:57:17 ERROR]: #!#!     at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
[17:57:17 ERROR]: #!#!     at java.base/java.lang.reflect.Field.set(Field.java:799)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.fastboard.FastBoardBase.setField(FastBoardBase.java:559)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.fastboard.FastBoardBase.sendScorePacket(FastBoardBase.java:475)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.fastboard.FastBoardBase.updateLines(FastBoardBase.java:338)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.scoreboard.FastBoardWrapper.updateLines(FastBoardWrapper.java:104)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.scoreboard.FastBoardWrapper.setLine(FastBoardWrapper.java:45)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.elements.scoreboard.expressions.ExprScoreboardLine.change(ExprScoreboardLine.java:93)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[17:57:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:57:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1639)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1518)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1214)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:57:17 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Version Information:
[17:57:17 ERROR]: #!#!   Skript: 2.6.4 (OUTDATED)
[17:57:17 ERROR]: #!#!     Flavor: skriptlang-github
[17:57:17 ERROR]: #!#!     Date: 17:14:25.041218900
[17:57:17 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[17:57:17 ERROR]: #!#!   Minecraft: 1.20.4
[17:57:17 ERROR]: #!#!   Java: 17.0.9 (OpenJDK 64-Bit Server VM 17.0.9+9)
[17:57:17 ERROR]: #!#!   OS: Linux amd64 4.19.0-24-amd64
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Server platform: Paper
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Current node: null
[17:57:17 ERROR]: #!#! Current item: set line [[long:15]] of scoreboard[s] of {_P} (as org.bukkit.entity.Player) to " "
[17:57:17 ERROR]: #!#! Current trigger: function SB (simple event) (scoreboard.sk, line 10)
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Thread: Server thread
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Language: english
[17:57:17 ERROR]: #!#! Link parse mode: DISABLED
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! End of Error.
[17:57:17 ERROR]: #!#!
```

### Steps to reproduce

I joined my server

I went to report the skript to their github, but I was told that it was due to skbee

### Expected behavior

I don't know

### SkBee Version

2.18.4

### Server Version

Paper 1.20.4

### SkBee Info

```
[01:28:12 INFO]: --- [SkBee Loading Info] ---
[01:28:12 INFO]: - [NBTAPI] Found Spigot: v1_20_R3! Trying to find NMS support
[01:28:12 INFO]: - NBT Elements DISABLED!
[01:28:12 INFO]: -  - Your server version [1.20.4] is not currently supported by the NBT-API
[01:28:12 INFO]: -  - This is not a bug!
[01:28:12 INFO]: -  - NBT elements will resume once the API is updated to work with [1.20.4]
[01:28:12 INFO]: - Text Component Elements successfully loaded
[01:28:12 INFO]: - Advancement Elements successfully loaded
[01:28:12 INFO]: - BossBar Elements disabled
[01:28:12 INFO]: - It appears another Skript addon may have registered BossBar syntax.
[01:28:12 INFO]: - To use SkBee BossBars, please remove the addon which has registered BossBars already.
[01:28:12 INFO]: - Bound Elements successfully loaded
[01:28:12 INFO]: - Display Entity elements successfully loaded
[01:28:12 INFO]: - It looks like another addon registered 'fishingstate' already.
[01:28:12 INFO]: - You may have to use their fishing states in SkBee's 'Fish Event State' expression.
[01:28:12 INFO]: - Fishing elements successfully loaded
[01:28:12 INFO]: - Game Event Elements successfully loaded
[01:28:12 INFO]: - Particle Elements successfully loaded
[01:28:12 INFO]: - RayTrace elements successfully loaded
[01:28:12 INFO]: - Recipe Elements successfully loaded
[01:28:12 INFO]: - Scoreboard Elements successfully loaded
[01:28:12 INFO]: - Scoreboard Objective Elements disabled
[01:28:12 INFO]: - It appears another Skript addon may have registered Scoreboard Objective syntax.
[01:28:12 INFO]: - To use SkBee Scoreboard Objectives, please remove the addon which has registered Scoreboard Objective already.
[01:28:12 INFO]: - Statistic Elements successfully loaded
[01:28:12 INFO]: - Structure Elements successfully loaded
[01:28:12 INFO]: - Minecraft Tag elements successfully loaded
[01:28:12 INFO]: - Team Elements disabled
[01:28:12 INFO]: - It appears another Skript addon may have registered Team syntax.
[01:28:12 INFO]: - To use SkBee Teams, please remove the addon which has registered Teams already.
[01:28:12 INFO]: - Villager Elements successfully loaded
[01:28:12 INFO]: - Virtual Furnace Elements disabled via config
[01:28:12 INFO]: - World Border Elements successfully loaded
[01:28:12 INFO]: - World Creator Elements successfully loaded
[01:28:12 INFO]: - Plugin is not up to date!
[01:28:12 INFO]: -  - Current version: v2.18.4
[01:28:12 INFO]: -  - Available update: v3.0.2
[01:28:12 INFO]: -  - Download available at: https://github.com/ShaneBeee/SkBee/releases
[01:28:12 INFO]: --- [Server Info] ---
[01:28:12 INFO]: Server Version: git-Paper-365 (MC: 1.20.4)
[01:28:12 INFO]: Skript Version: 2.6.4
[01:28:12 INFO]: Skript Addons:
[01:28:12 INFO]: - Skellett v2.0.9
[01:28:12 INFO]: - skript-gui v1.3
[01:28:12 INFO]: - skRayFall v1.9.28
[01:28:12 INFO]: - SharpSK v1.6.3
[01:28:12 INFO]: SkBee Version: 2.18.4
[01:28:12 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee
```

**Comment by ShaneBeee** [comment]
outdated versions of SkBee are not supported
