### ISSUE TITLE
[BUG] 3.1.0 Update breaks loading NBTs from files

### ISSUE THREAD

**Issue by Prorickey** [ShaneBeee/SkBee#552]
### What happened?

After updating to the latest version of SkBee, I got an error in console when starting the server and my nbts in files wouldn't save or load. 

### Steps to reproduce

nbt compound of file "whatever.dat"

### Expected behavior

I would expect no errors in console and for my nbts to work. 

### SkBee Version

3.1.0

### Server Version

Paper 1.20.4

### SkBee Info

SkBee 3.1.0

### Additional Information

```[14:33:10] [Server thread/ERROR]: #!#! Stack trace:
[14:33:10] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:142)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.UnparsedLiteral.getArray(UnparsedLiteral.java:162)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:88)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:94)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.events.EvtScript.runTrigger(EvtScript.java:88)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.events.EvtScript.postLoad(EvtScript.java:61)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.structures.StructEvent.postLoad(StructEvent.java:70)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$9(ScriptLoader.java:589)
[14:33:10] [Server thread/ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
[14:33:10] [Server thread/ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:581)
[14:33:10] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[14:33:10] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[14:33:10] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:511)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[14:33:10] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:836)
[14:33:10] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[14:33:10] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[14:33:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1143)
[14:33:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[14:33:10] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)```

**Comment by ShaneBeee** [comment]
Thanks for reporting.
This was reported to me earlier on discord, and I fixed the issue, and did a silent update (I just updated the jar)
so just re-download the jar and you should be good to go
