### ISSUE TITLE
[BUG] Scoreboard Number Objectives Expression Throws Exception

### ISSUE THREAD

**Issue by EquipableMC** [ShaneBeee/SkBee#584]
### What happened?

In the latest release (3.4.0), You added number format for objectives, well it throws a huge error in console. Read addition information for the error.

### Steps to reproduce

1. Add SkBee to your server
2. Load it
3. Thats it, thats really it.

### Expected behavior

N/A

### SkBee Version

3.4.0

### Server Version

Paper 1.19.4

### SkBee Info
```
[19:54:11 INFO]: --- [Server Info] ---
[19:54:11 INFO]: Server Version: git-Paper-550 (MC: 1.19.4)
[19:54:11 INFO]: Skript Version: 2.8.3
[19:54:11 INFO]: Skript Addons:
[19:54:11 INFO]: - skript-placeholders v1.6.0
[19:54:11 INFO]: - PoaSK v3.3.2
[19:54:11 INFO]: - skript-gui v1.3
[19:54:11 INFO]: - DiSky v4.12.2-beta1
[19:54:11 INFO]: - skript-reflect v2.4
[19:54:11 INFO]: - SkLogs v1.1.1
[19:54:11 INFO]: SkBee Version: 3.4.0
[19:54:11 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee
```

### Additional Information
```
[19:31:19 ERROR]: #!#! 
[19:31:19 ERROR]: #!#! [Skript] Severe Error:
[19:31:19 ERROR]: #!#! Cannot load class com.shanebeestudios.skbee.elements.objective.expressions.ExprObjNumberFormat
[19:31:19 ERROR]: #!#! 
[19:31:19 ERROR]: #!#! Something went horribly wrong with Skript.
[19:31:19 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[19:31:19 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[19:31:19 ERROR]: #!#! Following plugins are probably related to this error in some way:
[19:31:19 ERROR]: #!#! SkBee (https://github.com/ShaneBeee/SkBee) 
[19:31:19 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[19:31:19 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[19:31:19 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[19:31:19 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[19:31:19 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[19:31:19 ERROR]: #!#! 
[19:31:19 ERROR]: #!#! Stack trace:
[19:31:19 ERROR]: #!#! java.lang.NoClassDefFoundError: io/papermc/paper/scoreboard/numbers/NumberFormat
[19:31:19 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[19:31:19 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
[19:31:19 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.util.Utils.getClasses(Utils.java:201)
[19:31:19 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82)
[19:31:19 ERROR]: #!#!     at SkBee-3.4.0.jar//com.shanebeestudios.skbee.AddonLoader.loadScoreboardObjectiveElements(AddonLoader.java:208)
[19:31:19 ERROR]: #!#!     at SkBee-3.4.0.jar//com.shanebeestudios.skbee.AddonLoader.loadSkriptElements(AddonLoader.java:115)
[19:31:19 ERROR]: #!#!     at SkBee-3.4.0.jar//com.shanebeestudios.skbee.AddonLoader.canLoadPlugin(AddonLoader.java:88)
[19:31:19 ERROR]: #!#!     at SkBee-3.4.0.jar//com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:53)
[19:31:19 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[19:31:19 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[19:31:19 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[19:31:19 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[19:31:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
[19:31:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
[19:31:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[19:31:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[19:31:19 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[19:31:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[19:31:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[19:31:19 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[19:31:19 ERROR]: #!#! Caused by: java.lang.ClassNotFoundException: io.papermc.paper.scoreboard.numbers.NumberFormat
[19:31:19 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[19:31:19 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[19:31:19 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[19:31:19 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[19:31:19 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
[19:31:19 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.util.Utils.getClasses(Utils.java:201)
[19:31:19 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82)
[19:31:19 ERROR]: #!#!     at SkBee-3.4.0.jar//com.shanebeestudios.skbee.AddonLoader.loadScoreboardObjectiveElements(AddonLoader.java:208)
[19:31:19 ERROR]: #!#!     at SkBee-3.4.0.jar//com.shanebeestudios.skbee.AddonLoader.loadSkriptElements(AddonLoader.java:115)
[19:31:19 ERROR]: #!#!     at SkBee-3.4.0.jar//com.shanebeestudios.skbee.AddonLoader.canLoadPlugin(AddonLoader.java:88)
[19:31:19 ERROR]: #!#!     at SkBee-3.4.0.jar//com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:53)
[19:31:19 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[19:31:19 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[19:31:19 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[19:31:19 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[19:31:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
[19:31:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
[19:31:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[19:31:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[19:31:19 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[19:31:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[19:31:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[19:31:19 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[19:31:19 ERROR]: #!#! 
[19:31:19 ERROR]: #!#! Version Information:
[19:31:19 ERROR]: #!#!   Skript: 2.8.3 (latest)
[19:31:19 ERROR]: #!#!     Flavor: skriptlang-github
[19:31:19 ERROR]: #!#!     Date: 16:23:04.254419600
[19:31:19 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[19:31:19 ERROR]: #!#!   Minecraft: 1.19.4
[19:31:19 ERROR]: #!#!   Java: 17.0.10 (OpenJDK 64-Bit Server VM 17.0.10+7)
[19:31:19 ERROR]: #!#!   OS: Linux amd64 5.15.0-91-generic
[19:31:19 ERROR]: #!#! 
[19:31:19 ERROR]: #!#! Server platform: Paper
[19:31:19 ERROR]: #!#! 
[19:31:19 ERROR]: #!#! Current node: null
[19:31:19 ERROR]: #!#! Current item: null
[19:31:19 ERROR]: #!#! 
[19:31:19 ERROR]: #!#! Thread: Server thread
[19:31:19 ERROR]: #!#! 
[19:31:19 ERROR]: #!#! Language: english
[19:31:19 ERROR]: #!#! Link parse mode: DISABLED
[19:31:19 ERROR]: #!#! 
[19:31:19 ERROR]: #!#! End of Error.
[19:31:19 ERROR]: #!#!
```

**Comment by Fusezion** [comment]
Seems like we forgot to add a class exists check for this
