### ISSUE TITLE
[BUG] only 1 player teleported and console error

### ISSUE THREAD

**Issue by Slevi2009** [ShaneBeee/SkBee#620]
### What happened?

The `teleport {_p} to {map%{_map}%.team.%{_c}%}`  line was skipped and Skript sent an error in the console

### Steps to reproduce

1. Skript: 		
```
function startbedwars(mode: text, map: number):
	if {_mode} is "solos":
		set {_teamroll::*} to {bedwars.queue%{_map}%::*}
		delete {bedwars.queue%{_map}%::*}

		loop {@solosmaxplayers} times:
			add 1 to {_c}
			set {_p} to first element out of {_teamroll::*}
			remove {_p} from {bedwars.solos.queue::*}
			remove {_p} from {_teamroll::*}
			add {_p} to {_players::*}
			execute console command "mvtp %{_p}% %{_map}%"
			wait 10 ticks
			teleport {_p} to {map%{_map}%.team.%{_c}%}
```
2. just start the game with this function

### Expected behavior

The Skript will work

### SkBee Version

4.4.3

### Server Version

Purpur 1.20.1

### SkBee Info

[15:19:27 INFO]: --- [Server Info] ---
[15:19:27 INFO]: Server Version: git-Purpur-2062 (MC: 1.20.1)
[15:19:27 INFO]: Skript Version: 2.8.4
[15:19:27 INFO]: Skript Addons:
[15:19:27 INFO]: SkBee Version: 3.4.3
[15:19:27 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

### Additional Information

console error:

```
[15:16:39 ERROR]: #!#!
[15:16:39 ERROR]: #!#! [Skript] Severe Error:
[15:16:39 ERROR]: #!#!
[15:16:39 ERROR]: #!#! Something went horribly wrong with Skript.
[15:16:39 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:16:39 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:16:39 ERROR]: #!#! Here is full list of them:
[15:16:39 ERROR]: #!#! SkBee v3.4.3 (https://github.com/ShaneBeee/SkBee)
[15:16:39 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:16:39 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:16:39 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:16:39 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:16:39 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:16:39 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:16:39 ERROR]: #!#!
[15:16:39 ERROR]: #!#! Stack trace:
[15:16:39 ERROR]: #!#! java.lang.IllegalArgumentException: World unloaded
[15:16:39 ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[15:16:39 ERROR]: #!#!     at org.bukkit.Location.getWorld(Location.java:112)
[15:16:39 ERROR]: #!#!     at Skript (2).jar//ch.njol.skript.paperlib.PaperLib.getChunkAtAsync(PaperLib.java:105)
[15:16:39 ERROR]: #!#!     at Skript (2).jar//ch.njol.skript.effects.EffTeleport.walk(EffTeleport.java:132)
[15:16:39 ERROR]: #!#!     at Skript (2).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:16:39 ERROR]: #!#!     at Skript (2).jar//ch.njol.skript.effects.Delay.lambda$walk$0(Delay.java:107)
[15:16:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:16:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[15:16:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1506)
[15:16:39 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[15:16:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1420)
[15:16:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1191)
[15:16:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[15:16:39 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:842)
[15:16:39 ERROR]: #!#!
[15:16:39 ERROR]: #!#! Version Information:
[15:16:39 ERROR]: #!#!   Skript: 2.8.4 (latest)
[15:16:39 ERROR]: #!#!     Flavor: skriptlang-github
[15:16:39 ERROR]: #!#!     Date: 11:03:52.948789700
[15:16:39 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[15:16:39 ERROR]: #!#!   Minecraft: 1.20.1
[15:16:39 ERROR]: #!#!   Java: 17.0.10 (Java HotSpot(TM) 64-Bit Server VM 17.0.10+11-LTS-240)
[15:16:39 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:16:39 ERROR]: #!#!
[15:16:39 ERROR]: #!#! Server platform: Paper
[15:16:39 ERROR]: #!#!
[15:16:39 ERROR]: #!#! Current node: null
[15:16:39 ERROR]: #!#! Current item: teleport {_p} (as org.bukkit.entity.Entity) to [[direction:at]] {map%{_map} (as java.lang.Object)%.team.%{_c} (as java.lang.Object)%} (as org.bukkit.Location)
[15:16:39 ERROR]: #!#! Current trigger: function startbedwars (simple event) (bedwars.sk, line 182)
[15:16:39 ERROR]: #!#!
[15:16:39 ERROR]: #!#! Thread: Server thread
[15:16:39 ERROR]: #!#!
[15:16:39 ERROR]: #!#! Language: english
[15:16:39 ERROR]: #!#! Link parse mode: DISABLED
[15:16:39 ERROR]: #!#!
[15:16:39 ERROR]: #!#! End of Error.
[15:16:39 ERROR]: #!#!
```

**Comment by ShaneBeee** [comment]
Im confused, what does this have to do with skbee?

**Comment by Slevi2009** [comment]
The error message said "It looks like you are using some plugin(s) that alter how Skript works (addons)."
And the only installed addon is SkBee

**Comment by ShaneBeee** [comment]
Yeah the error comes from Skript, its not related to SkBee at all

**Comment by Slevi2009** [comment]
Ok, I'll report this on Skript github page. Thanks!
