### ISSUE TITLE
[BUG] Skript throws error when formatting string tag

### ISSUE THREAD

**Issue by sluhtie** [ShaneBeee/SkBee#641]
### What happened?

I noticed that if I format a string tag for example `set {_string} to unformatted (string tag "custom;AString" of nbt of player)` Skript throws an big exception in the console. The Skript does reload without problems, the error occurs as soon the expression is executed.

In order to bypass it, I would need to set a var to the tag, and than format the var.

```
[23:12:40] [Server thread/ERROR]: #!#! 
[23:12:40] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[23:12:40] [Server thread/ERROR]: #!#! 
[23:12:40] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[23:12:40] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:12:40] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:12:40] [Server thread/ERROR]: #!#! Here is full list of them:
[23:12:40] [Server thread/ERROR]: #!#! skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect) DiSky v4.16.0 SkBee v3.5.2 (https://github.com/ShaneBeee/SkBee) skript-votifier-hook v1.1.0 
[23:12:40] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:12:40] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:12:40] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:12:40] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:12:40] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:12:40] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[23:12:40] [Server thread/ERROR]: #!#! 
[23:12:40] [Server thread/ERROR]: #!#! Stack trace:
[23:12:40] [Server thread/ERROR]: #!#! java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
[23:12:40] [Server thread/ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.expressions.ExprColoured.get(ExprColoured.java:36)
[23:12:40] [Server thread/ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:88)
[23:12:40] [Server thread/ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:94)
[23:12:40] [Server thread/ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[23:12:40] [Server thread/ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[23:12:40] [Server thread/ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[23:12:40] [Server thread/ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[23:12:40] [Server thread/ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[23:12:40] [Server thread/ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155)
[23:12:40] [Server thread/ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166)
[23:12:40] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftFuture.run(CraftFuture.java:88)
[23:12:40] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[23:12:40] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1646)
[23:12:40] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[23:12:40] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1525)
[23:12:40] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[23:12:40] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:12:40] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1589)
[23:12:40] [Server thread/ERROR]: #!#! 
[23:12:40] [Server thread/ERROR]: #!#! Version Information:
[23:12:40] [Server thread/ERROR]: #!#!   Skript: 2.8.5 (latest)
[23:12:40] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[23:12:40] [Server thread/ERROR]: #!#!     Date: 16:49:26.326703600
[23:12:40] [Server thread/ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[23:12:40] [Server thread/ERROR]: #!#!   Minecraft: 1.20.4
[23:12:40] [Server thread/ERROR]: #!#!   Java: 19.0.2 (OpenJDK 64-Bit Server VM 19.0.2+7-Ubuntu-0ubuntu322.04)
[23:12:40] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.15.0-25-generic
[23:12:40] [Server thread/ERROR]: #!#! 
[23:12:40] [Server thread/ERROR]: #!#! Server platform: Paper
[23:12:40] [Server thread/ERROR]: #!#! 
[23:12:40] [Server thread/ERROR]: #!#! Current node: null
[23:12:40] [Server thread/ERROR]: #!#! Current item: set {_color} (as java.lang.Object) to uncolored [[nbttype:string tag]] "Color" of {-chatcolor::%loop-value%} (as com.shanebeestudios.skbee.api.nbt.NBTCompound)
[23:12:40] [Server thread/ERROR]: #!#! Current trigger: chat (simple event) (core/chat.sk, line 13)
[23:12:40] [Server thread/ERROR]: #!#! 
[23:12:40] [Server thread/ERROR]: #!#! Thread: Server thread
[23:12:40] [Server thread/ERROR]: #!#! 
[23:12:40] [Server thread/ERROR]: #!#! Language: english
[23:12:40] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[23:12:40] [Server thread/ERROR]: #!#! 
[23:12:40] [Server thread/ERROR]: #!#! End of Error.
[23:12:40] [Server thread/ERROR]: #!#! 
```

### Steps to reproduce

1. Try using the example from above that I provided
2. I know that the error occurs with the [Colored / Uncolored](https://skripthub.net/docs/?id=908) and [raw %string%](https://skripthub.net/docs/?id=9498) expression. Although there could be more.

### Expected behavior

That the expression gets formatted since it's a string.

### SkBee Version

3.5.2

### Server Version

Paper 1.20.4 (Build #496)

### SkBee Info

```
[09:19:05 INFO]: --- [SkBee Loading Info] ---
[09:19:05 INFO]: - [NBTAPI] Found Minecraft: v1_20_R3! Trying to find NMS support
[09:19:05 INFO]: - [NBTAPI] NMS support 'MC1_20_R3' loaded!
[09:19:05 INFO]: - NBT Elements successfully loaded
[09:19:05 INFO]: - Text Component Elements successfully loaded
[09:19:05 INFO]: - Advancement Elements successfully loaded
[09:19:05 INFO]: - BossBar Elements successfully loaded
[09:19:05 INFO]: - Bound Elements successfully loaded
[09:19:05 INFO]: - Damage Source elements successfully loaded
[09:19:05 INFO]: - Display Entity elements successfully loaded
[09:19:05 INFO]: - Fishing elements successfully loaded
[09:19:05 INFO]: - Game Event Elements successfully loaded
[09:19:05 INFO]: - Particle Elements successfully loaded
[09:19:05 INFO]: - RayTrace elements successfully loaded
[09:19:05 INFO]: - Recipe Elements successfully loaded
[09:19:05 INFO]: - Scoreboard Elements successfully loaded
[09:19:05 INFO]: - Scoreboard Objective Elements successfully loaded
[09:19:05 INFO]: - Statistic Elements successfully loaded
[09:19:05 INFO]: - Structure Elements successfully loaded
[09:19:05 INFO]: - Minecraft Tag elements successfully loaded
[09:19:05 INFO]: - Team Elements successfully loaded
[09:19:05 INFO]: - Tick Manager elements successfully loaded
[09:19:05 INFO]: - Villager Elements successfully loaded
[09:19:05 INFO]: - Virtual Furnace Elements disabled via config
[09:19:05 INFO]: - World Border Elements successfully loaded
[09:19:05 INFO]: - World Creator Elements successfully loaded
[09:19:05 INFO]: - Chunk Generator Elements disabled via config
[09:19:05 INFO]: - Plugin is up to date!
[09:19:05 INFO]: --- [Server Info] ---
[09:19:05 INFO]: Server Version: git-Paper-496 (MC: 1.20.4)
[09:19:05 INFO]: Skript Version: 2.8.5
[09:19:05 INFO]: Skript Addons:
[09:19:05 INFO]: - DiSky v4.16.0
[09:19:05 INFO]: - skript-votifier-hook v1.1.0
[09:19:05 INFO]: - skript-reflect v2.4
[09:19:05 INFO]: SkBee Version: 3.5.2
[09:19:05 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee
```

**Comment by Fusezion** [comment]
It's very unlikely there's anything we can do these errors have existed for years the only supported solution currently is just
```
set {_string} to string tag "" of {_nbt}
send uncolored {_string}
```
I'll leave open to see what shane says but he'll likely just say the same stuff

**Comment by ShaneBeee** [comment]
this one has been driving me bonkers for years.
I think I have found a solution, im going to do more testing.
