### ISSUE TITLE
[BUG] ExprAvailableMaterials Error

### ISSUE THREAD

**Issue by Chsui** [ShaneBeee/SkBee#652]
### What happened?

```
[16:14:32 INFO]: [SkBee] Enabling SkBee v3.5.3
[16:14:32 ERROR]: #!#!
[16:14:32 ERROR]: #!#! [Skript] Severe Error:
[16:14:32 ERROR]: #!#! class com.shanebeestudios.skbee.elements.other.expressions.ExprAvailableMaterials generated an exception while loading
[16:14:32 ERROR]: #!#!
[16:14:32 ERROR]: #!#! Something went horribly wrong with Skript.
[16:14:32 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:14:32 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:14:32 ERROR]: #!#! Following plugins are probably related to this error in some way:
[16:14:32 ERROR]: #!#! SkBee (https://github.com/ShaneBeee/SkBee)
[16:14:32 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:14:32 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:14:32 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:14:32 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:14:32 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:14:32 ERROR]: #!#!
[16:14:32 ERROR]: #!#! Stack trace:
[16:14:32 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "org.bukkit.loot.LootTable.getKey()" because "lootTable" is null
[16:14:32 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.elements.other.expressions.ExprAvailableMaterials.lambda$static$1(ExprAvailableMaterials.java:114)
[16:14:32 ERROR]: #!#!     at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
[16:14:32 ERROR]: #!#!     at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
[16:14:32 ERROR]: #!#!     at java.base/java.util.TimSort.sort(TimSort.java:234)
[16:14:32 ERROR]: #!#!     at java.base/java.util.Arrays.sort(Arrays.java:1308)
[16:14:32 ERROR]: #!#!     at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
[16:14:32 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
[16:14:32 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[16:14:32 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
[16:14:32 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
[16:14:32 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
[16:14:32 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
[16:14:32 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
[16:14:32 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.elements.other.expressions.ExprAvailableMaterials.<clinit>(ExprAvailableMaterials.java:114)
[16:14:32 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[16:14:32 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:534)
[16:14:32 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:513)
[16:14:32 ERROR]: #!#!     at Skript v2.8.6.jar//ch.njol.skript.util.Utils.getClasses(Utils.java:202)
[16:14:32 ERROR]: #!#!     at Skript v2.8.6.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82)
[16:14:32 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.AddonLoader.loadOtherElements(AddonLoader.java:339)
[16:14:32 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.AddonLoader.loadSkriptElements(AddonLoader.java:101)
[16:14:32 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.AddonLoader.canLoadPlugin(AddonLoader.java:91)
[16:14:32 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:61)
[16:14:32 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[16:14:32 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[16:14:32 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[16:14:32 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[16:14:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
[16:14:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
[16:14:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[16:14:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[16:14:32 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[16:14:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
[16:14:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[16:14:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[16:14:32 ERROR]: #!#!
[16:14:32 ERROR]: #!#! Version Information:
[16:14:32 ERROR]: #!#!   Skript: 2.8.6 (latest)
[16:14:32 ERROR]: #!#!     Flavor: skriptlang-github
[16:14:32 ERROR]: #!#!     Date: 15:29:23.319558700
[16:14:32 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[16:14:32 ERROR]: #!#!   Minecraft: 1.20.1
[16:14:32 ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[16:14:32 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[16:14:32 ERROR]: #!#!
[16:14:32 ERROR]: #!#! Server platform: Paper
[16:14:32 ERROR]: #!#!
[16:14:32 ERROR]: #!#! Current node: null
[16:14:32 ERROR]: #!#! Current item: null
[16:14:32 ERROR]: #!#!
[16:14:32 ERROR]: #!#! Thread: Server thread
[16:14:32 ERROR]: #!#!
[16:14:32 ERROR]: #!#! Language: english
[16:14:32 ERROR]: #!#! Link parse mode: DISABLED
[16:14:32 ERROR]: #!#!
[16:14:32 ERROR]: #!#! End of Error.
[16:14:32 ERROR]: #!#!
[16:14:32 INFO]: [SkBee] Loading NBTApi...
[16:14:32 INFO]: [SkBee] [NBTAPI] Found Minecraft: v1_20_R1! Trying to find NMS support
[16:14:32 INFO]: [SkBee] [NBTAPI] NMS support 'MC1_20_R1' loaded!
[16:14:32 INFO]: [SkBee] Successfully loaded NBTApi!
[16:14:32 INFO]: [SkBee] NBT Elements successfully loaded
[16:14:32 INFO]: [SkBee] Text Component Elements successfully loaded
[16:14:32 INFO]: [SkBee] Advancement Elements successfully loaded
[16:14:32 INFO]: [SkBee] BossBar Elements successfully loaded
[16:14:32 INFO]: [SkBee] Bound Elements successfully loaded
[16:14:32 INFO]: [SkBee] Damage Source elements disabled (Requires Minecraft 1.20.4+)
[16:14:32 INFO]: [SkBee] Display Entity elements successfully loaded
[16:14:32 INFO]: [SkBee] Fishing elements successfully loaded
[16:14:32 INFO]: [SkBee] Game Event Elements successfully loaded
[16:14:32 INFO]: [SkBee] Particle Elements successfully loaded
[16:14:32 INFO]: [SkBee] RayTrace elements successfully loaded
[16:14:32 INFO]: [SkBee] Recipe Elements successfully loaded
[16:14:32 INFO]: [SkBee] Scoreboard Elements successfully loaded
[16:14:32 INFO]: [SkBee] Scoreboard Objective Elements successfully loaded
[16:14:32 INFO]: [SkBee] Statistic Elements successfully loaded
[16:14:32 INFO]: [SkBee] Structure Elements successfully loaded
[16:14:32 INFO]: [SkBee] Minecraft Tag elements successfully loaded
[16:14:32 INFO]: [SkBee] Team Elements successfully loaded
[16:14:32 INFO]: [SkBee] Tick Manager elements disabled (Requires Minecraft 1.20.4+)
[16:14:32 INFO]: [SkBee] Villager Elements successfully loaded
[16:14:32 INFO]: [SkBee] Virtual Furnace Elements disabled via config
[16:14:32 INFO]: [SkBee] World Border Elements successfully loaded
[16:14:32 INFO]: [SkBee] World Creator Elements successfully loaded
[16:14:32 INFO]: [SkBee] Chunk Generator Elements disabled via config
[16:14:32 INFO]: [SkBee] Loaded (384) elements:
[16:14:32 INFO]: [SkBee]  - 56 events
[16:14:32 INFO]: [SkBee]  - 57 effects
[16:14:32 INFO]: [SkBee]  - 237 expressions
[16:14:32 INFO]: [SkBee]  - 23 conditions
[16:14:32 INFO]: [SkBee]  - 11 sections
[16:14:32 INFO]: [SkBee] Checking for update...
[16:14:33 INFO]: [SkBee] Plugin is up to date!
[16:14:33 INFO]: [SkBee] Successfully enabled v3.5.3 in 0.69 seconds
```

### Steps to reproduce

1. Enabling SkBee

### Expected behavior

No Error in Enabling

### SkBee Version

3.5.3

### Server Version

paper 1.20.1 b196

### SkBee Info

[16:15:10 INFO]: --- [Server Info] ---
[16:15:10 INFO]: Server Version: git-Paper-196 (MC: 1.20.1)
[16:15:10 INFO]: Skript Version: 2.8.6
[16:15:10 INFO]: Skript Addons:
[16:15:10 INFO]: - Skent v3.2.2
[16:15:10 INFO]: - skript-reflect v2.4
[16:15:10 INFO]: - Hippo v1.1.1
[16:15:10 INFO]: SkBee Version: 3.5.3
[16:15:10 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by ShaneBeee** [comment]
So, I wasn't able to replicate this, but I do see an issue in the code.
I've applied a fix that I hope fixes it for you, but since I can't test it, I'm not sure of its outcome.
