### ISSUE TITLE
[BUG] NBT, I think so.

### ISSUE THREAD

**Issue by ANormalGuys123** [ShaneBeee/SkBee#653]
### What happened?
```
[09:37:30 ERROR]: #!#! 
[09:37:30 ERROR]: #!#! [Skript] Severe Error:
[09:37:30 ERROR]: #!#! 
[09:37:30 ERROR]: #!#! Something went horribly wrong with Skript.
[09:37:30 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:37:30 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[09:37:30 ERROR]: #!#! Here is full list of them:
[09:37:30 ERROR]: #!#! skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect) SkBee v3.5.3 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.4.1 DiscordSRV v1.27.0 (https://github.com/DiscordSRV/DiscordSRV) 
[09:37:30 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[09:37:30 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[09:37:30 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[09:37:30 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[09:37:30 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[09:37:30 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[09:37:30 ERROR]: #!#! 
[09:37:30 ERROR]: #!#! Stack trace:
[09:37:30 ERROR]: #!#! java.lang.IllegalArgumentException: material must not be null
[09:37:30 ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[09:37:30 ERROR]: #!#!     at org.bukkit.inventory.meta.trim.ArmorTrim.<init>(ArmorTrim.java:32)
[09:37:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftMetaArmor.<init>(CraftMetaArmor.java:74)
[09:37:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftMetaColorableArmor.<init>(CraftMetaColorableArmor.java:32)
[09:37:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:340)
[09:37:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:287)
[09:37:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:279)
[09:37:30 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.api.nbt.NBTCustomItemStack.saveCompound(NBTCustomItemStack.java:42)
[09:37:30 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.mergeCompound(NBTCompound.java:151)
[09:37:30 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.elements.nbt.types.SkriptTypes$1.change(SkriptTypes.java:40)
[09:37:30 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.elements.nbt.types.SkriptTypes$1.change(SkriptTypes.java:24)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.util.SimpleExpression.change(SimpleExpression.java:263)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:292)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:86)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:311)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[09:37:30 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.effects.Delay.lambda$walk$0(Delay.java:107)
[09:37:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[09:37:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[09:37:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[09:37:30 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[09:37:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[09:37:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[09:37:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[09:37:30 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[09:37:30 ERROR]: #!#! 
[09:37:30 ERROR]: #!#! Version Information:
[09:37:30 ERROR]: #!#!   Skript: 2.8.6 (latest)
[09:37:30 ERROR]: #!#!     Flavor: skriptlang-github
[09:37:30 ERROR]: #!#!     Date: 15:29:23.319558700
[09:37:30 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[09:37:30 ERROR]: #!#!   Minecraft: 1.19.4
[09:37:30 ERROR]: #!#!   Java: 17.0.11 (OpenJDK 64-Bit Server VM 17.0.11+9)
[09:37:30 ERROR]: #!#!   OS: Linux amd64 5.15.0-112-generic
[09:37:30 ERROR]: #!#! 
[09:37:30 ERROR]: #!#! Server platform: Paper
[09:37:30 ERROR]: #!#! 
[09:37:30 ERROR]: #!#! Current node: null
[09:37:30 ERROR]: #!#! Current item: add nbt from "{Trim:{material:"minecraft:%lowercase%",pattern:"minecraft:%lowercase%"}}" to nbt from {skitemcreator.items.database::%{_file_name} (as java.lang.Object)%::final-item} (as java.lang.Object)
[09:37:30 ERROR]: #!#! Current trigger: function SKICLoadConfig (simple event) (SkItemCreator/SkItemCreator.sk, line 13)
[09:37:30 ERROR]: #!#! 
[09:37:30 ERROR]: #!#! Thread: Server thread
[09:37:30 ERROR]: #!#! 
[09:37:30 ERROR]: #!#! Language: english
[09:37:30 ERROR]: #!#! Link parse mode: DISABLED
[09:37:30 ERROR]: #!#! 
[09:37:30 ERROR]: #!#! End of Error.
[09:37:30 ERROR]: #!#! 

```
### Steps to reproduce

1.I downloaded the newest skbee addon
2.then when I restarted to start the addon
3.It had this line

### Expected behavior

no

### SkBee Version

3.5.3

### Server Version

Paper 1.19.4

### SkBee Info

![Screenshot 2024-06-10 164200](https://github.com/ShaneBeee/SkBee/assets/172186327/043d899f-94fd-4bc9-905d-ca45868fcd35)
![Screenshot 2024-06-10 164548](https://github.com/ShaneBeee/SkBee/assets/172186327/c0bb639c-8ca4-45a2-b2bc-da0687a1b594)
![Screenshot 2024-06-10 164558](https://github.com/ShaneBeee/SkBee/assets/172186327/7d95aec7-5447-4ae0-839c-0eb615614626)

### Additional Information

no

**Comment by ShaneBeee** [comment]
do you have the code/NBT to replicate this?

**Comment by ANormalGuys123** [comment]
![image](https://github.com/ShaneBeee/SkBee/assets/172186327/363f33cc-af9b-4fcb-99d3-1fb9db65bbe4)
I don't think so

**Comment by ShaneBeee** [comment]
I never said it was a Skript issue.
Based on the error, you're putting nbt for an armor trim, but your "material" entry is incorrect and/or missing, therefor the server can't make the the armor trim, and is throwing that error.

The error comes much after NBT is handled and really nothing I can do about it.

You're going to either have to:
a) use valid NBT
b) use SkBee's amor trim expressions
