### ISSUE TITLE
[BUG] Spawning a display entity throws an error and does not spawn

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [ShaneBeee/SkBee#664]
### What happened?

An error shows up in console when trying to spawn a display entity, and in game it says an interal error occurred
![image](https://github.com/ShaneBeee/SkBee/assets/70504198/3c79f020-8e4a-4128-bb34-a94b9b77a798)

Error:
```log
[00:46:29 INFO]: MinecraftMan1013 issued server command: /displayentity
[00:46:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'displayentity' in plugin Skript v2.8.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-550]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2257) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity org.bukkit.World.spawn(org.bukkit.Location, java.lang.Class, java.util.function.Consumer)'
        at com.shanebeestudios.skbee.elements.other.sections.SecSpawnMinecraftEntity.walk(SecSpawnMinecraftEntity.java:110) ~[SkBee-3.5.4.jar:?]
        at ch.njol.skript.lang.EffectSectionEffect.walk(EffectSectionEffect.java:47) ~[Skript-2.8.5.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[Skript-2.8.5.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript-2.8.5.jar:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316) ~[Skript-2.8.5.jar:?]
        at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275) ~[Skript-2.8.5.jar:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286) ~[Skript-2.8.5.jar:?]
        at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221) ~[Skript-2.8.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

### Steps to reproduce

Code used to test:
```
command /displayentity:
	permission: op
	trigger:
		skbee spawn text display at (location of player)
```

### Expected behavior

A display entity spawns

### SkBee Version

3.5.4

### Server Version

git-Paper-545 (MC: 1.19.4)

### SkBee Info

```log
[00:50:04 INFO]: --- [SkBee Loading Info] ---
[00:50:04 INFO]: - [NBTAPI] Found Minecraft: v1_19_R3! Trying to find NMS support
[00:50:04 INFO]: - [NBTAPI] NMS support 'MC1_19_R3' loaded!
[00:50:04 INFO]: - NBT Elements successfully loaded
[00:50:04 INFO]: - Text Component Elements successfully loaded
[00:50:04 INFO]: - Advancement Elements successfully loaded
[00:50:04 INFO]: - BossBar Elements successfully loaded
[00:50:04 INFO]: - Bound Elements successfully loaded
[00:50:04 INFO]: - Damage Source elements disabled (Requires Minecraft 1.20.4+)
[00:50:04 INFO]: - Display Entity elements successfully loaded
[00:50:04 INFO]: - Fishing elements successfully loaded
[00:50:04 INFO]: - Game Event Elements successfully loaded
[00:50:04 INFO]: - Particle Elements successfully loaded
[00:50:04 INFO]: - RayTrace elements successfully loaded
[00:50:04 INFO]: - Recipe Elements successfully loaded
[00:50:04 INFO]: - Scoreboard Elements successfully loaded
[00:50:04 INFO]: - Scoreboard Objective Elements successfully loaded
[00:50:04 INFO]: - Statistic Elements successfully loaded
[00:50:04 INFO]: - Structure Elements successfully loaded
[00:50:04 INFO]: - Minecraft Tag elements successfully loaded
[00:50:04 INFO]: - Team Elements successfully loaded
[00:50:04 INFO]: - Tick Manager elements disabled (Requires Minecraft 1.20.4+)
[00:50:04 INFO]: - Villager Elements successfully loaded
[00:50:04 INFO]: - Virtual Furnace Elements successfully loaded
[00:50:04 INFO]: - World Border Elements successfully loaded
[00:50:04 INFO]: - World Creator Elements successfully loaded
[00:50:04 INFO]: - Chunk Generator Elements successfully loaded
[00:50:04 INFO]: - Plugin is up to date!
[00:50:04 INFO]: --- [Server Info] ---
[00:50:04 INFO]: Server Version: git-Paper-550 (MC: 1.19.4)
[00:50:04 INFO]: Skript Version: 2.8.5
[00:50:04 INFO]: Skript Addons:
[00:50:04 INFO]: SkBee Version: 3.5.4
[00:50:04 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee
```

### Additional Information

One thing I notice is that SkBee loading log and the stack trace says `v1_19_R3`, even though the server is 1.19.4 (I have no idea if this makes any difference)

The only plugins on the server are Skript 2.8.5 and SkBee
![image](https://github.com/ShaneBeee/SkBee/assets/70504198/d63318e9-78c8-4476-93ef-062346fd83be)
![image](https://github.com/ShaneBeee/SkBee/assets/70504198/0b243390-fdc1-40f4-8c57-530150af12ce)

**Comment by ShaneBeee** [comment]
use Skript's spawn effect/section.
SkBee's was only a temp solution until Skript added the entities.

**Comment by ShaneBeee** [comment]
wait sorry, I misread that.

**Comment by MinecraftMan1013number2** [comment]
I also just realized that if I add the word `entity` before `at player`, it gives a warning
![image](https://github.com/ShaneBeee/SkBee/assets/70504198/b602dabe-9aff-42a8-bdb3-997fb678f392)
