### ISSUE TITLE
[BUG] Cannot load cloned world

### ISSUE THREAD

**Issue by Greathelloboy** [ShaneBeee/SkBee#669]
### What happened?

When I try to clone a world with the world creator syntax and then load it, an error is thrown in the console.

```
[10:48:19 WARN]: [SkBee] Plugin SkBee v3.5.6 generated an exception while executing task 30
java.lang.IllegalArgumentException: World name and key cannot be null
        at org.bukkit.WorldCreator.<init>(WorldCreator.java:59) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at SkBee-3.5.6.jar/com.shanebeestudios.skbee.elements.worldcreator.objects.BeeWorldCreator.lambda$cloneWorld$2(BeeWorldCreator.java:271) ~[SkBee-3.5.6.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### Steps to reproduce

1. Have a loaded world to clone
2. Clone a the world and load it
`set {_w} to world creator named "world_clone" to clone world "world"`
`load world from {_w}`

### Expected behavior

To load the cloned world.

### SkBee Version

3.5.6

### Server Version

Paper 1.20.6

### SkBee Info

[10:44:53 INFO]: --- [SkBee Loading Info] ---
[10:44:53 INFO]: - [NBTAPI] Found Minecraft: 1.20.6! Trying to find NMS support
[10:44:53 INFO]: - [NBTAPI] NMS support 'MC1_20_R4' loaded!
[10:44:53 INFO]: - NBT Elements successfully loaded
[10:44:53 INFO]: - Text Component Elements successfully loaded
[10:44:53 INFO]: - Advancement Elements successfully loaded
[10:44:53 INFO]: - BossBar Elements successfully loaded
[10:44:53 INFO]: - Bound Elements successfully loaded
[10:44:53 INFO]: - Damage Source elements successfully loaded
[10:44:53 INFO]: - Display Entity elements successfully loaded
[10:44:53 INFO]: - Fishing elements successfully loaded
[10:44:53 INFO]: - Game Event Elements successfully loaded
[10:44:53 INFO]: - Particle Elements successfully loaded
[10:44:53 INFO]: - RayTrace elements successfully loaded
[10:44:53 INFO]: - Recipe Elements successfully loaded
[10:44:53 INFO]: - Scoreboard Elements successfully loaded
[10:44:53 INFO]: - Scoreboard Objective Elements successfully loaded
[10:44:53 INFO]: - Statistic Elements successfully loaded
[10:44:53 INFO]: - Structure Elements successfully loaded
[10:44:53 INFO]: - Minecraft Tag elements successfully loaded
[10:44:53 INFO]: - Team Elements successfully loaded
[10:44:53 INFO]: - Tick Manager elements successfully loaded
[10:44:53 INFO]: - Villager Elements successfully loaded
[10:44:53 INFO]: - Virtual Furnace Elements disabled via config
[10:44:53 INFO]: - World Border Elements successfully loaded
[10:44:53 INFO]: - World Creator Elements successfully loaded
[10:44:53 INFO]: - Chunk Generator Elements disabled via config
[10:44:53 INFO]: - Plugin is up to date!
[10:44:53 INFO]: --- [Server Info] ---
[10:44:53 INFO]: Server Version: 1.20.6-148-20f5165 (MC: 1.20.6)
[10:44:53 INFO]: Skript Version: 2.8.7
[10:44:53 INFO]: Skript Addons:
[10:44:53 INFO]: - SkQuery v4.1.10
[10:44:53 INFO]: SkBee Version: 3.5.6
[10:44:53 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by ShaneBeee** [comment]
I found the problem, I think.
Ping me on skUnity discord and ill send you a jar to test

**Comment by Greathelloboy** [comment]
it works

**Comment by ShaneBeee** [comment]
glad to hear.
Im going to keep this open until I actually do a release
