### ISSUE TITLE
[BUG] Structures over 32x32x32 not saving.

### ISSUE THREAD

**Issue by Rayners01** [ShaneBeee/SkBee#69]
**Describe the bug**
Saving structures over 32x32x32 blocks using SkBee gives me an error in console and the structure does not load when I paste it. Before this didn't happen, but tell me if there is a setting that I forgot to change haha.

**To Reproduce**
Save a structure that is over 32x32x32 blocks.

**Expected behaviour**
Structure would just save and load in normally when I paste it.

**Screenshots/Errors**

`[17:30:51] [Server thread/INFO]: Rayners02 issued server command: /stsave cells
[17:30:51] [Server thread/INFO]: Rayners02 [34e9c956-5317-4c4b-a2d8-e481aeeaa6c0]: /stsave cells
[17:30:51] [Craft Scheduler Thread - 81/WARN]: [SkBee] Plugin SkBee v1.8.2 generated an exception while executing task 47948
java.lang.IllegalArgumentException: Axe x exceeded StructureRestriction of 32x32x32! Change the restriction or reduce the size of your selection.
	at tk.shanebee.bee.api.Structure.core.entity.StructureSaverAbstractImpl.validateDirection(StructureSaverAbstractImpl.java:494) ~[?:?]
	at tk.shanebee.bee.api.Structure.core.entity.StructureSaverAbstractImpl.validate(StructureSaverAbstractImpl.java:457) ~[?:?]
	at tk.shanebee.bee.api.Structure.core.entity.StructureSaverAbstractImpl.saveToOutputStream(StructureSaverAbstractImpl.java:412) ~[?:?]
	at tk.shanebee.bee.api.Structure.core.entity.StructureSaverAbstractImpl.lambda$saveToFile$5(StructureSaverAbstractImpl.java:378) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[spigot.jar:git-Paper-261]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot.jar:git-Paper-261]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[spigot.jar:git-Paper-261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Version Info:**
 - **SkBee Version:** 1.8.2
-  **Skript Version:** 2.5-MH
 - **Server Version/Platform** Paper 1.16.4

**Comment by ShaneBeee** [comment]
Thanks for letting me know.
This has been fixed and will appear in the next update.
