### ISSUE TITLE
[BUG] TabCompletion not work for 1.21 server

### ISSUE THREAD

**Issue by Radiation-pi** [ShaneBeee/SkBee#697]
### What happened?

[14:18:23] [Server thread/ERROR]: #!#! Stack trace:
[14:18:23] [Server thread/ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
[14:18:23] [Server thread/ERROR]: #!#!     at SkBee-3.5.9.jar//com.shanebeestudios.skbee.elements.other.expressions.ExprTabCompletion.change(ExprTabCompletion.java:101)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:292)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$2(SkriptEventHandler.java:183)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$3(SkriptEventHandler.java:194)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler.execute(SkriptEventHandler.java:192)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:138)
[14:18:23] [Server thread/ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:64)
[14:18:23] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72)
[14:18:23] [Server thread/ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:60)
[14:18:23] [Server thread/ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[14:18:23] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[14:18:23] [Server thread/ERROR]: #!#!     at org.bukkit.event.Event.callEvent(Event.java:71)
[14:18:23] [Server thread/ERROR]: #!#!     at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigSuggestionProvider.getSuggestions(BukkitCommandNode.java:120)
[14:18:23] [Server thread/ERROR]: #!#!     at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71)
[14:18:23] [Server thread/ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:551)
[14:18:23] [Server thread/ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:531)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.sendServerSuggestions(ServerGamePacketListenerImpl.java:862)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions0$3(ServerGamePacketListenerImpl.java:823)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1555)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1533)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1526)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1484)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1491)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1338)
[14:18:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[14:18:23] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[14:18:23] [Server thread/ERROR]: #!#! 

[14:18:23] [Server thread/ERROR]: #!#! Current node: null
[14:18:23] [Server thread/ERROR]: #!#! Current item: add ("on" and "off")[class java.lang.String] to tab completions
[14:18:23] [Server thread/ERROR]: #!#! Current trigger: tab complete of "/bt" (tab complete for [/bt]) (../../../../terra/plugins/Skript/scripts/bt.sk, line 99)

### Steps to reproduce

1. install skript 2.9.1 + skbee 3.5.9 in 1.21 server
2. use some TabCompletion in script

on tab complete of "/world":
    add "world", "world_nether", "world_the_end" to tab completions

### Expected behavior

error come with:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1

### SkBee Version

3.5.9 (the lastest)

### Server Version

1.21

### SkBee Info

[14:34:57 INFO]: --- [SkBee Loading Info] ---
[14:34:57 INFO]: - [NBTAPI] Found Minecraft: 1.21! Trying to find NMS support
[14:34:57 INFO]: - [NBTAPI] NMS support 'MC1_21_R1' loaded!
[14:34:57 INFO]: - Advancement Elements disabled via config
[14:34:57 INFO]: - BossBar Elements disabled via config
[14:34:57 INFO]: - Fishing elements disabled via config
[14:34:57 INFO]: - Game Event Elements disabled via config
[14:34:57 INFO]: - Statistic Elements disabled via config
[14:34:57 INFO]: - Structure Elements disabled via config
[14:34:57 INFO]: - Team Elements disabled via config
[14:34:57 INFO]: - Virtual Furnace Elements disabled via config
[14:34:57 INFO]: - World Border Elements disabled via config
[14:34:57 INFO]: - Plugin is up to date!
[14:34:57 INFO]: --- [Server Info] ---
[14:34:57 INFO]: Server Version: 1.21-DEV-d4fcc79 (MC: 1.21)
[14:34:57 INFO]: Skript Version: 2.9.1
[14:34:57 INFO]: Skript Addons:
[14:34:57 INFO]: - skript-placeholders v1.6-dev-nightly-b730ffa
[14:34:57 INFO]: - skript-reflect v2.5.1
[14:34:57 INFO]: - ItemsAdder v4.0.2-alpha-test-3
[14:34:57 INFO]: SkBee Version: 3.5.9
[14:34:57 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by Radiation-pi** [comment]
It works well now, thanks!
