### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Xosmuits** [ShaneBeee/SkBee#706]
### What happened?

ERROR]: #!#! 
[17:36:20 ERROR]: #!#! [Skript] Severe Error:
[17:36:20 ERROR]: #!#! 
[17:36:20 ERROR]: #!#! Something went horribly wrong with Skript.
[17:36:20 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:36:20 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:36:20 ERROR]: #!#! Here is full list of them:
[17:36:20 ERROR]: #!#! SkBee v3.6.1 (https://github.com/ShaneBeee/SkBee) 
[17:36:20 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:36:20 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:36:20 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:36:20 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:36:20 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:36:20 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:36:20 ERROR]: #!#! 
[17:36:20 ERROR]: #!#! Stack trace:
[17:36:20 ERROR]: #!#! java.lang.ClassCastException: class org.bukkit.util.Vector cannot be cast to class java.lang.Number (org.bukkit.util.Vector is in unnamed module of loader java.net.URLClassLoader @4e515669; java.lang.Number is in module java.base of loader 'bootstrap')
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.expressions.arithmetic.ArithmeticChain.get(ArithmeticChain.java:103)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.expressions.arithmetic.ExprArithmetic.get(ExprArithmetic.java:318)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:97)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:78)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:323)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$2(SkriptEventHandler.java:183)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$3(SkriptEventHandler.java:194)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler.execute(SkriptEventHandler.java:192)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:138)
[17:36:20 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:64)
[17:36:20 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:36:20 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:36:20 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[17:36:20 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[17:36:20 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[17:36:20 ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerCommand(ServerGamePacketListenerImpl.java:2612)
[17:36:20 ERROR]: #!#!     at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:46)
[17:36:20 ERROR]: #!#!     at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:18)
[17:36:20 ERROR]: #!#!     at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[17:36:20 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:36:20 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[17:36:20 ERROR]: #!#!     at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[17:36:20 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
[17:36:20 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[17:36:20 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[17:36:20 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
[17:36:20 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[17:36:20 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[17:36:20 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629)
[17:36:20 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[17:36:20 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[17:36:20 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[17:36:20 ERROR]: #!#! 
[17:36:20 ERROR]: #!#! Version Information:
[17:36:20 ERROR]: #!#!   Skript: 2.9.1 (latest)
[17:36:20 ERROR]: #!#!     Flavor: skriptlang-github
[17:36:20 ERROR]: #!#!     Date: 14:17:55.682181900
[17:36:20 ERROR]: #!#!   Bukkit: 1.21.1-R0.1-SNAPSHOT
[17:36:20 ERROR]: #!#!   Minecraft: 1.21.1
[17:36:20 ERROR]: #!#!   Java: 21.0.2 (Java HotSpot(TM) 64-Bit Server VM 21.0.2+13-LTS-58)
[17:36:20 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[17:36:20 ERROR]: #!#! 
[17:36:20 ERROR]: #!#! Server platform: Paper
[17:36:20 ERROR]: #!#! 
[17:36:20 ERROR]: #!#! Current node: null
[17:36:20 ERROR]: #!#! Current item: set {_densityVectorDistance} (as java.lang.Object) to {_vectorFromXtoY} (as java.lang.Object) / {_densityLength} (as java.lang.Object)
[17:36:20 ERROR]: #!#! Current trigger: function drawLine (simple event) (a.sk, line 1)
[17:36:20 ERROR]: #!#! 
[17:36:20 ERROR]: #!#! Thread: Server thread
[17:36:20 ERROR]: #!#! 
[17:36:20 ERROR]: #!#! Language: english
[17:36:20 ERROR]: #!#! Link parse mode: DISABLED
[17:36:20 ERROR]: #!#! 
[17:36:20 ERROR]: #!#! End of Error.
[17:36:20 ERROR]: #!#! 

### Steps to reproduce

```
function drawLine(from:location, to:location, density:number, particle:particle, extra:object={_null}):
    set {_vectorFromXtoY} to vector from {_from} to {_to}
    set {_length} to ceil(vector length of {_vectorFromXtoY})
    set {_densityLength} to min(ceil({_length} / {_density}), 16384)
    set {_densityVectorDistance} to {_vectorFromXtoY} / {_densityLength} # this line breaks possible using '//' instead will solve it on chunk unload
    loop {_densityLength} times:
        if {_extra} is set:
            draw 1 {_particle} using {_extra} at {_from} with extra 0 with force
        else:
            draw 1 {_particle} at {_from} with extra 0 with force
        set {_from} to {_from} ~ {_densityVectorDistance}


on sneak toggle:
	drawLine(player, target, 0.5, small_flame)
```
	using this script but whenever i toggle sneak this pops up at the console and skript stops working
	

### Expected behavior

```
function drawLine(from:location, to:location, density:number, particle:particle, extra:object={_null}):
    set {_vectorFromXtoY} to vector from {_from} to {_to}
    set {_length} to ceil(vector length of {_vectorFromXtoY})
    set {_densityLength} to min(ceil({_length} / {_density}), 16384)
    set {_densityVectorDistance} to {_vectorFromXtoY} / {_densityLength} # this line breaks possible using '//' instead will solve it on chunk unload
    loop {_densityLength} times:
        if {_extra} is set:
            draw 1 {_particle} using {_extra} at {_from} with extra 0 with force
        else:
            draw 1 {_particle} at {_from} with extra 0 with force
        set {_from} to {_from} ~ {_densityVectorDistance}


on sneak toggle:
	drawLine(player, target, 0.5, small_flame)
```
	using this script but whenever i toggle sneak this pops up at the console and skript stops working
	

### SkBee Version

3.6.1

### Server Version

1.21.1

### SkBee Info

![image](https://github.com/user-attachments/assets/110d5018-a4ec-41e3-b07c-a0d711835de4)

**Comment by Fusezion** [comment]
This is a skript issue with their arithmetic and not an skbee issue, create an issue on their github at https://github.com/SkriptLang/Skript/issues/new/choose
