### ISSUE TITLE
[BUG] Errors with addon, inventory click

### ISSUE THREAD

**Issue by LuCkyLuKie** [ShaneBeee/SkBee#89]
**Describe the bug**
Script is still working, but it shows some errors in console. It keeps showing every 2/5 minutes.

**To Reproduce**
https://pastebin.com/qErMaVKe
My script if you wanna check it.

**Expected behavior**
I blocked mending enchanted book, it disappears when it is dropped, clicked or pick up.

**Screenshots/Errors**
https://pastebin.com/qtqt1mFJ  logs from console

**Version Info:**
 - **SkBee Version:** ( 1.9.0)
-  **Skript Version:** ( 2.5.3)
 - **Server Version/Platform** (git-Paper-325 MC 1.16.4)

**Additional context**
Any fixes to script or addon to show less errors in console? Sorry for bad english, if some things aren't understable

**Comment by ShaneBeee** [comment]
I can't not seem to replicate this error.

Which inventory are you clicking in when this happens?
I tried clicking in my own inventory, as well as a chest, and neither time did the error pop up.

The error itself is coming from Skript. My guess is Skript isn't recognizing the inventory type or something

**Comment by LuCkyLuKie** [comment]
I am clicking nothing when it appears in console. It's strange because it appears in random time on server, neither players have got mending book. I've got my server on titanaxe hosting and I cannot manually update server engine. I will talk to them and then I will reply if error keep showing.

**Comment by ShaneBeee** [comment]
According to the error, its coming from an inventory click event.
So it must be happening when a player is clicking their inventory.

Regardless, this is not an SkBee bug, this is happening on Skript's side. But looking at Skript's code, it seems odd that it would be happening anyway.

without know what exactly is happening for this error to show in console, makes it really hard to crackdown where the issue is coming from.

**Comment by LuCkyLuKie** [comment]
Nothing changed after updating paper to the latest version (git-Paper-400).

Still showing this error message.
```
[13:08:26 ERROR]: #!#!
[13:08:26 ERROR]: #!#! [Skript] Severe Error:
[13:08:26 ERROR]: #!#!
[13:08:26 ERROR]: #!#! Something went horribly wrong with Skript.
[13:08:26 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:08:26 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:08:26 ERROR]: #!#! Here is full list of them:
[13:08:26 ERROR]: #!#! SkBee v1.9.0 (https://github.com/ShaneBeee/SkBee) skUtilities v0.9.2 (https://tim740.github.io/) SkQuery v4.1.4 Factions v1.6.9.5-2.6.2-STABLE
[13:08:26 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:08:26 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:08:26 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:08:26 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:08:26 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:08:26 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[13:08:26 ERROR]: #!#!
[13:08:26 ERROR]: #!#! Stack trace:
[13:08:26 ERROR]: #!#! java.lang.NullPointerException
[13:08:26 ERROR]: #!#!     at ch.njol.skript.util.slot.InventorySlot.getItem(InventorySlot.java:65)
[13:08:26 ERROR]: #!#!     at tk.shanebee.bee.api.NBTApi.getNBT(NBTApi.java:268)
[13:08:26 ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprObjectNBT.convert(ExprObjectNBT.java:73)
[13:08:26 ERROR]: #!#!     at tk.shanebee.bee.elements.nbt.expressions.ExprObjectNBT.convert(ExprObjectNBT.java:25)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:390)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:381)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:102)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:53)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:73)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:159)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.conditions.CondContains.check(CondContains.java:139)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:55)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:50)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153)
[13:08:26 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111)
[13:08:26 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:08:26 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:08:26 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2540)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1128)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1121)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1257)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992)
[13:08:26 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
[13:08:26 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[13:08:26 ERROR]: #!#!
[13:08:26 ERROR]: #!#! Version Information:
[13:08:26 ERROR]: #!#!   Skript: 2.5.3
[13:08:26 ERROR]: #!#!     Flavor: skriptlang-github
[13:08:26 ERROR]: #!#!     Date: 2020-12-11
[13:08:26 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[13:08:26 ERROR]: #!#!   Minecraft: 1.16.4
[13:08:26 ERROR]: #!#!   Java: 11 (OpenJDK 64-Bit Server VM 11+28)
[13:08:26 ERROR]: #!#!   OS: Linux amd64 3.10.0-1062.12.1.el7.x86_64
[13:08:26 ERROR]: #!#!
[13:08:26 ERROR]: #!#! Server platform: Paper
[13:08:26 ERROR]: #!#!
[13:08:26 ERROR]: #!#! Current node: null
[13:08:26 ERROR]: #!#! Current item: the object nbt of event-slot contains "{StoredEnchantments:[{id:"minecraft:mending",lvl:1s}]}"
[13:08:26 ERROR]: #!#! Current trigger: inventory click (dispense/spawn/drop/craft/pickup/consume/break/despawn/merge) (mending.sk, line 12)
[13:08:26 ERROR]: #!#!
[13:08:26 ERROR]: #!#! Thread: Server thread
[13:08:26 ERROR]: #!#!
[13:08:26 ERROR]: #!#! Language: english
[13:08:26 ERROR]: #!#! Link parse mode: DISABLED
[13:08:26 ERROR]: #!#!
[13:08:26 ERROR]: #!#! End of Error.
[13:08:26 ERROR]: #!#!
```

When i was on the server and when it appeared in console, I checked inventories of players, and there was only one player with enchantment (not mending) on his fishing rod. So i asked him to click on it and change slot of it. He did it, but error didn't appear. I don't know what it causes, but skript is still working fine...

**Comment by LuCkyLuKie** [comment]
I changed skript a little to this version:
```
on inventory click:
	if event-item is enchanted book:
		if nbt of event-slot contains "{StoredEnchantments:[{id:""minecraft:mending"",lvl:1s}]}":
			cancel event
			set event-slot to air
			message "&c&l[i] &7Przepraszamy, ale &cMending &7jest zablokowany na tym serwerze!"
```
I will look for errors from now and I will reply if something will go on.
